/* about.c generated by valac 0.40.23, the Vala compiler
 * generated from about.vala, do not modify */

/*
 Copyright (C) 2018-2019 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "config.h"
#include <glib/gi18n-lib.h>
#include <gio/gio.h>


#define MIDORI_TYPE_ABOUT (midori_about_get_type ())
#define MIDORI_ABOUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_ABOUT, MidoriAbout))
#define MIDORI_ABOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_ABOUT, MidoriAboutClass))
#define MIDORI_IS_ABOUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_ABOUT))
#define MIDORI_IS_ABOUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_ABOUT))
#define MIDORI_ABOUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_ABOUT, MidoriAboutClass))

typedef struct _MidoriAbout MidoriAbout;
typedef struct _MidoriAboutClass MidoriAboutClass;
typedef struct _MidoriAboutPrivate MidoriAboutPrivate;
enum  {
	MIDORI_ABOUT_0_PROPERTY,
	MIDORI_ABOUT_NUM_PROPERTIES
};
static GParamSpec* midori_about_properties[MIDORI_ABOUT_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MidoriAbout {
	GtkAboutDialog parent_instance;
	MidoriAboutPrivate * priv;
};

struct _MidoriAboutClass {
	GtkAboutDialogClass parent_class;
};


static gpointer midori_about_parent_class = NULL;

GType midori_about_get_type (void) G_GNUC_CONST;
MidoriAbout* midori_about_new (GtkWindow* parent);
MidoriAbout* midori_about_construct (GType object_type,
                                     GtkWindow* parent);
static void __lambda4_ (MidoriAbout* self);
static void ___lambda4__gtk_button_clicked (GtkButton* _sender,
                                     gpointer self);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 20 "/home/test/core/core/about.vala"
	return self ? g_object_ref (self) : NULL;
#line 74 "about.c"
}


static void
__lambda4_ (MidoriAbout* self)
{
	GFile** files = NULL;
	GFile** _tmp0_;
	gint files_length1;
	gint _files_size_;
	GFile* _tmp1_;
	GApplication* _tmp2_;
#line 22 "/home/test/core/core/about.vala"
	_tmp0_ = g_new0 (GFile*, 1 + 1);
#line 22 "/home/test/core/core/about.vala"
	files = _tmp0_;
#line 22 "/home/test/core/core/about.vala"
	files_length1 = 1;
#line 22 "/home/test/core/core/about.vala"
	_files_size_ = files_length1;
#line 23 "/home/test/core/core/about.vala"
	_tmp1_ = g_file_new_for_uri (PROJECT_BUGS);
#line 23 "/home/test/core/core/about.vala"
	_g_object_unref0 (files[0]);
#line 23 "/home/test/core/core/about.vala"
	files[0] = _tmp1_;
#line 24 "/home/test/core/core/about.vala"
	_tmp2_ = g_application_get_default ();
#line 24 "/home/test/core/core/about.vala"
	g_application_open (_tmp2_, files, files_length1, "");
#line 21 "/home/test/core/core/about.vala"
	files = (_vala_array_free (files, files_length1, (GDestroyNotify) g_object_unref), NULL);
#line 107 "about.c"
}


static void
___lambda4__gtk_button_clicked (GtkButton* _sender,
                                gpointer self)
{
#line 21 "/home/test/core/core/about.vala"
	__lambda4_ ((MidoriAbout*) self);
#line 117 "about.c"
}


MidoriAbout*
midori_about_construct (GType object_type,
                        GtkWindow* parent)
{
	MidoriAbout * self = NULL;
	GtkButton* report = NULL;
	GtkWidget* _tmp0_;
	GtkButton* _tmp1_;
#line 15 "/home/test/core/core/about.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 16 "/home/test/core/core/about.vala"
	self = (MidoriAbout*) g_object_new (object_type, "transient-for", parent, "logo-icon-name", PROJECT_DOMAIN, "website", PROJECT_WEBSITE, "version", CORE_VERSION, NULL);
#line 20 "/home/test/core/core/about.vala"
	_tmp0_ = gtk_dialog_add_button ((GtkDialog*) self, _ ("_Report a Problem…"), (gint) GTK_RESPONSE_HELP);
#line 20 "/home/test/core/core/about.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, gtk_button_get_type ()) ? ((GtkButton*) _tmp0_) : NULL);
#line 20 "/home/test/core/core/about.vala"
	report = _tmp1_;
#line 21 "/home/test/core/core/about.vala"
	g_signal_connect_object (report, "clicked", (GCallback) ___lambda4__gtk_button_clicked, self, 0);
#line 15 "/home/test/core/core/about.vala"
	_g_object_unref0 (report);
#line 15 "/home/test/core/core/about.vala"
	return self;
#line 145 "about.c"
}


MidoriAbout*
midori_about_new (GtkWindow* parent)
{
#line 15 "/home/test/core/core/about.vala"
	return midori_about_construct (MIDORI_TYPE_ABOUT, parent);
#line 154 "about.c"
}


static void
midori_about_class_init (MidoriAboutClass * klass)
{
#line 14 "/home/test/core/core/about.vala"
	midori_about_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/test/core/core/about.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/ui/about.ui");
#line 165 "about.c"
}


static void
midori_about_instance_init (MidoriAbout * self)
{
#line 14 "/home/test/core/core/about.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 174 "about.c"
}


GType
midori_about_get_type (void)
{
	static volatile gsize midori_about_type_id__volatile = 0;
	if (g_once_init_enter (&midori_about_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriAboutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_about_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriAbout), 0, (GInstanceInitFunc) midori_about_instance_init, NULL };
		GType midori_about_type_id;
		midori_about_type_id = g_type_register_static (gtk_about_dialog_get_type (), "MidoriAbout", &g_define_type_info, 0);
		g_once_init_leave (&midori_about_type_id__volatile, midori_about_type_id);
	}
	return midori_about_type_id__volatile;
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



