/* favicon.c generated by valac 0.40.23, the Vala compiler
 * generated from favicon.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include "webkit2/webkit2.h"
#include <gio/gio.h>
#include <cairo.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>


#define MIDORI_TYPE_FAVICON (midori_favicon_get_type ())
#define MIDORI_FAVICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_FAVICON, MidoriFavicon))
#define MIDORI_FAVICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_FAVICON, MidoriFaviconClass))
#define MIDORI_IS_FAVICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_FAVICON))
#define MIDORI_IS_FAVICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_FAVICON))
#define MIDORI_FAVICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_FAVICON, MidoriFaviconClass))

typedef struct _MidoriFavicon MidoriFavicon;
typedef struct _MidoriFaviconClass MidoriFaviconClass;
typedef struct _MidoriFaviconPrivate MidoriFaviconPrivate;
enum  {
	MIDORI_FAVICON_0_PROPERTY,
	MIDORI_FAVICON_SURFACE_PROPERTY,
	MIDORI_FAVICON_URI_PROPERTY,
	MIDORI_FAVICON_NUM_PROPERTIES
};
static GParamSpec* midori_favicon_properties[MIDORI_FAVICON_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _MidoriFaviconLoadIconData MidoriFaviconLoadIconData;

struct _MidoriFavicon {
	GtkImage parent_instance;
	MidoriFaviconPrivate * priv;
};

struct _MidoriFaviconClass {
	GtkImageClass parent_class;
};

struct _MidoriFaviconPrivate {
	gchar* _uri;
	WebKitFaviconDatabase* database;
};

struct _MidoriFaviconLoadIconData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	MidoriFavicon* self;
	GCancellable* cancellable;
	WebKitFaviconDatabase* _tmp0_;
	WebKitWebContext* _tmp1_;
	WebKitFaviconDatabase* _tmp2_;
	WebKitFaviconDatabase* _tmp3_;
	WebKitFaviconDatabase* _tmp4_;
	cairo_surface_t* _tmp5_;
	WebKitFaviconDatabase* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	cairo_surface_t* _tmp9_;
	GError* _error_;
	GError* _tmp10_;
	const gchar* _tmp11_;
	GError* _inner_error0_;
};


static gpointer midori_favicon_parent_class = NULL;

GType midori_favicon_get_type (void) G_GNUC_CONST;
#define MIDORI_FAVICON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_FAVICON, MidoriFaviconPrivate))
static void midori_favicon_load_icon_data_free (gpointer _data);
static void midori_favicon_load_icon (MidoriFavicon* self,
                               GCancellable* cancellable,
                               GAsyncReadyCallback _callback_,
                               gpointer _user_data_);
static void midori_favicon_load_icon_finish (MidoriFavicon* self,
                                      GAsyncResult* _res_);
static gboolean midori_favicon_load_icon_co (MidoriFaviconLoadIconData* _data_);
static void ___lambda23_ (MidoriFavicon* self,
                   const gchar* page_uri,
                   const gchar* favicon_uri);
const gchar* midori_favicon_get_uri (MidoriFavicon* self);
static void ____lambda23__webkit_favicon_database_favicon_changed (WebKitFaviconDatabase* _sender,
                                                            const gchar* page_uri,
                                                            const gchar* favicon_uri,
                                                            gpointer self);
static void midori_favicon_load_icon_ready (GObject* source_object,
                                     GAsyncResult* _res_,
                                     gpointer _user_data_);
void midori_favicon_set_surface (MidoriFavicon* self,
                                 cairo_surface_t* value);
static GdkPixbuf* midori_favicon_scale_to_icon_size (MidoriFavicon* self,
                                              GdkPixbuf* pixbuf);
MidoriFavicon* midori_favicon_new (void);
MidoriFavicon* midori_favicon_construct (GType object_type);
void midori_favicon_set_uri (MidoriFavicon* self,
                             const gchar* value);
static void midori_favicon_finalize (GObject * obj);
static void _vala_midori_favicon_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec);
static void _vala_midori_favicon_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec);


static void
midori_favicon_load_icon_data_free (gpointer _data)
{
	MidoriFaviconLoadIconData* _data_;
	_data_ = _data;
#line 13 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (_data_->cancellable);
#line 13 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (_data_->self);
#line 13 "/home/test/core/core/favicon.vala"
	g_slice_free (MidoriFaviconLoadIconData, _data_);
#line 143 "favicon.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 13 "/home/test/core/core/favicon.vala"
	return self ? g_object_ref (self) : NULL;
#line 152 "favicon.c"
}


static void
midori_favicon_load_icon (MidoriFavicon* self,
                          GCancellable* cancellable,
                          GAsyncReadyCallback _callback_,
                          gpointer _user_data_)
{
	MidoriFaviconLoadIconData* _data_;
	MidoriFavicon* _tmp0_;
	GCancellable* _tmp1_;
#line 13 "/home/test/core/core/favicon.vala"
	_data_ = g_slice_new0 (MidoriFaviconLoadIconData);
#line 13 "/home/test/core/core/favicon.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), cancellable, _callback_, _user_data_);
#line 13 "/home/test/core/core/favicon.vala"
	g_task_set_task_data (_data_->_async_result, _data_, midori_favicon_load_icon_data_free);
#line 13 "/home/test/core/core/favicon.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 13 "/home/test/core/core/favicon.vala"
	_data_->self = _tmp0_;
#line 13 "/home/test/core/core/favicon.vala"
	_tmp1_ = _g_object_ref0 (cancellable);
#line 13 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (_data_->cancellable);
#line 13 "/home/test/core/core/favicon.vala"
	_data_->cancellable = _tmp1_;
#line 13 "/home/test/core/core/favicon.vala"
	midori_favicon_load_icon_co (_data_);
#line 183 "favicon.c"
}


static void
midori_favicon_load_icon_finish (MidoriFavicon* self,
                                 GAsyncResult* _res_)
{
	MidoriFaviconLoadIconData* _data_;
#line 13 "/home/test/core/core/favicon.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 13 "/home/test/core/core/favicon.vala"
	if (NULL == _data_) {
#line 13 "/home/test/core/core/favicon.vala"
		return;
#line 198 "favicon.c"
	}
}


static void
___lambda23_ (MidoriFavicon* self,
              const gchar* page_uri,
              const gchar* favicon_uri)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
#line 37 "/home/test/core/core/favicon.vala"
	g_return_if_fail (page_uri != NULL);
#line 37 "/home/test/core/core/favicon.vala"
	g_return_if_fail (favicon_uri != NULL);
#line 38 "/home/test/core/core/favicon.vala"
	_tmp0_ = midori_favicon_get_uri (self);
#line 38 "/home/test/core/core/favicon.vala"
	_tmp1_ = _tmp0_;
#line 38 "/home/test/core/core/favicon.vala"
	if (g_strcmp0 (page_uri, _tmp1_) == 0) {
#line 39 "/home/test/core/core/favicon.vala"
		midori_favicon_load_icon (self, NULL, NULL, NULL);
#line 222 "favicon.c"
	}
}


static void
____lambda23__webkit_favicon_database_favicon_changed (WebKitFaviconDatabase* _sender,
                                                       const gchar* page_uri,
                                                       const gchar* favicon_uri,
                                                       gpointer self)
{
#line 37 "/home/test/core/core/favicon.vala"
	___lambda23_ ((MidoriFavicon*) self, page_uri, favicon_uri);
#line 235 "favicon.c"
}


static void
midori_favicon_load_icon_ready (GObject* source_object,
                                GAsyncResult* _res_,
                                gpointer _user_data_)
{
	MidoriFaviconLoadIconData* _data_;
#line 45 "/home/test/core/core/favicon.vala"
	_data_ = _user_data_;
#line 45 "/home/test/core/core/favicon.vala"
	_data_->_source_object_ = source_object;
#line 45 "/home/test/core/core/favicon.vala"
	_data_->_res_ = _res_;
#line 45 "/home/test/core/core/favicon.vala"
	midori_favicon_load_icon_co (_data_);
#line 253 "favicon.c"
}


static gboolean
midori_favicon_load_icon_co (MidoriFaviconLoadIconData* _data_)
{
#line 34 "/home/test/core/core/favicon.vala"
	switch (_data_->_state_) {
#line 34 "/home/test/core/core/favicon.vala"
		case 0:
#line 264 "favicon.c"
		goto _state_0;
#line 34 "/home/test/core/core/favicon.vala"
		case 1:
#line 268 "favicon.c"
		goto _state_1;
		default:
#line 34 "/home/test/core/core/favicon.vala"
		g_assert_not_reached ();
#line 273 "favicon.c"
	}
	_state_0:
#line 35 "/home/test/core/core/favicon.vala"
	_data_->_tmp0_ = _data_->self->priv->database;
#line 35 "/home/test/core/core/favicon.vala"
	if (_data_->_tmp0_ == NULL) {
#line 36 "/home/test/core/core/favicon.vala"
		_data_->_tmp1_ = webkit_web_context_get_default ();
#line 36 "/home/test/core/core/favicon.vala"
		_data_->_tmp2_ = webkit_web_context_get_favicon_database (_data_->_tmp1_);
#line 36 "/home/test/core/core/favicon.vala"
		_data_->_tmp3_ = _g_object_ref0 (_data_->_tmp2_);
#line 36 "/home/test/core/core/favicon.vala"
		_g_object_unref0 (_data_->self->priv->database);
#line 36 "/home/test/core/core/favicon.vala"
		_data_->self->priv->database = _data_->_tmp3_;
#line 37 "/home/test/core/core/favicon.vala"
		_data_->_tmp4_ = _data_->self->priv->database;
#line 37 "/home/test/core/core/favicon.vala"
		g_signal_connect_object (_data_->_tmp4_, "favicon-changed", (GCallback) ____lambda23__webkit_favicon_database_favicon_changed, _data_->self, 0);
#line 294 "favicon.c"
	}
	{
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_tmp6_ = _data_->self->priv->database;
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_tmp7_ = midori_favicon_get_uri (_data_->self);
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_tmp8_ = _data_->_tmp7_;
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_state_ = 1;
#line 45 "/home/test/core/core/favicon.vala"
		webkit_favicon_database_get_favicon (_data_->_tmp6_, _data_->_tmp8_, _data_->cancellable, midori_favicon_load_icon_ready, _data_);
#line 45 "/home/test/core/core/favicon.vala"
		return FALSE;
#line 309 "favicon.c"
		_state_1:
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_tmp9_ = webkit_favicon_database_get_favicon_finish (_data_->_tmp6_, _data_->_res_, &_data_->_inner_error0_);
#line 45 "/home/test/core/core/favicon.vala"
		_data_->_tmp5_ = _data_->_tmp9_;
#line 45 "/home/test/core/core/favicon.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 317 "favicon.c"
			goto __catch26_g_error;
		}
#line 45 "/home/test/core/core/favicon.vala"
		midori_favicon_set_surface (_data_->self, _data_->_tmp5_);
#line 44 "/home/test/core/core/favicon.vala"
		_cairo_surface_destroy0 (_data_->_tmp5_);
#line 324 "favicon.c"
	}
	goto __finally26;
	__catch26_g_error:
	{
#line 44 "/home/test/core/core/favicon.vala"
		_data_->_error_ = _data_->_inner_error0_;
#line 44 "/home/test/core/core/favicon.vala"
		_data_->_inner_error0_ = NULL;
#line 47 "/home/test/core/core/favicon.vala"
		_data_->_tmp10_ = _data_->_error_;
#line 47 "/home/test/core/core/favicon.vala"
		_data_->_tmp11_ = _data_->_tmp10_->message;
#line 47 "/home/test/core/core/favicon.vala"
		g_debug ("favicon.vala:47: Icon failed to load: %s", _data_->_tmp11_);
#line 44 "/home/test/core/core/favicon.vala"
		_g_error_free0 (_data_->_error_);
#line 341 "favicon.c"
	}
	__finally26:
#line 44 "/home/test/core/core/favicon.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 44 "/home/test/core/core/favicon.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 44 "/home/test/core/core/favicon.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 44 "/home/test/core/core/favicon.vala"
		g_object_unref (_data_->_async_result);
#line 44 "/home/test/core/core/favicon.vala"
		return FALSE;
#line 354 "favicon.c"
	}
#line 34 "/home/test/core/core/favicon.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 34 "/home/test/core/core/favicon.vala"
	if (_data_->_state_ != 0) {
#line 34 "/home/test/core/core/favicon.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 34 "/home/test/core/core/favicon.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 364 "favicon.c"
		}
	}
#line 34 "/home/test/core/core/favicon.vala"
	g_object_unref (_data_->_async_result);
#line 34 "/home/test/core/core/favicon.vala"
	return FALSE;
#line 371 "favicon.c"
}


static GdkPixbuf*
midori_favicon_scale_to_icon_size (MidoriFavicon* self,
                                   GdkPixbuf* pixbuf)
{
	GdkPixbuf* result = NULL;
	gint icon_width = 0;
	gint icon_height = 0;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	GdkPixbuf* _tmp12_;
#line 51 "/home/test/core/core/favicon.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 51 "/home/test/core/core/favicon.vala"
	g_return_val_if_fail (pixbuf != NULL, NULL);
#line 52 "/home/test/core/core/favicon.vala"
	icon_width = 16;
#line 52 "/home/test/core/core/favicon.vala"
	icon_height = 16;
#line 53 "/home/test/core/core/favicon.vala"
	g_object_get ((GtkImage*) self, "icon-size", &_tmp0_, NULL);
#line 53 "/home/test/core/core/favicon.vala"
	_tmp1_ = _tmp0_;
#line 53 "/home/test/core/core/favicon.vala"
	gtk_icon_size_lookup ((GtkIconSize) _tmp1_, &_tmp2_, &_tmp3_);
#line 53 "/home/test/core/core/favicon.vala"
	icon_width = _tmp2_;
#line 53 "/home/test/core/core/favicon.vala"
	icon_height = _tmp3_;
#line 55 "/home/test/core/core/favicon.vala"
	_tmp4_ = icon_width;
#line 55 "/home/test/core/core/favicon.vala"
	_tmp5_ = gtk_widget_get_scale_factor ((GtkWidget*) self);
#line 55 "/home/test/core/core/favicon.vala"
	_tmp6_ = _tmp5_;
#line 55 "/home/test/core/core/favicon.vala"
	icon_width = _tmp4_ * _tmp6_;
#line 56 "/home/test/core/core/favicon.vala"
	_tmp7_ = icon_height;
#line 56 "/home/test/core/core/favicon.vala"
	_tmp8_ = gtk_widget_get_scale_factor ((GtkWidget*) self);
#line 56 "/home/test/core/core/favicon.vala"
	_tmp9_ = _tmp8_;
#line 56 "/home/test/core/core/favicon.vala"
	icon_height = _tmp7_ * _tmp9_;
#line 57 "/home/test/core/core/favicon.vala"
	_tmp10_ = icon_width;
#line 57 "/home/test/core/core/favicon.vala"
	_tmp11_ = icon_height;
#line 57 "/home/test/core/core/favicon.vala"
	_tmp12_ = gdk_pixbuf_scale_simple (pixbuf, _tmp10_, _tmp11_, GDK_INTERP_BILINEAR);
#line 57 "/home/test/core/core/favicon.vala"
	result = _tmp12_;
#line 57 "/home/test/core/core/favicon.vala"
	return result;
#line 439 "favicon.c"
}


MidoriFavicon*
midori_favicon_construct (GType object_type)
{
	MidoriFavicon * self = NULL;
#line 13 "/home/test/core/core/favicon.vala"
	self = (MidoriFavicon*) g_object_new (object_type, NULL);
#line 13 "/home/test/core/core/favicon.vala"
	return self;
#line 451 "favicon.c"
}


MidoriFavicon*
midori_favicon_new (void)
{
#line 13 "/home/test/core/core/favicon.vala"
	return midori_favicon_construct (MIDORI_TYPE_FAVICON);
#line 460 "favicon.c"
}


static gpointer
_cairo_surface_reference0 (gpointer self)
{
#line 15 "/home/test/core/core/favicon.vala"
	return self ? cairo_surface_reference (self) : NULL;
#line 469 "favicon.c"
}


void
midori_favicon_set_surface (MidoriFavicon* self,
                            cairo_surface_t* value)
{
	cairo_surface_t* image = NULL;
	cairo_surface_t* _tmp0_;
	GdkPixbuf* _tmp1_ = NULL;
	cairo_surface_t* _tmp2_;
	GdkPixbuf* pixbuf = NULL;
	GdkPixbuf* _tmp7_;
	gint _icon_size = 0;
	gint _tmp8_;
	gint _tmp9_;
	GIcon* _tmp10_ = NULL;
	GdkPixbuf* _tmp11_;
	gint _tmp14_;
#line 14 "/home/test/core/core/favicon.vala"
	g_return_if_fail (self != NULL);
#line 15 "/home/test/core/core/favicon.vala"
	_tmp0_ = _cairo_surface_reference0 ((cairo_surface_t*) value);
#line 15 "/home/test/core/core/favicon.vala"
	image = _tmp0_;
#line 16 "/home/test/core/core/favicon.vala"
	_tmp2_ = image;
#line 16 "/home/test/core/core/favicon.vala"
	if (_tmp2_ != NULL) {
#line 499 "favicon.c"
		cairo_surface_t* _tmp3_;
		cairo_surface_t* _tmp4_;
		cairo_surface_t* _tmp5_;
		GdkPixbuf* _tmp6_;
#line 16 "/home/test/core/core/favicon.vala"
		_tmp3_ = image;
#line 16 "/home/test/core/core/favicon.vala"
		_tmp4_ = image;
#line 16 "/home/test/core/core/favicon.vala"
		_tmp5_ = image;
#line 16 "/home/test/core/core/favicon.vala"
		_tmp6_ = gdk_pixbuf_get_from_surface (_tmp3_, 0, 0, cairo_image_surface_get_width (_tmp4_), cairo_image_surface_get_height (_tmp5_));
#line 16 "/home/test/core/core/favicon.vala"
		_g_object_unref0 (_tmp1_);
#line 16 "/home/test/core/core/favicon.vala"
		_tmp1_ = _tmp6_;
#line 516 "favicon.c"
	} else {
#line 16 "/home/test/core/core/favicon.vala"
		_g_object_unref0 (_tmp1_);
#line 16 "/home/test/core/core/favicon.vala"
		_tmp1_ = NULL;
#line 522 "favicon.c"
	}
#line 16 "/home/test/core/core/favicon.vala"
	_tmp7_ = _g_object_ref0 (_tmp1_);
#line 16 "/home/test/core/core/favicon.vala"
	pixbuf = _tmp7_;
#line 17 "/home/test/core/core/favicon.vala"
	g_object_get ((GtkImage*) self, "icon-size", &_tmp8_, NULL);
#line 17 "/home/test/core/core/favicon.vala"
	_tmp9_ = _tmp8_;
#line 17 "/home/test/core/core/favicon.vala"
	_icon_size = _tmp9_;
#line 18 "/home/test/core/core/favicon.vala"
	_tmp11_ = pixbuf;
#line 18 "/home/test/core/core/favicon.vala"
	if (_tmp11_ != NULL) {
#line 538 "favicon.c"
		GdkPixbuf* _tmp12_;
		GdkPixbuf* _tmp13_;
#line 18 "/home/test/core/core/favicon.vala"
		_tmp12_ = pixbuf;
#line 18 "/home/test/core/core/favicon.vala"
		_tmp13_ = midori_favicon_scale_to_icon_size (self, _tmp12_);
#line 18 "/home/test/core/core/favicon.vala"
		_g_object_unref0 (_tmp10_);
#line 18 "/home/test/core/core/favicon.vala"
		_tmp10_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, g_icon_get_type (), GIcon);
#line 549 "favicon.c"
	} else {
#line 18 "/home/test/core/core/favicon.vala"
		_g_object_unref0 (_tmp10_);
#line 18 "/home/test/core/core/favicon.vala"
		_tmp10_ = NULL;
#line 555 "favicon.c"
	}
#line 18 "/home/test/core/core/favicon.vala"
	g_object_set ((GtkImage*) self, "gicon", _tmp10_, NULL);
#line 19 "/home/test/core/core/favicon.vala"
	_tmp14_ = _icon_size;
#line 19 "/home/test/core/core/favicon.vala"
	g_object_set ((GtkImage*) self, "icon-size", _tmp14_, NULL);
#line 14 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (_tmp10_);
#line 14 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (pixbuf);
#line 14 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (_tmp1_);
#line 14 "/home/test/core/core/favicon.vala"
	_cairo_surface_destroy0 (image);
#line 14 "/home/test/core/core/favicon.vala"
	g_object_notify_by_pspec ((GObject *) self, midori_favicon_properties[MIDORI_FAVICON_SURFACE_PROPERTY]);
#line 573 "favicon.c"
}


const gchar*
midori_favicon_get_uri (MidoriFavicon* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 23 "/home/test/core/core/favicon.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "/home/test/core/core/favicon.vala"
	_tmp0_ = self->priv->_uri;
#line 23 "/home/test/core/core/favicon.vala"
	result = _tmp0_;
#line 23 "/home/test/core/core/favicon.vala"
	return result;
#line 590 "favicon.c"
}


void
midori_favicon_set_uri (MidoriFavicon* self,
                        const gchar* value)
{
	gint _icon_size = 0;
	gint _tmp0_;
	gint _tmp1_;
	gchar* _tmp2_;
#line 23 "/home/test/core/core/favicon.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/test/core/core/favicon.vala"
	g_object_get ((GtkImage*) self, "icon-size", &_tmp0_, NULL);
#line 25 "/home/test/core/core/favicon.vala"
	_tmp1_ = _tmp0_;
#line 25 "/home/test/core/core/favicon.vala"
	_icon_size = _tmp1_;
#line 26 "/home/test/core/core/favicon.vala"
	g_object_set ((GtkImage*) self, "gicon", NULL, NULL);
#line 27 "/home/test/core/core/favicon.vala"
	g_object_set ((GtkImage*) self, "icon-size", _icon_size, NULL);
#line 29 "/home/test/core/core/favicon.vala"
	_tmp2_ = g_strdup (value);
#line 29 "/home/test/core/core/favicon.vala"
	_g_free0 (self->priv->_uri);
#line 29 "/home/test/core/core/favicon.vala"
	self->priv->_uri = _tmp2_;
#line 30 "/home/test/core/core/favicon.vala"
	midori_favicon_load_icon (self, NULL, NULL, NULL);
#line 23 "/home/test/core/core/favicon.vala"
	g_object_notify_by_pspec ((GObject *) self, midori_favicon_properties[MIDORI_FAVICON_URI_PROPERTY]);
#line 624 "favicon.c"
}


static void
midori_favicon_class_init (MidoriFaviconClass * klass)
{
#line 13 "/home/test/core/core/favicon.vala"
	midori_favicon_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/test/core/core/favicon.vala"
	g_type_class_add_private (klass, sizeof (MidoriFaviconPrivate));
#line 13 "/home/test/core/core/favicon.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_midori_favicon_get_property;
#line 13 "/home/test/core/core/favicon.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_midori_favicon_set_property;
#line 13 "/home/test/core/core/favicon.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_favicon_finalize;
#line 13 "/home/test/core/core/favicon.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_FAVICON_SURFACE_PROPERTY, midori_favicon_properties[MIDORI_FAVICON_SURFACE_PROPERTY] = g_param_spec_pointer ("surface", "surface", "surface", G_PARAM_STATIC_STRINGS | G_PARAM_WRITABLE));
#line 13 "/home/test/core/core/favicon.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_FAVICON_URI_PROPERTY, midori_favicon_properties[MIDORI_FAVICON_URI_PROPERTY] = g_param_spec_string ("uri", "uri", "uri", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 645 "favicon.c"
}


static void
midori_favicon_instance_init (MidoriFavicon * self)
{
#line 13 "/home/test/core/core/favicon.vala"
	self->priv = MIDORI_FAVICON_GET_PRIVATE (self);
#line 22 "/home/test/core/core/favicon.vala"
	self->priv->_uri = NULL;
#line 656 "favicon.c"
}


static void
midori_favicon_finalize (GObject * obj)
{
	MidoriFavicon * self;
#line 13 "/home/test/core/core/favicon.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_FAVICON, MidoriFavicon);
#line 22 "/home/test/core/core/favicon.vala"
	_g_free0 (self->priv->_uri);
#line 33 "/home/test/core/core/favicon.vala"
	_g_object_unref0 (self->priv->database);
#line 13 "/home/test/core/core/favicon.vala"
	G_OBJECT_CLASS (midori_favicon_parent_class)->finalize (obj);
#line 672 "favicon.c"
}


GType
midori_favicon_get_type (void)
{
	static volatile gsize midori_favicon_type_id__volatile = 0;
	if (g_once_init_enter (&midori_favicon_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriFaviconClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_favicon_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriFavicon), 0, (GInstanceInitFunc) midori_favicon_instance_init, NULL };
		GType midori_favicon_type_id;
		midori_favicon_type_id = g_type_register_static (gtk_image_get_type (), "MidoriFavicon", &g_define_type_info, 0);
		g_once_init_leave (&midori_favicon_type_id__volatile, midori_favicon_type_id);
	}
	return midori_favicon_type_id__volatile;
}


static void
_vala_midori_favicon_get_property (GObject * object,
                                   guint property_id,
                                   GValue * value,
                                   GParamSpec * pspec)
{
	MidoriFavicon * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_FAVICON, MidoriFavicon);
#line 13 "/home/test/core/core/favicon.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/favicon.vala"
		case MIDORI_FAVICON_URI_PROPERTY:
#line 13 "/home/test/core/core/favicon.vala"
		g_value_set_string (value, midori_favicon_get_uri (self));
#line 13 "/home/test/core/core/favicon.vala"
		break;
#line 706 "favicon.c"
		default:
#line 13 "/home/test/core/core/favicon.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/favicon.vala"
		break;
#line 712 "favicon.c"
	}
}


static void
_vala_midori_favicon_set_property (GObject * object,
                                   guint property_id,
                                   const GValue * value,
                                   GParamSpec * pspec)
{
	MidoriFavicon * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_FAVICON, MidoriFavicon);
#line 13 "/home/test/core/core/favicon.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/favicon.vala"
		case MIDORI_FAVICON_SURFACE_PROPERTY:
#line 13 "/home/test/core/core/favicon.vala"
		midori_favicon_set_surface (self, g_value_get_pointer (value));
#line 13 "/home/test/core/core/favicon.vala"
		break;
#line 13 "/home/test/core/core/favicon.vala"
		case MIDORI_FAVICON_URI_PROPERTY:
#line 13 "/home/test/core/core/favicon.vala"
		midori_favicon_set_uri (self, g_value_get_string (value));
#line 13 "/home/test/core/core/favicon.vala"
		break;
#line 739 "favicon.c"
		default:
#line 13 "/home/test/core/core/favicon.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/favicon.vala"
		break;
#line 745 "favicon.c"
	}
}



