/* main.c generated by valac 0.40.23, the Vala compiler
 * generated from main.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>


#define MIDORI_TYPE_APP (midori_app_get_type ())
#define MIDORI_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_APP, MidoriApp))
#define MIDORI_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_APP, MidoriAppClass))
#define MIDORI_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_APP))
#define MIDORI_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_APP))
#define MIDORI_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_APP, MidoriAppClass))

typedef struct _MidoriApp MidoriApp;
typedef struct _MidoriAppClass MidoriAppClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



gint _vala_main (gchar** args,
                 int args_length1);
GType midori_app_get_type (void) G_GNUC_CONST;
MidoriApp* midori_app_new (void);
MidoriApp* midori_app_construct (GType object_type);


gint
_vala_main (gchar** args,
            int args_length1)
{
	gint result = 0;
	MidoriApp* app = NULL;
	MidoriApp* _tmp0_;
#line 13 "/home/test/core/core/main.vala"
	_tmp0_ = midori_app_new ();
#line 13 "/home/test/core/core/main.vala"
	app = _tmp0_;
#line 14 "/home/test/core/core/main.vala"
	result = g_application_run ((GApplication*) app, args_length1, args);
#line 14 "/home/test/core/core/main.vala"
	_g_object_unref0 (app);
#line 14 "/home/test/core/core/main.vala"
	return result;
#line 62 "main.c"
}


int
main (int argc,
      char ** argv)
{
#line 12 "/home/test/core/core/main.vala"
	return _vala_main (argv, argc);
#line 72 "main.c"
}



