/* navigationbar.c generated by valac 0.40.23, the Vala compiler
 * generated from navigationbar.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define MIDORI_TYPE_NAVIGATIONBAR (midori_navigationbar_get_type ())
#define MIDORI_NAVIGATIONBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_NAVIGATIONBAR, MidoriNavigationbar))
#define MIDORI_NAVIGATIONBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_NAVIGATIONBAR, MidoriNavigationbarClass))
#define MIDORI_IS_NAVIGATIONBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_NAVIGATIONBAR))
#define MIDORI_IS_NAVIGATIONBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_NAVIGATIONBAR))
#define MIDORI_NAVIGATIONBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_NAVIGATIONBAR, MidoriNavigationbarClass))

typedef struct _MidoriNavigationbar MidoriNavigationbar;
typedef struct _MidoriNavigationbarClass MidoriNavigationbarClass;
typedef struct _MidoriNavigationbarPrivate MidoriNavigationbarPrivate;

#define MIDORI_TYPE_URLBAR (midori_urlbar_get_type ())
#define MIDORI_URLBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_URLBAR, MidoriUrlbar))
#define MIDORI_URLBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_URLBAR, MidoriUrlbarClass))
#define MIDORI_IS_URLBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_URLBAR))
#define MIDORI_IS_URLBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_URLBAR))
#define MIDORI_URLBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_URLBAR, MidoriUrlbarClass))

typedef struct _MidoriUrlbar MidoriUrlbar;
typedef struct _MidoriUrlbarClass MidoriUrlbarClass;
enum  {
	MIDORI_NAVIGATIONBAR_0_PROPERTY,
	MIDORI_NAVIGATIONBAR_NUM_PROPERTIES
};
static GParamSpec* midori_navigationbar_properties[MIDORI_NAVIGATIONBAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define MIDORI_TYPE_SETTINGS (midori_settings_get_type ())
#define MIDORI_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_SETTINGS, MidoriSettings))
#define MIDORI_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_SETTINGS, MidoriSettingsClass))
#define MIDORI_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_SETTINGS))
#define MIDORI_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_SETTINGS))
#define MIDORI_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_SETTINGS, MidoriSettingsClass))

typedef struct _MidoriSettings MidoriSettings;
typedef struct _MidoriSettingsClass MidoriSettingsClass;

#define MIDORI_TYPE_CORE_SETTINGS (midori_core_settings_get_type ())
#define MIDORI_CORE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettings))
#define MIDORI_CORE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettingsClass))
#define MIDORI_IS_CORE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_CORE_SETTINGS))
#define MIDORI_IS_CORE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_CORE_SETTINGS))
#define MIDORI_CORE_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettingsClass))

typedef struct _MidoriCoreSettings MidoriCoreSettings;
typedef struct _MidoriCoreSettingsClass MidoriCoreSettingsClass;

struct _MidoriNavigationbar {
	GtkActionBar parent_instance;
	MidoriNavigationbarPrivate * priv;
	GtkBox* actionbox;
	GtkButton* go_back;
	GtkButton* go_forward;
	GtkButton* reload;
	GtkButton* stop_loading;
	GtkButton* homepage;
	MidoriUrlbar* urlbar;
	GtkButton* restore;
};

struct _MidoriNavigationbarClass {
	GtkActionBarClass parent_class;
};


static gpointer midori_navigationbar_parent_class = NULL;

GType midori_navigationbar_get_type (void) G_GNUC_CONST;
GType midori_urlbar_get_type (void) G_GNUC_CONST;
MidoriNavigationbar* midori_navigationbar_new (void);
MidoriNavigationbar* midori_navigationbar_construct (GType object_type);
static GObject * midori_navigationbar_constructor (GType type,
                                            guint n_construct_properties,
                                            GObjectConstructParam * construct_properties);
GType midori_settings_get_type (void) G_GNUC_CONST;
GType midori_core_settings_get_type (void) G_GNUC_CONST;
MidoriCoreSettings* midori_core_settings_get_default (void);
gboolean midori_core_settings_get_homepage_in_toolbar (MidoriCoreSettings* self);
static void midori_navigationbar_finalize (GObject * obj);


MidoriNavigationbar*
midori_navigationbar_construct (GType object_type)
{
	MidoriNavigationbar * self = NULL;
#line 14 "/home/test/core/core/navigationbar.vala"
	self = (MidoriNavigationbar*) g_object_new (object_type, NULL);
#line 14 "/home/test/core/core/navigationbar.vala"
	return self;
#line 111 "navigationbar.c"
}


MidoriNavigationbar*
midori_navigationbar_new (void)
{
#line 14 "/home/test/core/core/navigationbar.vala"
	return midori_navigationbar_construct (MIDORI_TYPE_NAVIGATIONBAR);
#line 120 "navigationbar.c"
}


static GObject *
midori_navigationbar_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MidoriNavigationbar * self;
	MidoriCoreSettings* settings = NULL;
	MidoriCoreSettings* _tmp0_;
	GtkButton* _tmp1_;
	MidoriCoreSettings* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	MidoriCoreSettings* _tmp5_;
	GtkButton* _tmp6_;
#line 32 "/home/test/core/core/navigationbar.vala"
	parent_class = G_OBJECT_CLASS (midori_navigationbar_parent_class);
#line 32 "/home/test/core/core/navigationbar.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 32 "/home/test/core/core/navigationbar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_NAVIGATIONBAR, MidoriNavigationbar);
#line 33 "/home/test/core/core/navigationbar.vala"
	_tmp0_ = midori_core_settings_get_default ();
#line 33 "/home/test/core/core/navigationbar.vala"
	settings = _tmp0_;
#line 34 "/home/test/core/core/navigationbar.vala"
	_tmp1_ = self->homepage;
#line 34 "/home/test/core/core/navigationbar.vala"
	_tmp2_ = settings;
#line 34 "/home/test/core/core/navigationbar.vala"
	_tmp3_ = midori_core_settings_get_homepage_in_toolbar (_tmp2_);
#line 34 "/home/test/core/core/navigationbar.vala"
	_tmp4_ = _tmp3_;
#line 34 "/home/test/core/core/navigationbar.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp1_, _tmp4_);
#line 35 "/home/test/core/core/navigationbar.vala"
	_tmp5_ = settings;
#line 35 "/home/test/core/core/navigationbar.vala"
	_tmp6_ = self->homepage;
#line 35 "/home/test/core/core/navigationbar.vala"
	g_object_bind_property_with_closures ((GObject*) _tmp5_, "homepage-in-toolbar", (GObject*) _tmp6_, "visible", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
#line 32 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (settings);
#line 32 "/home/test/core/core/navigationbar.vala"
	return obj;
#line 170 "navigationbar.c"
}


static void
midori_navigationbar_class_init (MidoriNavigationbarClass * klass)
{
#line 14 "/home/test/core/core/navigationbar.vala"
	midori_navigationbar_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/test/core/core/navigationbar.vala"
	G_OBJECT_CLASS (klass)->constructor = midori_navigationbar_constructor;
#line 14 "/home/test/core/core/navigationbar.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_navigationbar_finalize;
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/ui/navigationbar.ui");
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "actionbox", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, actionbox));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "go_back", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, go_back));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "go_forward", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, go_forward));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "reload", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, reload));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stop_loading", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, stop_loading));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "homepage", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, homepage));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "urlbar", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, urlbar));
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "restore", FALSE, G_STRUCT_OFFSET (MidoriNavigationbar, restore));
#line 201 "navigationbar.c"
}


static void
midori_navigationbar_instance_init (MidoriNavigationbar * self)
{
#line 14 "/home/test/core/core/navigationbar.vala"
	g_type_ensure (MIDORI_TYPE_URLBAR);
#line 14 "/home/test/core/core/navigationbar.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 212 "navigationbar.c"
}


static void
midori_navigationbar_finalize (GObject * obj)
{
	MidoriNavigationbar * self;
#line 14 "/home/test/core/core/navigationbar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_NAVIGATIONBAR, MidoriNavigationbar);
#line 16 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->actionbox);
#line 18 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->go_back);
#line 20 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->go_forward);
#line 22 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->reload);
#line 24 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->stop_loading);
#line 26 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->homepage);
#line 28 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->urlbar);
#line 30 "/home/test/core/core/navigationbar.vala"
	_g_object_unref0 (self->restore);
#line 14 "/home/test/core/core/navigationbar.vala"
	G_OBJECT_CLASS (midori_navigationbar_parent_class)->finalize (obj);
#line 240 "navigationbar.c"
}


GType
midori_navigationbar_get_type (void)
{
	static volatile gsize midori_navigationbar_type_id__volatile = 0;
	if (g_once_init_enter (&midori_navigationbar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriNavigationbarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_navigationbar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriNavigationbar), 0, (GInstanceInitFunc) midori_navigationbar_instance_init, NULL };
		GType midori_navigationbar_type_id;
		midori_navigationbar_type_id = g_type_register_static (gtk_action_bar_get_type (), "MidoriNavigationbar", &g_define_type_info, 0);
		g_once_init_leave (&midori_navigationbar_type_id__volatile, midori_navigationbar_type_id);
	}
	return midori_navigationbar_type_id__volatile;
}



