/* network-check.c generated by valac 0.40.23, the Vala compiler
 * generated from network-check.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "webkit2/webkit2.h"
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define MIDORI_TYPE_NETWORK_CHECK (midori_network_check_get_type ())
#define MIDORI_NETWORK_CHECK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheck))
#define MIDORI_NETWORK_CHECK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheckClass))
#define MIDORI_IS_NETWORK_CHECK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_NETWORK_CHECK))
#define MIDORI_IS_NETWORK_CHECK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_NETWORK_CHECK))
#define MIDORI_NETWORK_CHECK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheckClass))

typedef struct _MidoriNetworkCheck MidoriNetworkCheck;
typedef struct _MidoriNetworkCheckClass MidoriNetworkCheckClass;
typedef struct _MidoriNetworkCheckPrivate MidoriNetworkCheckPrivate;
enum  {
	MIDORI_NETWORK_CHECK_0_PROPERTY,
	MIDORI_NETWORK_CHECK_NUM_PROPERTIES
};
static GParamSpec* midori_network_check_properties[MIDORI_NETWORK_CHECK_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define MIDORI_TYPE_BROWSER (midori_browser_get_type ())
#define MIDORI_BROWSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_BROWSER, MidoriBrowser))
#define MIDORI_BROWSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_BROWSER, MidoriBrowserClass))
#define MIDORI_IS_BROWSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_BROWSER))
#define MIDORI_IS_BROWSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_BROWSER))
#define MIDORI_BROWSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_BROWSER, MidoriBrowserClass))

typedef struct _MidoriBrowser MidoriBrowser;
typedef struct _MidoriBrowserClass MidoriBrowserClass;

#define MIDORI_TYPE_TAB (midori_tab_get_type ())
#define MIDORI_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_TAB, MidoriTab))
#define MIDORI_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_TAB, MidoriTabClass))
#define MIDORI_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_TAB))
#define MIDORI_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_TAB))
#define MIDORI_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_TAB, MidoriTabClass))

typedef struct _MidoriTab MidoriTab;
typedef struct _MidoriTabClass MidoriTabClass;
typedef struct _Block12Data Block12Data;

struct _MidoriNetworkCheck {
	GtkActionBar parent_instance;
	MidoriNetworkCheckPrivate * priv;
};

struct _MidoriNetworkCheckClass {
	GtkActionBarClass parent_class;
};

struct _MidoriNetworkCheckPrivate {
	GtkButton* login;
};

struct _Block12Data {
	int _ref_count_;
	MidoriNetworkCheck* self;
	GNetworkMonitor* monitor;
};


static gpointer midori_network_check_parent_class = NULL;

GType midori_network_check_get_type (void) G_GNUC_CONST;
#define MIDORI_NETWORK_CHECK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheckPrivate))
static void midori_network_check_login_clicked (MidoriNetworkCheck* self);
GType midori_browser_get_type (void) G_GNUC_CONST;
GType midori_tab_get_type (void) G_GNUC_CONST;
void midori_browser_add (MidoriBrowser* self,
                         MidoriTab* tab);
WebKitWebContext* midori_browser_get_web_context (MidoriBrowser* self);
MidoriTab* midori_tab_new (MidoriTab* related,
                           WebKitWebContext* web_context,
                           const gchar* uri,
                           const gchar* title);
MidoriTab* midori_tab_construct (GType object_type,
                                 MidoriTab* related,
                                 WebKitWebContext* web_context,
                                 const gchar* uri,
                                 const gchar* title);
MidoriNetworkCheck* midori_network_check_new (void);
MidoriNetworkCheck* midori_network_check_construct (GType object_type);
static GObject * midori_network_check_constructor (GType type,
                                            guint n_construct_properties,
                                            GObjectConstructParam * construct_properties);
static Block12Data* block12_data_ref (Block12Data* _data12_);
static void block12_data_unref (void * _userdata_);
static void _midori_network_check_login_clicked_gtk_button_clicked (GtkButton* _sender,
                                                             gpointer self);
static void _midori_network_check___lambda105_ (Block12Data* _data12_,
                                         GParamSpec* pspec);
static void __midori_network_check___lambda105__g_object_notify (GObject* _sender,
                                                          GParamSpec* pspec,
                                                          gpointer self);
static void midori_network_check_finalize (GObject * obj);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 30 "/home/test/core/core/network-check.vala"
	return self ? g_object_ref (self) : NULL;
#line 125 "network-check.c"
}


static void
midori_network_check_login_clicked (MidoriNetworkCheck* self)
{
	MidoriBrowser* browser = NULL;
	GtkWidget* _tmp0_;
	MidoriBrowser* _tmp1_;
	WebKitWebContext* _tmp2_;
	WebKitWebContext* _tmp3_;
	MidoriTab* _tmp4_;
	MidoriTab* _tmp5_;
#line 29 "/home/test/core/core/network-check.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/test/core/core/network-check.vala"
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
#line 30 "/home/test/core/core/network-check.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, MIDORI_TYPE_BROWSER, MidoriBrowser));
#line 30 "/home/test/core/core/network-check.vala"
	browser = _tmp1_;
#line 31 "/home/test/core/core/network-check.vala"
	_tmp2_ = midori_browser_get_web_context (browser);
#line 31 "/home/test/core/core/network-check.vala"
	_tmp3_ = _tmp2_;
#line 31 "/home/test/core/core/network-check.vala"
	_tmp4_ = midori_tab_new (NULL, _tmp3_, "http://example.com", NULL);
#line 31 "/home/test/core/core/network-check.vala"
	g_object_ref_sink (_tmp4_);
#line 31 "/home/test/core/core/network-check.vala"
	_tmp5_ = _tmp4_;
#line 31 "/home/test/core/core/network-check.vala"
	midori_browser_add (browser, _tmp5_);
#line 31 "/home/test/core/core/network-check.vala"
	_g_object_unref0 (_tmp5_);
#line 29 "/home/test/core/core/network-check.vala"
	_g_object_unref0 (browser);
#line 163 "network-check.c"
}


MidoriNetworkCheck*
midori_network_check_construct (GType object_type)
{
	MidoriNetworkCheck * self = NULL;
#line 14 "/home/test/core/core/network-check.vala"
	self = (MidoriNetworkCheck*) g_object_new (object_type, NULL);
#line 14 "/home/test/core/core/network-check.vala"
	return self;
#line 175 "network-check.c"
}


MidoriNetworkCheck*
midori_network_check_new (void)
{
#line 14 "/home/test/core/core/network-check.vala"
	return midori_network_check_construct (MIDORI_TYPE_NETWORK_CHECK);
#line 184 "network-check.c"
}


static Block12Data*
block12_data_ref (Block12Data* _data12_)
{
#line 18 "/home/test/core/core/network-check.vala"
	g_atomic_int_inc (&_data12_->_ref_count_);
#line 18 "/home/test/core/core/network-check.vala"
	return _data12_;
#line 195 "network-check.c"
}


static void
block12_data_unref (void * _userdata_)
{
	Block12Data* _data12_;
	_data12_ = (Block12Data*) _userdata_;
#line 18 "/home/test/core/core/network-check.vala"
	if (g_atomic_int_dec_and_test (&_data12_->_ref_count_)) {
#line 206 "network-check.c"
		MidoriNetworkCheck* self;
#line 18 "/home/test/core/core/network-check.vala"
		self = _data12_->self;
#line 18 "/home/test/core/core/network-check.vala"
		_g_object_unref0 (_data12_->monitor);
#line 18 "/home/test/core/core/network-check.vala"
		_g_object_unref0 (self);
#line 18 "/home/test/core/core/network-check.vala"
		g_slice_free (Block12Data, _data12_);
#line 216 "network-check.c"
	}
}


static void
_midori_network_check_login_clicked_gtk_button_clicked (GtkButton* _sender,
                                                        gpointer self)
{
#line 19 "/home/test/core/core/network-check.vala"
	midori_network_check_login_clicked ((MidoriNetworkCheck*) self);
#line 227 "network-check.c"
}


static void
_midori_network_check___lambda105_ (Block12Data* _data12_,
                                    GParamSpec* pspec)
{
	MidoriNetworkCheck* self;
	GNetworkMonitor* _tmp0_;
	GNetworkConnectivity _tmp1_;
	GNetworkConnectivity _tmp2_;
#line 23 "/home/test/core/core/network-check.vala"
	self = _data12_->self;
#line 23 "/home/test/core/core/network-check.vala"
	g_return_if_fail (pspec != NULL);
#line 24 "/home/test/core/core/network-check.vala"
	_tmp0_ = _data12_->monitor;
#line 24 "/home/test/core/core/network-check.vala"
	_tmp1_ = g_network_monitor_get_connectivity (_tmp0_);
#line 24 "/home/test/core/core/network-check.vala"
	_tmp2_ = _tmp1_;
#line 24 "/home/test/core/core/network-check.vala"
	gtk_widget_set_visible ((GtkWidget*) self, _tmp2_ == G_NETWORK_CONNECTIVITY_PORTAL);
#line 251 "network-check.c"
}


static void
__midori_network_check___lambda105__g_object_notify (GObject* _sender,
                                                     GParamSpec* pspec,
                                                     gpointer self)
{
#line 23 "/home/test/core/core/network-check.vala"
	_midori_network_check___lambda105_ (self, pspec);
#line 262 "network-check.c"
}


static GObject *
midori_network_check_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MidoriNetworkCheck * self;
	Block12Data* _data12_;
	GtkButton* _tmp0_;
	GNetworkMonitor* _tmp1_;
	GNetworkMonitor* _tmp2_;
	GNetworkMonitor* _tmp3_;
	GNetworkConnectivity _tmp4_;
	GNetworkConnectivity _tmp5_;
	GNetworkMonitor* _tmp6_;
#line 18 "/home/test/core/core/network-check.vala"
	parent_class = G_OBJECT_CLASS (midori_network_check_parent_class);
#line 18 "/home/test/core/core/network-check.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 18 "/home/test/core/core/network-check.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheck);
#line 18 "/home/test/core/core/network-check.vala"
	_data12_ = g_slice_new0 (Block12Data);
#line 18 "/home/test/core/core/network-check.vala"
	_data12_->_ref_count_ = 1;
#line 18 "/home/test/core/core/network-check.vala"
	_data12_->self = g_object_ref (self);
#line 19 "/home/test/core/core/network-check.vala"
	_tmp0_ = self->priv->login;
#line 19 "/home/test/core/core/network-check.vala"
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) _midori_network_check_login_clicked_gtk_button_clicked, self, 0);
#line 21 "/home/test/core/core/network-check.vala"
	_tmp1_ = g_network_monitor_get_default ();
#line 21 "/home/test/core/core/network-check.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 21 "/home/test/core/core/network-check.vala"
	_data12_->monitor = _tmp2_;
#line 22 "/home/test/core/core/network-check.vala"
	_tmp3_ = _data12_->monitor;
#line 22 "/home/test/core/core/network-check.vala"
	_tmp4_ = g_network_monitor_get_connectivity (_tmp3_);
#line 22 "/home/test/core/core/network-check.vala"
	_tmp5_ = _tmp4_;
#line 22 "/home/test/core/core/network-check.vala"
	gtk_widget_set_visible ((GtkWidget*) self, _tmp5_ == G_NETWORK_CONNECTIVITY_PORTAL);
#line 23 "/home/test/core/core/network-check.vala"
	_tmp6_ = _data12_->monitor;
#line 23 "/home/test/core/core/network-check.vala"
	g_signal_connect_data ((GObject*) _tmp6_, "notify::connectivity", (GCallback) __midori_network_check___lambda105__g_object_notify, block12_data_ref (_data12_), (GClosureNotify) block12_data_unref, 0);
#line 18 "/home/test/core/core/network-check.vala"
	return obj;
#line 318 "network-check.c"
}


static void
midori_network_check_class_init (MidoriNetworkCheckClass * klass)
{
	gint MidoriNetworkCheck_private_offset;
#line 14 "/home/test/core/core/network-check.vala"
	midori_network_check_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/test/core/core/network-check.vala"
	g_type_class_add_private (klass, sizeof (MidoriNetworkCheckPrivate));
#line 14 "/home/test/core/core/network-check.vala"
	G_OBJECT_CLASS (klass)->constructor = midori_network_check_constructor;
#line 14 "/home/test/core/core/network-check.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_network_check_finalize;
#line 14 "/home/test/core/core/network-check.vala"
	MidoriNetworkCheck_private_offset = g_type_class_get_instance_private_offset (klass);
#line 14 "/home/test/core/core/network-check.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/ui/network-check.ui");
#line 14 "/home/test/core/core/network-check.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "login", FALSE, MidoriNetworkCheck_private_offset + G_STRUCT_OFFSET (MidoriNetworkCheckPrivate, login));
#line 340 "network-check.c"
}


static void
midori_network_check_instance_init (MidoriNetworkCheck * self)
{
#line 14 "/home/test/core/core/network-check.vala"
	self->priv = MIDORI_NETWORK_CHECK_GET_PRIVATE (self);
#line 14 "/home/test/core/core/network-check.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 351 "network-check.c"
}


static void
midori_network_check_finalize (GObject * obj)
{
	MidoriNetworkCheck * self;
#line 14 "/home/test/core/core/network-check.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_NETWORK_CHECK, MidoriNetworkCheck);
#line 16 "/home/test/core/core/network-check.vala"
	_g_object_unref0 (self->priv->login);
#line 14 "/home/test/core/core/network-check.vala"
	G_OBJECT_CLASS (midori_network_check_parent_class)->finalize (obj);
#line 365 "network-check.c"
}


GType
midori_network_check_get_type (void)
{
	static volatile gsize midori_network_check_type_id__volatile = 0;
	if (g_once_init_enter (&midori_network_check_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriNetworkCheckClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_network_check_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriNetworkCheck), 0, (GInstanceInitFunc) midori_network_check_instance_init, NULL };
		GType midori_network_check_type_id;
		midori_network_check_type_id = g_type_register_static (gtk_action_bar_get_type (), "MidoriNetworkCheck", &g_define_type_info, 0);
		g_once_init_leave (&midori_network_check_type_id__volatile, midori_network_check_type_id);
	}
	return midori_network_check_type_id__volatile;
}



