/* switcher.c generated by valac 0.40.23, the Vala compiler
 * generated from switcher.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include "webkit2/webkit2.h"


#define MIDORI_TYPE_SWITCHER (midori_switcher_get_type ())
#define MIDORI_SWITCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_SWITCHER, MidoriSwitcher))
#define MIDORI_SWITCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_SWITCHER, MidoriSwitcherClass))
#define MIDORI_IS_SWITCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_SWITCHER))
#define MIDORI_IS_SWITCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_SWITCHER))
#define MIDORI_SWITCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_SWITCHER, MidoriSwitcherClass))

typedef struct _MidoriSwitcher MidoriSwitcher;
typedef struct _MidoriSwitcherClass MidoriSwitcherClass;
typedef struct _MidoriSwitcherPrivate MidoriSwitcherPrivate;

#define MIDORI_TYPE_TALLY (midori_tally_get_type ())
#define MIDORI_TALLY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_TALLY, MidoriTally))
#define MIDORI_TALLY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_TALLY, MidoriTallyClass))
#define MIDORI_IS_TALLY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_TALLY))
#define MIDORI_IS_TALLY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_TALLY))
#define MIDORI_TALLY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_TALLY, MidoriTallyClass))

typedef struct _MidoriTally MidoriTally;
typedef struct _MidoriTallyClass MidoriTallyClass;
enum  {
	MIDORI_SWITCHER_0_PROPERTY,
	MIDORI_SWITCHER_STACK_PROPERTY,
	MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY,
	MIDORI_SWITCHER_NUM_PROPERTIES
};
static GParamSpec* midori_switcher_properties[MIDORI_SWITCHER_NUM_PROPERTIES];
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block16Data Block16Data;
typedef struct _Block17Data Block17Data;

#define MIDORI_TYPE_TAB (midori_tab_get_type ())
#define MIDORI_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_TAB, MidoriTab))
#define MIDORI_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_TAB, MidoriTabClass))
#define MIDORI_IS_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_TAB))
#define MIDORI_IS_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_TAB))
#define MIDORI_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_TAB, MidoriTabClass))

typedef struct _MidoriTab MidoriTab;
typedef struct _MidoriTabClass MidoriTabClass;

struct _MidoriSwitcher {
	GtkBox parent_instance;
	MidoriSwitcherPrivate * priv;
};

struct _MidoriSwitcherClass {
	GtkBoxClass parent_class;
};

struct _MidoriSwitcherPrivate {
	GHashTable* buttons;
	GtkStack* _stack;
	gboolean _show_close_buttons;
};

struct _Block16Data {
	int _ref_count_;
	MidoriSwitcher* self;
	GtkScrolledWindow* scrolled;
	MidoriTally* button;
};

struct _Block17Data {
	int _ref_count_;
	MidoriSwitcher* self;
	GtkWidget* widget;
};


static gpointer midori_switcher_parent_class = NULL;

GType midori_switcher_get_type (void) G_GNUC_CONST;
GType midori_tally_get_type (void) G_GNUC_CONST;
#define MIDORI_SWITCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_SWITCHER, MidoriSwitcherPrivate))
static void midori_switcher_visible_child_changed (MidoriSwitcher* self,
                                            GParamSpec* pspec);
GtkStack* midori_switcher_get_stack (MidoriSwitcher* self);
void midori_tally_set_active (MidoriTally* self,
                              gboolean value);
gboolean midori_tally_get_active (MidoriTally* self);
static void midori_switcher_ensure_child_visible (MidoriSwitcher* self,
                                           MidoriTally* button);
static Block16Data* block16_data_ref (Block16Data* _data16_);
static void block16_data_unref (void * _userdata_);
static gboolean ___lambda118_ (Block16Data* _data16_);
static gboolean ____lambda118__gsource_func (gpointer self);
MidoriSwitcher* midori_switcher_new (void);
MidoriSwitcher* midori_switcher_construct (GType object_type);
void midori_switcher_set_stack (MidoriSwitcher* self,
                                GtkStack* value);
gboolean midori_switcher_get_show_close_buttons (MidoriSwitcher* self);
void midori_switcher_set_show_close_buttons (MidoriSwitcher* self,
                                             gboolean value);
static GObject * midori_switcher_constructor (GType type,
                                       guint n_construct_properties,
                                       GObjectConstructParam * construct_properties);
static void _g_object_unref0_ (gpointer var);
static void _midori_switcher___lambda119_ (MidoriSwitcher* self,
                                    GParamSpec* pspec);
static void __lambda120_ (MidoriSwitcher* self,
                   GtkWidget* widget);
static Block17Data* block17_data_ref (Block17Data* _data17_);
static void block17_data_unref (void * _userdata_);
GType midori_tab_get_type (void) G_GNUC_CONST;
MidoriTally* midori_tally_new (MidoriTab* tab);
MidoriTally* midori_tally_construct (GType object_type,
                                     MidoriTab* tab);
static void ___lambda121_ (Block17Data* _data17_);
static void ____lambda121__midori_tally_clicked (MidoriTally* _sender,
                                          gpointer self);
void midori_tally_set_show_close (MidoriTally* self,
                                  gboolean value);
static void ___lambda120__gtk_container_add (GtkContainer* _sender,
                                      GtkWidget* widget,
                                      gpointer self);
static void _midori_switcher_visible_child_changed_g_object_notify (GObject* _sender,
                                                             GParamSpec* pspec,
                                                             gpointer self);
static void __lambda122_ (MidoriSwitcher* self,
                   GtkWidget* widget);
static void ___lambda122__gtk_container_remove (GtkContainer* _sender,
                                         GtkWidget* widget,
                                         gpointer self);
static void __midori_switcher___lambda119__g_object_notify (GObject* _sender,
                                                     GParamSpec* pspec,
                                                     gpointer self);
static void midori_switcher_finalize (GObject * obj);
static void _vala_midori_switcher_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec);
static void _vala_midori_switcher_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 44 "/home/test/core/core/switcher.vala"
	return self ? g_object_ref (self) : NULL;
#line 170 "switcher.c"
}


static void
midori_switcher_visible_child_changed (MidoriSwitcher* self,
                                       GParamSpec* pspec)
{
	MidoriTally* button = NULL;
	GHashTable* _tmp0_;
	GtkStack* _tmp1_;
	GtkWidget* _tmp2_;
	GtkWidget* _tmp3_;
	gconstpointer _tmp4_;
	MidoriTally* _tmp5_;
	MidoriTally* _tmp6_;
#line 43 "/home/test/core/core/switcher.vala"
	g_return_if_fail (self != NULL);
#line 43 "/home/test/core/core/switcher.vala"
	g_return_if_fail (pspec != NULL);
#line 44 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 44 "/home/test/core/core/switcher.vala"
	_tmp1_ = self->priv->_stack;
#line 44 "/home/test/core/core/switcher.vala"
	_tmp2_ = gtk_stack_get_visible_child (_tmp1_);
#line 44 "/home/test/core/core/switcher.vala"
	_tmp3_ = _tmp2_;
#line 44 "/home/test/core/core/switcher.vala"
	_tmp4_ = g_hash_table_lookup (_tmp0_, _tmp3_);
#line 44 "/home/test/core/core/switcher.vala"
	_tmp5_ = _g_object_ref0 ((MidoriTally*) _tmp4_);
#line 44 "/home/test/core/core/switcher.vala"
	button = _tmp5_;
#line 45 "/home/test/core/core/switcher.vala"
	_tmp6_ = button;
#line 45 "/home/test/core/core/switcher.vala"
	if (_tmp6_ != NULL) {
#line 208 "switcher.c"
		GList* _tmp7_;
#line 46 "/home/test/core/core/switcher.vala"
		_tmp7_ = gtk_container_get_children ((GtkContainer*) self);
#line 212 "switcher.c"
		{
			GList* b_collection = NULL;
			GList* b_it = NULL;
#line 46 "/home/test/core/core/switcher.vala"
			b_collection = _tmp7_;
#line 46 "/home/test/core/core/switcher.vala"
			for (b_it = b_collection; b_it != NULL; b_it = b_it->next) {
#line 220 "switcher.c"
				GtkWidget* b = NULL;
#line 46 "/home/test/core/core/switcher.vala"
				b = (GtkWidget*) b_it->data;
#line 224 "switcher.c"
				{
					GtkWidget* _tmp8_;
					GtkWidget* _tmp9_;
					MidoriTally* _tmp10_;
					MidoriTally* _tmp11_;
					gboolean _tmp12_;
					gboolean _tmp13_;
#line 47 "/home/test/core/core/switcher.vala"
					_tmp8_ = b;
#line 47 "/home/test/core/core/switcher.vala"
					_tmp9_ = b;
#line 47 "/home/test/core/core/switcher.vala"
					_tmp10_ = button;
#line 47 "/home/test/core/core/switcher.vala"
					midori_tally_set_active (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, MIDORI_TYPE_TALLY, MidoriTally), _tmp9_ == G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, gtk_widget_get_type (), GtkWidget));
#line 48 "/home/test/core/core/switcher.vala"
					_tmp11_ = button;
#line 48 "/home/test/core/core/switcher.vala"
					_tmp12_ = midori_tally_get_active (_tmp11_);
#line 48 "/home/test/core/core/switcher.vala"
					_tmp13_ = _tmp12_;
#line 48 "/home/test/core/core/switcher.vala"
					if (_tmp13_) {
#line 248 "switcher.c"
						MidoriTally* _tmp14_;
#line 49 "/home/test/core/core/switcher.vala"
						_tmp14_ = button;
#line 49 "/home/test/core/core/switcher.vala"
						midori_switcher_ensure_child_visible (self, _tmp14_);
#line 254 "switcher.c"
					}
				}
			}
#line 46 "/home/test/core/core/switcher.vala"
			(b_collection == NULL) ? NULL : (b_collection = (g_list_free (b_collection), NULL));
#line 260 "switcher.c"
		}
	}
#line 43 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (button);
#line 265 "switcher.c"
}


static Block16Data*
block16_data_ref (Block16Data* _data16_)
{
#line 55 "/home/test/core/core/switcher.vala"
	g_atomic_int_inc (&_data16_->_ref_count_);
#line 55 "/home/test/core/core/switcher.vala"
	return _data16_;
#line 276 "switcher.c"
}


static void
block16_data_unref (void * _userdata_)
{
	Block16Data* _data16_;
	_data16_ = (Block16Data*) _userdata_;
#line 55 "/home/test/core/core/switcher.vala"
	if (g_atomic_int_dec_and_test (&_data16_->_ref_count_)) {
#line 287 "switcher.c"
		MidoriSwitcher* self;
#line 55 "/home/test/core/core/switcher.vala"
		self = _data16_->self;
#line 55 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (_data16_->scrolled);
#line 55 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (_data16_->button);
#line 55 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (self);
#line 55 "/home/test/core/core/switcher.vala"
		g_slice_free (Block16Data, _data16_);
#line 299 "switcher.c"
	}
}


static gboolean
___lambda118_ (Block16Data* _data16_)
{
	MidoriSwitcher* self;
	gboolean result = FALSE;
	GtkAdjustment* adjustment = NULL;
	GtkScrolledWindow* _tmp0_;
	GtkAdjustment* _tmp1_;
	GtkAdjustment* _tmp2_;
	GtkAdjustment* _tmp3_;
	GtkAllocation alloc = {0};
	GtkAllocation _tmp4_ = {0};
	GtkAllocation _tmp5_;
	gint _tmp6_;
	GtkAllocation _tmp7_;
	gint _tmp8_;
	GtkAllocation _tmp9_;
	gint _tmp10_;
#line 60 "/home/test/core/core/switcher.vala"
	self = _data16_->self;
#line 61 "/home/test/core/core/switcher.vala"
	_tmp0_ = _data16_->scrolled;
#line 61 "/home/test/core/core/switcher.vala"
	_tmp1_ = gtk_scrolled_window_get_hadjustment (_tmp0_);
#line 61 "/home/test/core/core/switcher.vala"
	_tmp2_ = _tmp1_;
#line 61 "/home/test/core/core/switcher.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 61 "/home/test/core/core/switcher.vala"
	adjustment = _tmp3_;
#line 63 "/home/test/core/core/switcher.vala"
	gtk_widget_get_allocation ((GtkWidget*) _data16_->button, &_tmp4_);
#line 63 "/home/test/core/core/switcher.vala"
	alloc = _tmp4_;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp5_ = alloc;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp6_ = _tmp5_.x;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp7_ = alloc;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp8_ = _tmp7_.x;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp9_ = alloc;
#line 64 "/home/test/core/core/switcher.vala"
	_tmp10_ = _tmp9_.width;
#line 64 "/home/test/core/core/switcher.vala"
	gtk_adjustment_clamp_page (adjustment, (gdouble) _tmp6_, (gdouble) (_tmp8_ + _tmp10_));
#line 65 "/home/test/core/core/switcher.vala"
	result = G_SOURCE_REMOVE;
#line 65 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (adjustment);
#line 65 "/home/test/core/core/switcher.vala"
	return result;
#line 358 "switcher.c"
}


static gboolean
____lambda118__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda118_ (self);
#line 60 "/home/test/core/core/switcher.vala"
	return result;
#line 369 "switcher.c"
}


static void
midori_switcher_ensure_child_visible (MidoriSwitcher* self,
                                      MidoriTally* button)
{
	Block16Data* _data16_;
	MidoriTally* _tmp0_;
	GtkWidget* _tmp1_;
	GtkScrolledWindow* _tmp2_;
	GtkScrolledWindow* _tmp3_;
#line 55 "/home/test/core/core/switcher.vala"
	g_return_if_fail (self != NULL);
#line 55 "/home/test/core/core/switcher.vala"
	g_return_if_fail (button != NULL);
#line 55 "/home/test/core/core/switcher.vala"
	_data16_ = g_slice_new0 (Block16Data);
#line 55 "/home/test/core/core/switcher.vala"
	_data16_->_ref_count_ = 1;
#line 55 "/home/test/core/core/switcher.vala"
	_data16_->self = g_object_ref (self);
#line 55 "/home/test/core/core/switcher.vala"
	_tmp0_ = _g_object_ref0 (button);
#line 55 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (_data16_->button);
#line 55 "/home/test/core/core/switcher.vala"
	_data16_->button = _tmp0_;
#line 57 "/home/test/core/core/switcher.vala"
	_tmp1_ = gtk_widget_get_ancestor ((GtkWidget*) self, gtk_scrolled_window_get_type ());
#line 57 "/home/test/core/core/switcher.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_scrolled_window_get_type (), GtkScrolledWindow));
#line 57 "/home/test/core/core/switcher.vala"
	_data16_->scrolled = _tmp2_;
#line 58 "/home/test/core/core/switcher.vala"
	_tmp3_ = _data16_->scrolled;
#line 58 "/home/test/core/core/switcher.vala"
	if (_tmp3_ != NULL) {
#line 60 "/home/test/core/core/switcher.vala"
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda118__gsource_func, block16_data_ref (_data16_), block16_data_unref);
#line 410 "switcher.c"
	}
#line 55 "/home/test/core/core/switcher.vala"
	block16_data_unref (_data16_);
#line 55 "/home/test/core/core/switcher.vala"
	_data16_ = NULL;
#line 416 "switcher.c"
}


MidoriSwitcher*
midori_switcher_construct (GType object_type)
{
	MidoriSwitcher * self = NULL;
#line 13 "/home/test/core/core/switcher.vala"
	self = (MidoriSwitcher*) g_object_new (object_type, NULL);
#line 13 "/home/test/core/core/switcher.vala"
	return self;
#line 428 "switcher.c"
}


MidoriSwitcher*
midori_switcher_new (void)
{
#line 13 "/home/test/core/core/switcher.vala"
	return midori_switcher_construct (MIDORI_TYPE_SWITCHER);
#line 437 "switcher.c"
}


GtkStack*
midori_switcher_get_stack (MidoriSwitcher* self)
{
	GtkStack* result;
	GtkStack* _tmp0_;
#line 15 "/home/test/core/core/switcher.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 15 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->_stack;
#line 15 "/home/test/core/core/switcher.vala"
	result = _tmp0_;
#line 15 "/home/test/core/core/switcher.vala"
	return result;
#line 454 "switcher.c"
}


void
midori_switcher_set_stack (MidoriSwitcher* self,
                           GtkStack* value)
{
#line 15 "/home/test/core/core/switcher.vala"
	g_return_if_fail (self != NULL);
#line 15 "/home/test/core/core/switcher.vala"
	if (midori_switcher_get_stack (self) != value) {
#line 466 "switcher.c"
		GtkStack* _tmp0_;
#line 15 "/home/test/core/core/switcher.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 15 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (self->priv->_stack);
#line 15 "/home/test/core/core/switcher.vala"
		self->priv->_stack = _tmp0_;
#line 15 "/home/test/core/core/switcher.vala"
		g_object_notify_by_pspec ((GObject *) self, midori_switcher_properties[MIDORI_SWITCHER_STACK_PROPERTY]);
#line 476 "switcher.c"
	}
}


gboolean
midori_switcher_get_show_close_buttons (MidoriSwitcher* self)
{
	gboolean result;
	gboolean _tmp0_;
#line 16 "/home/test/core/core/switcher.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 16 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->_show_close_buttons;
#line 16 "/home/test/core/core/switcher.vala"
	result = _tmp0_;
#line 16 "/home/test/core/core/switcher.vala"
	return result;
#line 494 "switcher.c"
}


void
midori_switcher_set_show_close_buttons (MidoriSwitcher* self,
                                        gboolean value)
{
#line 16 "/home/test/core/core/switcher.vala"
	g_return_if_fail (self != NULL);
#line 16 "/home/test/core/core/switcher.vala"
	if (midori_switcher_get_show_close_buttons (self) != value) {
#line 16 "/home/test/core/core/switcher.vala"
		self->priv->_show_close_buttons = value;
#line 16 "/home/test/core/core/switcher.vala"
		g_object_notify_by_pspec ((GObject *) self, midori_switcher_properties[MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY]);
#line 510 "switcher.c"
	}
}


static void
_g_object_unref0_ (gpointer var)
{
#line 19 "/home/test/core/core/switcher.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 520 "switcher.c"
}


static Block17Data*
block17_data_ref (Block17Data* _data17_)
{
#line 21 "/home/test/core/core/switcher.vala"
	g_atomic_int_inc (&_data17_->_ref_count_);
#line 21 "/home/test/core/core/switcher.vala"
	return _data17_;
#line 531 "switcher.c"
}


static void
block17_data_unref (void * _userdata_)
{
	Block17Data* _data17_;
	_data17_ = (Block17Data*) _userdata_;
#line 21 "/home/test/core/core/switcher.vala"
	if (g_atomic_int_dec_and_test (&_data17_->_ref_count_)) {
#line 542 "switcher.c"
		MidoriSwitcher* self;
#line 21 "/home/test/core/core/switcher.vala"
		self = _data17_->self;
#line 21 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (_data17_->widget);
#line 21 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (self);
#line 21 "/home/test/core/core/switcher.vala"
		g_slice_free (Block17Data, _data17_);
#line 552 "switcher.c"
	}
}


static void
___lambda121_ (Block17Data* _data17_)
{
	MidoriSwitcher* self;
	GtkStack* _tmp0_;
#line 26 "/home/test/core/core/switcher.vala"
	self = _data17_->self;
#line 27 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->_stack;
#line 27 "/home/test/core/core/switcher.vala"
	gtk_stack_set_visible_child (_tmp0_, _data17_->widget);
#line 568 "switcher.c"
}


static void
____lambda121__midori_tally_clicked (MidoriTally* _sender,
                                     gpointer self)
{
#line 26 "/home/test/core/core/switcher.vala"
	___lambda121_ (self);
#line 578 "switcher.c"
}


static void
__lambda120_ (MidoriSwitcher* self,
              GtkWidget* widget)
{
	Block17Data* _data17_;
	GtkWidget* _tmp0_;
	gboolean _tmp1_ = FALSE;
	GHashTable* _tmp2_;
	gconstpointer _tmp3_;
#line 21 "/home/test/core/core/switcher.vala"
	g_return_if_fail (widget != NULL);
#line 21 "/home/test/core/core/switcher.vala"
	_data17_ = g_slice_new0 (Block17Data);
#line 21 "/home/test/core/core/switcher.vala"
	_data17_->_ref_count_ = 1;
#line 21 "/home/test/core/core/switcher.vala"
	_data17_->self = g_object_ref (self);
#line 21 "/home/test/core/core/switcher.vala"
	_tmp0_ = _g_object_ref0 (widget);
#line 21 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (_data17_->widget);
#line 21 "/home/test/core/core/switcher.vala"
	_data17_->widget = _tmp0_;
#line 22 "/home/test/core/core/switcher.vala"
	_tmp2_ = self->priv->buttons;
#line 22 "/home/test/core/core/switcher.vala"
	_tmp3_ = g_hash_table_lookup (_tmp2_, _data17_->widget);
#line 22 "/home/test/core/core/switcher.vala"
	if (((MidoriTally*) _tmp3_) == NULL) {
#line 22 "/home/test/core/core/switcher.vala"
		_tmp1_ = MIDORI_IS_TAB (_data17_->widget);
#line 613 "switcher.c"
	} else {
#line 22 "/home/test/core/core/switcher.vala"
		_tmp1_ = FALSE;
#line 617 "switcher.c"
	}
#line 22 "/home/test/core/core/switcher.vala"
	if (_tmp1_) {
#line 621 "switcher.c"
		MidoriTally* button = NULL;
		MidoriTally* _tmp4_;
		GHashTable* _tmp5_;
		GtkWidget* _tmp6_;
		MidoriTally* _tmp7_;
		MidoriTally* _tmp8_;
		MidoriTally* _tmp9_;
		GtkStack* _tmp10_;
		GtkWidget* _tmp11_;
		GtkWidget* _tmp12_;
		MidoriTally* _tmp13_;
		GHashTable* _tmp14_;
		MidoriTally* _tmp15_;
		gboolean _tmp16_;
		MidoriTally* _tmp17_;
		MidoriTally* _tmp18_;
#line 23 "/home/test/core/core/switcher.vala"
		_tmp4_ = midori_tally_new (G_TYPE_CHECK_INSTANCE_CAST (_data17_->widget, MIDORI_TYPE_TAB, MidoriTab));
#line 23 "/home/test/core/core/switcher.vala"
		g_object_ref_sink (_tmp4_);
#line 23 "/home/test/core/core/switcher.vala"
		button = _tmp4_;
#line 24 "/home/test/core/core/switcher.vala"
		_tmp5_ = self->priv->buttons;
#line 24 "/home/test/core/core/switcher.vala"
		_tmp6_ = _g_object_ref0 (_data17_->widget);
#line 24 "/home/test/core/core/switcher.vala"
		_tmp7_ = button;
#line 24 "/home/test/core/core/switcher.vala"
		_tmp8_ = _g_object_ref0 (_tmp7_);
#line 24 "/home/test/core/core/switcher.vala"
		g_hash_table_insert (_tmp5_, _tmp6_, _tmp8_);
#line 25 "/home/test/core/core/switcher.vala"
		_tmp9_ = button;
#line 25 "/home/test/core/core/switcher.vala"
		_tmp10_ = self->priv->_stack;
#line 25 "/home/test/core/core/switcher.vala"
		_tmp11_ = gtk_stack_get_visible_child (_tmp10_);
#line 25 "/home/test/core/core/switcher.vala"
		_tmp12_ = _tmp11_;
#line 25 "/home/test/core/core/switcher.vala"
		midori_tally_set_active (_tmp9_, _tmp12_ == _data17_->widget);
#line 26 "/home/test/core/core/switcher.vala"
		_tmp13_ = button;
#line 26 "/home/test/core/core/switcher.vala"
		g_signal_connect_data (_tmp13_, "clicked", (GCallback) ____lambda121__midori_tally_clicked, block17_data_ref (_data17_), (GClosureNotify) block17_data_unref, 0);
#line 29 "/home/test/core/core/switcher.vala"
		_tmp14_ = self->priv->buttons;
#line 29 "/home/test/core/core/switcher.vala"
		midori_switcher_set_show_close_buttons (self, g_hash_table_size (_tmp14_) > ((guint) 1));
#line 30 "/home/test/core/core/switcher.vala"
		_tmp15_ = button;
#line 30 "/home/test/core/core/switcher.vala"
		_tmp16_ = self->priv->_show_close_buttons;
#line 30 "/home/test/core/core/switcher.vala"
		midori_tally_set_show_close (_tmp15_, _tmp16_);
#line 31 "/home/test/core/core/switcher.vala"
		_tmp17_ = button;
#line 31 "/home/test/core/core/switcher.vala"
		g_object_bind_property_with_closures ((GObject*) self, "show-close-buttons", (GObject*) _tmp17_, "show-close", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
#line 32 "/home/test/core/core/switcher.vala"
		_tmp18_ = button;
#line 32 "/home/test/core/core/switcher.vala"
		gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp18_);
#line 22 "/home/test/core/core/switcher.vala"
		_g_object_unref0 (button);
#line 688 "switcher.c"
	}
}


static void
___lambda120__gtk_container_add (GtkContainer* _sender,
                                 GtkWidget* widget,
                                 gpointer self)
{
#line 21 "/home/test/core/core/switcher.vala"
	__lambda120_ ((MidoriSwitcher*) self, widget);
#line 700 "switcher.c"
}


static void
_midori_switcher_visible_child_changed_g_object_notify (GObject* _sender,
                                                        GParamSpec* pspec,
                                                        gpointer self)
{
#line 35 "/home/test/core/core/switcher.vala"
	midori_switcher_visible_child_changed ((MidoriSwitcher*) self, pspec);
#line 711 "switcher.c"
}


static gpointer
_vala_g_hash_table_take (GHashTable* self,
                         gconstpointer key,
                         gboolean* exists)
{
	gboolean _vala_exists = FALSE;
	gpointer result = NULL;
	GHashTable* ht = NULL;
	void** htp = NULL;
	void** _tmp0_;
	gconstpointer _tmp1_;
#line 4867 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 4868 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	ht = NULL;
#line 4869 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	htp = &ht;
#line 4870 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = htp;
#line 4870 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1_ = g_hash_table_lookup (self, key);
#line 4870 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	*_tmp0_ = _tmp1_;
#line 4871 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_vala_exists = g_hash_table_steal (self, key);
#line 4872 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = ht;
#line 4872 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (exists) {
#line 4872 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		*exists = _vala_exists;
#line 746 "switcher.c"
	}
#line 4872 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 750 "switcher.c"
}


static void
__lambda122_ (MidoriSwitcher* self,
              GtkWidget* widget)
{
	GHashTable* _tmp0_;
	gpointer _tmp1_;
	MidoriTally* _tmp2_;
	GHashTable* _tmp3_;
#line 36 "/home/test/core/core/switcher.vala"
	g_return_if_fail (widget != NULL);
#line 37 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->buttons;
#line 37 "/home/test/core/core/switcher.vala"
	_tmp1_ = _vala_g_hash_table_take (_tmp0_, widget, NULL);
#line 37 "/home/test/core/core/switcher.vala"
	_tmp2_ = (MidoriTally*) _tmp1_;
#line 37 "/home/test/core/core/switcher.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp2_);
#line 37 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (_tmp2_);
#line 38 "/home/test/core/core/switcher.vala"
	_tmp3_ = self->priv->buttons;
#line 38 "/home/test/core/core/switcher.vala"
	midori_switcher_set_show_close_buttons (self, g_hash_table_size (_tmp3_) > ((guint) 1));
#line 778 "switcher.c"
}


static void
___lambda122__gtk_container_remove (GtkContainer* _sender,
                                    GtkWidget* widget,
                                    gpointer self)
{
#line 36 "/home/test/core/core/switcher.vala"
	__lambda122_ ((MidoriSwitcher*) self, widget);
#line 789 "switcher.c"
}


static void
_midori_switcher___lambda119_ (MidoriSwitcher* self,
                               GParamSpec* pspec)
{
	GtkStack* _tmp0_;
	GtkStack* _tmp1_;
	GtkStack* _tmp2_;
#line 20 "/home/test/core/core/switcher.vala"
	g_return_if_fail (pspec != NULL);
#line 21 "/home/test/core/core/switcher.vala"
	_tmp0_ = self->priv->_stack;
#line 21 "/home/test/core/core/switcher.vala"
	g_signal_connect_object ((GtkContainer*) _tmp0_, "add", (GCallback) ___lambda120__gtk_container_add, self, 0);
#line 35 "/home/test/core/core/switcher.vala"
	_tmp1_ = self->priv->_stack;
#line 35 "/home/test/core/core/switcher.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify::visible-child", (GCallback) _midori_switcher_visible_child_changed_g_object_notify, self, 0);
#line 36 "/home/test/core/core/switcher.vala"
	_tmp2_ = self->priv->_stack;
#line 36 "/home/test/core/core/switcher.vala"
	g_signal_connect_object ((GtkContainer*) _tmp2_, "remove", (GCallback) ___lambda122__gtk_container_remove, self, 0);
#line 814 "switcher.c"
}


static void
__midori_switcher___lambda119__g_object_notify (GObject* _sender,
                                                GParamSpec* pspec,
                                                gpointer self)
{
#line 20 "/home/test/core/core/switcher.vala"
	_midori_switcher___lambda119_ ((MidoriSwitcher*) self, pspec);
#line 825 "switcher.c"
}


static GObject *
midori_switcher_constructor (GType type,
                             guint n_construct_properties,
                             GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MidoriSwitcher * self;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
#line 18 "/home/test/core/core/switcher.vala"
	parent_class = G_OBJECT_CLASS (midori_switcher_parent_class);
#line 18 "/home/test/core/core/switcher.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 18 "/home/test/core/core/switcher.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_SWITCHER, MidoriSwitcher);
#line 19 "/home/test/core/core/switcher.vala"
	_tmp0_ = g_direct_hash;
#line 19 "/home/test/core/core/switcher.vala"
	_tmp1_ = g_direct_equal;
#line 19 "/home/test/core/core/switcher.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_object_unref0_, _g_object_unref0_);
#line 19 "/home/test/core/core/switcher.vala"
	_g_hash_table_unref0 (self->priv->buttons);
#line 19 "/home/test/core/core/switcher.vala"
	self->priv->buttons = _tmp2_;
#line 20 "/home/test/core/core/switcher.vala"
	g_signal_connect_object ((GObject*) self, "notify::stack", (GCallback) __midori_switcher___lambda119__g_object_notify, self, 0);
#line 18 "/home/test/core/core/switcher.vala"
	return obj;
#line 860 "switcher.c"
}


static void
midori_switcher_class_init (MidoriSwitcherClass * klass)
{
#line 13 "/home/test/core/core/switcher.vala"
	midori_switcher_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/test/core/core/switcher.vala"
	g_type_class_add_private (klass, sizeof (MidoriSwitcherPrivate));
#line 13 "/home/test/core/core/switcher.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_midori_switcher_get_property;
#line 13 "/home/test/core/core/switcher.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_midori_switcher_set_property;
#line 13 "/home/test/core/core/switcher.vala"
	G_OBJECT_CLASS (klass)->constructor = midori_switcher_constructor;
#line 13 "/home/test/core/core/switcher.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_switcher_finalize;
#line 13 "/home/test/core/core/switcher.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_SWITCHER_STACK_PROPERTY, midori_switcher_properties[MIDORI_SWITCHER_STACK_PROPERTY] = g_param_spec_object ("stack", "stack", "stack", gtk_stack_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 13 "/home/test/core/core/switcher.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY, midori_switcher_properties[MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY] = g_param_spec_boolean ("show-close-buttons", "show-close-buttons", "show-close-buttons", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 883 "switcher.c"
}


static void
midori_switcher_instance_init (MidoriSwitcher * self)
{
#line 13 "/home/test/core/core/switcher.vala"
	self->priv = MIDORI_SWITCHER_GET_PRIVATE (self);
#line 892 "switcher.c"
}


static void
midori_switcher_finalize (GObject * obj)
{
	MidoriSwitcher * self;
#line 13 "/home/test/core/core/switcher.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_SWITCHER, MidoriSwitcher);
#line 14 "/home/test/core/core/switcher.vala"
	_g_hash_table_unref0 (self->priv->buttons);
#line 15 "/home/test/core/core/switcher.vala"
	_g_object_unref0 (self->priv->_stack);
#line 13 "/home/test/core/core/switcher.vala"
	G_OBJECT_CLASS (midori_switcher_parent_class)->finalize (obj);
#line 908 "switcher.c"
}


GType
midori_switcher_get_type (void)
{
	static volatile gsize midori_switcher_type_id__volatile = 0;
	if (g_once_init_enter (&midori_switcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriSwitcherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_switcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriSwitcher), 0, (GInstanceInitFunc) midori_switcher_instance_init, NULL };
		GType midori_switcher_type_id;
		midori_switcher_type_id = g_type_register_static (gtk_box_get_type (), "MidoriSwitcher", &g_define_type_info, 0);
		g_once_init_leave (&midori_switcher_type_id__volatile, midori_switcher_type_id);
	}
	return midori_switcher_type_id__volatile;
}


static void
_vala_midori_switcher_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec)
{
	MidoriSwitcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_SWITCHER, MidoriSwitcher);
#line 13 "/home/test/core/core/switcher.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/switcher.vala"
		case MIDORI_SWITCHER_STACK_PROPERTY:
#line 13 "/home/test/core/core/switcher.vala"
		g_value_set_object (value, midori_switcher_get_stack (self));
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 13 "/home/test/core/core/switcher.vala"
		case MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY:
#line 13 "/home/test/core/core/switcher.vala"
		g_value_set_boolean (value, midori_switcher_get_show_close_buttons (self));
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 948 "switcher.c"
		default:
#line 13 "/home/test/core/core/switcher.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 954 "switcher.c"
	}
}


static void
_vala_midori_switcher_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec)
{
	MidoriSwitcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_SWITCHER, MidoriSwitcher);
#line 13 "/home/test/core/core/switcher.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/switcher.vala"
		case MIDORI_SWITCHER_STACK_PROPERTY:
#line 13 "/home/test/core/core/switcher.vala"
		midori_switcher_set_stack (self, g_value_get_object (value));
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 13 "/home/test/core/core/switcher.vala"
		case MIDORI_SWITCHER_SHOW_CLOSE_BUTTONS_PROPERTY:
#line 13 "/home/test/core/core/switcher.vala"
		midori_switcher_set_show_close_buttons (self, g_value_get_boolean (value));
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 981 "switcher.c"
		default:
#line 13 "/home/test/core/core/switcher.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/switcher.vala"
		break;
#line 987 "switcher.c"
	}
}



