/* activatable.c generated by valac 0.40.23, the Vala compiler
 * generated from activatable.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas.h>
#include "webkit2/webkit-web-extension.h"
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>


#define MIDORI_TYPE_PLUGINS (midori_plugins_get_type ())
#define MIDORI_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_PLUGINS, MidoriPlugins))
#define MIDORI_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_PLUGINS, MidoriPluginsClass))
#define MIDORI_IS_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_PLUGINS))
#define MIDORI_IS_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_PLUGINS))
#define MIDORI_PLUGINS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_PLUGINS, MidoriPluginsClass))

typedef struct _MidoriPlugins MidoriPlugins;
typedef struct _MidoriPluginsClass MidoriPluginsClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_SoupURI_free0(var) ((var == NULL) ? NULL : (var = (_vala_SoupURI_free (var), NULL)))

#define MIDORI_TYPE_DATABASE (midori_database_get_type ())
#define MIDORI_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_DATABASE, MidoriDatabase))
#define MIDORI_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_DATABASE, MidoriDatabaseClass))
#define MIDORI_IS_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_DATABASE))
#define MIDORI_IS_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_DATABASE))
#define MIDORI_DATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_DATABASE, MidoriDatabaseClass))

typedef struct _MidoriDatabase MidoriDatabase;
typedef struct _MidoriDatabaseClass MidoriDatabaseClass;

#define MIDORI_TYPE_HISTORY_DATABASE (midori_history_database_get_type ())
#define MIDORI_HISTORY_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_HISTORY_DATABASE, MidoriHistoryDatabase))
#define MIDORI_HISTORY_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_HISTORY_DATABASE, MidoriHistoryDatabaseClass))
#define MIDORI_IS_HISTORY_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_HISTORY_DATABASE))
#define MIDORI_IS_HISTORY_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_HISTORY_DATABASE))
#define MIDORI_HISTORY_DATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_HISTORY_DATABASE, MidoriHistoryDatabaseClass))

typedef struct _MidoriHistoryDatabase MidoriHistoryDatabase;
typedef struct _MidoriHistoryDatabaseClass MidoriHistoryDatabaseClass;

#define MIDORI_TYPE_DATABASE_STATEMENT (midori_database_statement_get_type ())
#define MIDORI_DATABASE_STATEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_DATABASE_STATEMENT, MidoriDatabaseStatement))
#define MIDORI_DATABASE_STATEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_DATABASE_STATEMENT, MidoriDatabaseStatementClass))
#define MIDORI_IS_DATABASE_STATEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_DATABASE_STATEMENT))
#define MIDORI_IS_DATABASE_STATEMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_DATABASE_STATEMENT))
#define MIDORI_DATABASE_STATEMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_DATABASE_STATEMENT, MidoriDatabaseStatementClass))

typedef struct _MidoriDatabaseStatement MidoriDatabaseStatement;
typedef struct _MidoriDatabaseStatementClass MidoriDatabaseStatementClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Block1Data {
	int _ref_count_;
	WebKitWebPage* page;
};

typedef enum  {
	MIDORI_DATABASE_ERROR_OPEN,
	MIDORI_DATABASE_ERROR_NAMING,
	MIDORI_DATABASE_ERROR_FILENAME,
	MIDORI_DATABASE_ERROR_EXECUTE,
	MIDORI_DATABASE_ERROR_COMPILE,
	MIDORI_DATABASE_ERROR_TYPE
} MidoriDatabaseError;
#define MIDORI_DATABASE_ERROR midori_database_error_quark ()

extern MidoriPlugins* plugins;
MidoriPlugins* plugins = NULL;

GType midori_plugins_get_type (void) G_GNUC_CONST;
void webkit_web_extension_initialize_with_user_data (WebKitWebExtension* extension,
                                                     GVariant* user_data);
MidoriPlugins* midori_plugins_get_default (const gchar* builtin_path);
static void __lambda5_ (WebKitWebPage* page);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda6_ (Block1Data* _data1_);
static void _vala_SoupURI_free (SoupURI* self);
GType midori_database_get_type (void) G_GNUC_CONST;
GType midori_history_database_get_type (void) G_GNUC_CONST;
GQuark midori_database_error_quark (void);
MidoriHistoryDatabase* midori_history_database_get_default (gboolean incognito,
                                                            GError** error);
GType midori_database_statement_get_type (void) G_GNUC_CONST;
MidoriDatabaseStatement* midori_database_prepare (MidoriDatabase* self,
                                                  const gchar* query,
                                                  GError** error,
                                                  ...);
const gchar* midori_database_get_table (MidoriDatabase* self);
gboolean midori_database_statement_exec (MidoriDatabaseStatement* self,
                                         GError** error);
static void ___lambda6__webkit_web_page_document_loaded (WebKitWebPage* _sender,
                                                  gpointer self);
PeasExtensionSet* midori_plugins_plug (MidoriPlugins* self,
                                       GType t_type,
                                       GBoxedCopyFunc t_dup_func,
                                       GDestroyNotify t_destroy_func,
                                       const gchar* name,
                                       GObject* object);
static void __lambda11_ (PeasPluginInfo* info,
                  GObject* extension);
static void ___lambda11__peas_extension_set_extension_added (PeasExtensionSet* _sender,
                                                      PeasPluginInfo* info,
                                                      GObject* exten,
                                                      gpointer self);
static void __lambda12_ (PeasPluginInfo* info,
                  GObject* extension);
static void ___lambda12__peas_extension_set_extension_removed (PeasExtensionSet* _sender,
                                                        PeasPluginInfo* info,
                                                        GObject* exten,
                                                        gpointer self);
static void __lambda13_ (PeasExtensionSet* extensions,
                  PeasPluginInfo* info,
                  PeasExtension* extension);
static void ___lambda13__peas_extension_set_foreach_func (PeasExtensionSet* set,
                                                   PeasPluginInfo* info,
                                                   PeasExtension* exten,
                                                   gpointer self);
static void ___lambda5__webkit_web_extension_page_created (WebKitWebExtension* _sender,
                                                    WebKitWebPage* web_page,
                                                    gpointer self);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 15 "/home/test/core/web/activatable.vala"
	return self ? g_object_ref (self) : NULL;
#line 148 "activatable.c"
}


static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 15 "/home/test/core/web/activatable.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 15 "/home/test/core/web/activatable.vala"
	return _data1_;
#line 159 "activatable.c"
}


static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 15 "/home/test/core/web/activatable.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 15 "/home/test/core/web/activatable.vala"
		_g_object_unref0 (_data1_->page);
#line 15 "/home/test/core/web/activatable.vala"
		g_slice_free (Block1Data, _data1_);
#line 174 "activatable.c"
	}
}


static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gboolean result = FALSE;
	gchar* _tmp0_;
#line 1475 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1475 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 195 "activatable.c"
}


static void
_vala_SoupURI_free (SoupURI* self)
{
#line 29 "/home/test/core/web/activatable.vala"
	g_boxed_free (soup_uri_get_type (), self);
#line 204 "activatable.c"
}


static void
__lambda6_ (Block1Data* _data1_)
{
	GError* _inner_error0_ = NULL;
	{
		WebKitDOMElement* image = NULL;
		WebKitDOMDocument* _tmp0_;
		WebKitDOMElement* _tmp1_;
		WebKitDOMElement* _tmp2_;
		gchar* _tmp3_ = NULL;
		WebKitDOMElement* _tmp4_;
		gchar* uri = NULL;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		gboolean _tmp18_ = FALSE;
		const gchar* _tmp19_;
#line 20 "/home/test/core/web/activatable.vala"
		_tmp0_ = webkit_web_page_get_dom_document (_data1_->page);
#line 20 "/home/test/core/web/activatable.vala"
		_tmp1_ = webkit_dom_document_query_selector (_tmp0_, "meta[property=\"og:image\"],meta[name=\"og:image\"]", &_inner_error0_);
#line 20 "/home/test/core/web/activatable.vala"
		_tmp2_ = _g_object_ref0 (_tmp1_);
#line 20 "/home/test/core/web/activatable.vala"
		image = _tmp2_;
#line 20 "/home/test/core/web/activatable.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 234 "activatable.c"
			goto __catch0_g_error;
		}
#line 21 "/home/test/core/web/activatable.vala"
		_tmp4_ = image;
#line 21 "/home/test/core/web/activatable.vala"
		if (_tmp4_ != NULL) {
#line 241 "activatable.c"
			WebKitDOMElement* _tmp5_;
			gchar* _tmp6_;
#line 21 "/home/test/core/web/activatable.vala"
			_tmp5_ = image;
#line 21 "/home/test/core/web/activatable.vala"
			_tmp6_ = webkit_dom_element_get_attribute (_tmp5_, "content");
#line 21 "/home/test/core/web/activatable.vala"
			_g_free0 (_tmp3_);
#line 21 "/home/test/core/web/activatable.vala"
			_tmp3_ = _tmp6_;
#line 252 "activatable.c"
		} else {
#line 21 "/home/test/core/web/activatable.vala"
			_g_free0 (_tmp3_);
#line 21 "/home/test/core/web/activatable.vala"
			_tmp3_ = NULL;
#line 258 "activatable.c"
		}
#line 21 "/home/test/core/web/activatable.vala"
		_tmp7_ = g_strdup (_tmp3_);
#line 21 "/home/test/core/web/activatable.vala"
		uri = _tmp7_;
#line 22 "/home/test/core/web/activatable.vala"
		_tmp8_ = uri;
#line 22 "/home/test/core/web/activatable.vala"
		if (_tmp8_ == NULL) {
#line 268 "activatable.c"
			WebKitDOMElement* _tmp9_ = NULL;
			WebKitDOMDocument* _tmp10_;
			WebKitDOMElement* _tmp11_;
			WebKitDOMElement* _tmp12_;
			gchar* _tmp13_ = NULL;
			WebKitDOMElement* _tmp14_;
			gchar* _tmp17_;
#line 24 "/home/test/core/web/activatable.vala"
			_tmp10_ = webkit_web_page_get_dom_document (_data1_->page);
#line 24 "/home/test/core/web/activatable.vala"
			_tmp11_ = webkit_dom_document_query_selector (_tmp10_, "link[sizes=\"any\"],link[sizes=\"152x152\"],link[sizes=\"144x144\"]", &_inner_error0_);
#line 24 "/home/test/core/web/activatable.vala"
			_tmp9_ = _tmp11_;
#line 24 "/home/test/core/web/activatable.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 24 "/home/test/core/web/activatable.vala"
				_g_free0 (uri);
#line 24 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp3_);
#line 24 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (image);
#line 290 "activatable.c"
				goto __catch0_g_error;
			}
#line 24 "/home/test/core/web/activatable.vala"
			_tmp12_ = _g_object_ref0 (_tmp9_);
#line 24 "/home/test/core/web/activatable.vala"
			_g_object_unref0 (image);
#line 24 "/home/test/core/web/activatable.vala"
			image = _tmp12_;
#line 25 "/home/test/core/web/activatable.vala"
			_tmp14_ = image;
#line 25 "/home/test/core/web/activatable.vala"
			if (_tmp14_ != NULL) {
#line 303 "activatable.c"
				WebKitDOMElement* _tmp15_;
				gchar* _tmp16_;
#line 25 "/home/test/core/web/activatable.vala"
				_tmp15_ = image;
#line 25 "/home/test/core/web/activatable.vala"
				_tmp16_ = webkit_dom_element_get_attribute (_tmp15_, "href");
#line 25 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp13_);
#line 25 "/home/test/core/web/activatable.vala"
				_tmp13_ = _tmp16_;
#line 314 "activatable.c"
			} else {
#line 25 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp13_);
#line 25 "/home/test/core/web/activatable.vala"
				_tmp13_ = NULL;
#line 320 "activatable.c"
			}
#line 25 "/home/test/core/web/activatable.vala"
			_tmp17_ = g_strdup (_tmp13_);
#line 25 "/home/test/core/web/activatable.vala"
			_g_free0 (uri);
#line 25 "/home/test/core/web/activatable.vala"
			uri = _tmp17_;
#line 22 "/home/test/core/web/activatable.vala"
			_g_free0 (_tmp13_);
#line 330 "activatable.c"
		}
#line 27 "/home/test/core/web/activatable.vala"
		_tmp19_ = uri;
#line 27 "/home/test/core/web/activatable.vala"
		if (_tmp19_ != NULL) {
#line 336 "activatable.c"
			const gchar* _tmp20_;
#line 27 "/home/test/core/web/activatable.vala"
			_tmp20_ = uri;
#line 27 "/home/test/core/web/activatable.vala"
			_tmp18_ = g_strcmp0 (_tmp20_, "") != 0;
#line 342 "activatable.c"
		} else {
#line 27 "/home/test/core/web/activatable.vala"
			_tmp18_ = FALSE;
#line 346 "activatable.c"
		}
#line 27 "/home/test/core/web/activatable.vala"
		if (_tmp18_) {
#line 350 "activatable.c"
			const gchar* _tmp21_;
			const gchar* _tmp32_;
			const gchar* _tmp33_;
			const gchar* _tmp34_;
			MidoriHistoryDatabase* history = NULL;
			MidoriHistoryDatabase* _tmp35_;
			MidoriDatabaseStatement* _tmp36_ = NULL;
			MidoriHistoryDatabase* _tmp37_;
			MidoriHistoryDatabase* _tmp38_;
			const gchar* _tmp39_;
			const gchar* _tmp40_;
			gchar* _tmp41_;
			gchar* _tmp42_;
			const gchar* _tmp43_;
			const gchar* _tmp44_;
			const gchar* _tmp45_;
			MidoriDatabaseStatement* _tmp46_;
			MidoriDatabaseStatement* _tmp47_;
#line 29 "/home/test/core/web/activatable.vala"
			_tmp21_ = uri;
#line 29 "/home/test/core/web/activatable.vala"
			if (!string_contains (_tmp21_, "://")) {
#line 373 "activatable.c"
				SoupURI* soup_uri = NULL;
				const gchar* _tmp22_;
				const gchar* _tmp23_;
				SoupURI* _tmp24_;
				SoupURI* _tmp25_;
				const gchar* _tmp26_;
				gchar* _tmp27_;
				gchar* _tmp28_;
				SoupURI* _tmp29_;
				SoupURI* _tmp30_;
				gchar* _tmp31_;
#line 30 "/home/test/core/web/activatable.vala"
				_tmp22_ = webkit_web_page_get_uri (_data1_->page);
#line 30 "/home/test/core/web/activatable.vala"
				_tmp23_ = _tmp22_;
#line 30 "/home/test/core/web/activatable.vala"
				_tmp24_ = soup_uri_new (_tmp23_);
#line 30 "/home/test/core/web/activatable.vala"
				soup_uri = _tmp24_;
#line 31 "/home/test/core/web/activatable.vala"
				_tmp25_ = soup_uri;
#line 31 "/home/test/core/web/activatable.vala"
				_tmp26_ = uri;
#line 31 "/home/test/core/web/activatable.vala"
				_tmp27_ = g_strconcat ("/", _tmp26_, NULL);
#line 31 "/home/test/core/web/activatable.vala"
				_tmp28_ = _tmp27_;
#line 31 "/home/test/core/web/activatable.vala"
				soup_uri_set_path (_tmp25_, _tmp28_);
#line 31 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp28_);
#line 32 "/home/test/core/web/activatable.vala"
				_tmp29_ = soup_uri;
#line 32 "/home/test/core/web/activatable.vala"
				soup_uri_set_query (_tmp29_, NULL);
#line 33 "/home/test/core/web/activatable.vala"
				_tmp30_ = soup_uri;
#line 33 "/home/test/core/web/activatable.vala"
				_tmp31_ = soup_uri_to_string (_tmp30_, FALSE);
#line 33 "/home/test/core/web/activatable.vala"
				_g_free0 (uri);
#line 33 "/home/test/core/web/activatable.vala"
				uri = _tmp31_;
#line 29 "/home/test/core/web/activatable.vala"
				__vala_SoupURI_free0 (soup_uri);
#line 419 "activatable.c"
			}
#line 35 "/home/test/core/web/activatable.vala"
			_tmp32_ = webkit_web_page_get_uri (_data1_->page);
#line 35 "/home/test/core/web/activatable.vala"
			_tmp33_ = _tmp32_;
#line 35 "/home/test/core/web/activatable.vala"
			_tmp34_ = uri;
#line 35 "/home/test/core/web/activatable.vala"
			g_debug ("activatable.vala:35: Found thumbnail for %s: %s", _tmp33_, _tmp34_);
#line 36 "/home/test/core/web/activatable.vala"
			_tmp35_ = midori_history_database_get_default (FALSE, &_inner_error0_);
#line 36 "/home/test/core/web/activatable.vala"
			history = _tmp35_;
#line 36 "/home/test/core/web/activatable.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 36 "/home/test/core/web/activatable.vala"
				_g_free0 (uri);
#line 36 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp3_);
#line 36 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (image);
#line 441 "activatable.c"
				goto __catch0_g_error;
			}
#line 37 "/home/test/core/web/activatable.vala"
			_tmp37_ = history;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp38_ = history;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp39_ = midori_database_get_table ((MidoriDatabase*) _tmp38_);
#line 37 "/home/test/core/web/activatable.vala"
			_tmp40_ = _tmp39_;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp41_ = g_strdup_printf ("UPDATE %s SET image = :image WHERE uri = :uri", _tmp40_);
#line 37 "/home/test/core/web/activatable.vala"
			_tmp42_ = _tmp41_;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp43_ = uri;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp44_ = webkit_web_page_get_uri (_data1_->page);
#line 37 "/home/test/core/web/activatable.vala"
			_tmp45_ = _tmp44_;
#line 37 "/home/test/core/web/activatable.vala"
			_tmp46_ = midori_database_prepare ((MidoriDatabase*) _tmp37_, _tmp42_, &_inner_error0_, ":image", G_TYPE_STRING, _tmp43_, ":uri", G_TYPE_STRING, _tmp45_, NULL);
#line 37 "/home/test/core/web/activatable.vala"
			_tmp47_ = _tmp46_;
#line 37 "/home/test/core/web/activatable.vala"
			_g_free0 (_tmp42_);
#line 37 "/home/test/core/web/activatable.vala"
			_tmp36_ = _tmp47_;
#line 37 "/home/test/core/web/activatable.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 37 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (history);
#line 37 "/home/test/core/web/activatable.vala"
				_g_free0 (uri);
#line 37 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp3_);
#line 37 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (image);
#line 480 "activatable.c"
				goto __catch0_g_error;
			}
#line 37 "/home/test/core/web/activatable.vala"
			midori_database_statement_exec (_tmp36_, &_inner_error0_);
#line 37 "/home/test/core/web/activatable.vala"
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 37 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (_tmp36_);
#line 37 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (history);
#line 37 "/home/test/core/web/activatable.vala"
				_g_free0 (uri);
#line 37 "/home/test/core/web/activatable.vala"
				_g_free0 (_tmp3_);
#line 37 "/home/test/core/web/activatable.vala"
				_g_object_unref0 (image);
#line 497 "activatable.c"
				goto __catch0_g_error;
			}
#line 27 "/home/test/core/web/activatable.vala"
			_g_object_unref0 (_tmp36_);
#line 27 "/home/test/core/web/activatable.vala"
			_g_object_unref0 (history);
#line 504 "activatable.c"
		}
#line 17 "/home/test/core/web/activatable.vala"
		_g_free0 (uri);
#line 17 "/home/test/core/web/activatable.vala"
		_g_free0 (_tmp3_);
#line 17 "/home/test/core/web/activatable.vala"
		_g_object_unref0 (image);
#line 512 "activatable.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* _error_ = NULL;
		const gchar* _tmp48_;
		const gchar* _tmp49_;
		GError* _tmp50_;
		const gchar* _tmp51_;
#line 17 "/home/test/core/web/activatable.vala"
		_error_ = _inner_error0_;
#line 17 "/home/test/core/web/activatable.vala"
		_inner_error0_ = NULL;
#line 42 "/home/test/core/web/activatable.vala"
		_tmp48_ = webkit_web_page_get_uri (_data1_->page);
#line 42 "/home/test/core/web/activatable.vala"
		_tmp49_ = _tmp48_;
#line 42 "/home/test/core/web/activatable.vala"
		_tmp50_ = _error_;
#line 42 "/home/test/core/web/activatable.vala"
		_tmp51_ = _tmp50_->message;
#line 42 "/home/test/core/web/activatable.vala"
		g_debug ("activatable.vala:42: Failed to locate thumbnail for %s: %s", _tmp49_, _tmp51_);
#line 17 "/home/test/core/web/activatable.vala"
		_g_error_free0 (_error_);
#line 538 "activatable.c"
	}
	__finally0:
#line 17 "/home/test/core/web/activatable.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 17 "/home/test/core/web/activatable.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 17 "/home/test/core/web/activatable.vala"
		g_clear_error (&_inner_error0_);
#line 17 "/home/test/core/web/activatable.vala"
		return;
#line 549 "activatable.c"
	}
}


static void
___lambda6__webkit_web_page_document_loaded (WebKitWebPage* _sender,
                                             gpointer self)
{
#line 16 "/home/test/core/web/activatable.vala"
	__lambda6_ (self);
#line 560 "activatable.c"
}


static void
__lambda11_ (PeasPluginInfo* info,
             GObject* extension)
{
#line 46 "/home/test/core/web/activatable.vala"
	g_return_if_fail (info != NULL);
#line 46 "/home/test/core/web/activatable.vala"
	g_return_if_fail (extension != NULL);
#line 46 "/home/test/core/web/activatable.vala"
	peas_activatable_activate (G_TYPE_CHECK_INSTANCE_CAST (extension, peas_activatable_get_type (), PeasActivatable));
#line 574 "activatable.c"
}


static void
___lambda11__peas_extension_set_extension_added (PeasExtensionSet* _sender,
                                                 PeasPluginInfo* info,
                                                 GObject* exten,
                                                 gpointer self)
{
#line 46 "/home/test/core/web/activatable.vala"
	__lambda11_ (info, exten);
#line 586 "activatable.c"
}


static void
__lambda12_ (PeasPluginInfo* info,
             GObject* extension)
{
#line 47 "/home/test/core/web/activatable.vala"
	g_return_if_fail (info != NULL);
#line 47 "/home/test/core/web/activatable.vala"
	g_return_if_fail (extension != NULL);
#line 47 "/home/test/core/web/activatable.vala"
	peas_activatable_deactivate (G_TYPE_CHECK_INSTANCE_CAST (extension, peas_activatable_get_type (), PeasActivatable));
#line 600 "activatable.c"
}


static void
___lambda12__peas_extension_set_extension_removed (PeasExtensionSet* _sender,
                                                   PeasPluginInfo* info,
                                                   GObject* exten,
                                                   gpointer self)
{
#line 47 "/home/test/core/web/activatable.vala"
	__lambda12_ (info, exten);
#line 612 "activatable.c"
}


static void
__lambda13_ (PeasExtensionSet* extensions,
             PeasPluginInfo* info,
             PeasExtension* extension)
{
#line 48 "/home/test/core/web/activatable.vala"
	g_return_if_fail (extensions != NULL);
#line 48 "/home/test/core/web/activatable.vala"
	g_return_if_fail (info != NULL);
#line 48 "/home/test/core/web/activatable.vala"
	g_return_if_fail (extension != NULL);
#line 48 "/home/test/core/web/activatable.vala"
	g_signal_emit_by_name (extensions, "extension-added", info, (GObject*) extension);
#line 629 "activatable.c"
}


static void
___lambda13__peas_extension_set_foreach_func (PeasExtensionSet* set,
                                              PeasPluginInfo* info,
                                              PeasExtension* exten,
                                              gpointer self)
{
#line 48 "/home/test/core/web/activatable.vala"
	__lambda13_ (set, info, exten);
#line 641 "activatable.c"
}


static void
__lambda5_ (WebKitWebPage* page)
{
	Block1Data* _data1_;
	WebKitWebPage* _tmp0_;
	PeasExtensionSet* extensions = NULL;
	MidoriPlugins* _tmp1_;
	PeasExtensionSet* _tmp2_;
#line 15 "/home/test/core/web/activatable.vala"
	g_return_if_fail (page != NULL);
#line 15 "/home/test/core/web/activatable.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 15 "/home/test/core/web/activatable.vala"
	_data1_->_ref_count_ = 1;
#line 15 "/home/test/core/web/activatable.vala"
	_tmp0_ = _g_object_ref0 (page);
#line 15 "/home/test/core/web/activatable.vala"
	_g_object_unref0 (_data1_->page);
#line 15 "/home/test/core/web/activatable.vala"
	_data1_->page = _tmp0_;
#line 16 "/home/test/core/web/activatable.vala"
	g_signal_connect_data (_data1_->page, "document-loaded", (GCallback) ___lambda6__webkit_web_page_document_loaded, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 45 "/home/test/core/web/activatable.vala"
	_tmp1_ = plugins;
#line 45 "/home/test/core/web/activatable.vala"
	_tmp2_ = midori_plugins_plug (_tmp1_, peas_activatable_get_type (), (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, "object", (GObject*) _data1_->page);
#line 45 "/home/test/core/web/activatable.vala"
	extensions = _tmp2_;
#line 46 "/home/test/core/web/activatable.vala"
	g_signal_connect (extensions, "extension-added", (GCallback) ___lambda11__peas_extension_set_extension_added, NULL);
#line 47 "/home/test/core/web/activatable.vala"
	g_signal_connect (extensions, "extension-removed", (GCallback) ___lambda12__peas_extension_set_extension_removed, NULL);
#line 48 "/home/test/core/web/activatable.vala"
	peas_extension_set_foreach (extensions, ___lambda13__peas_extension_set_foreach_func, NULL);
#line 15 "/home/test/core/web/activatable.vala"
	_g_object_unref0 (extensions);
#line 15 "/home/test/core/web/activatable.vala"
	block1_data_unref (_data1_);
#line 15 "/home/test/core/web/activatable.vala"
	_data1_ = NULL;
#line 685 "activatable.c"
}


static void
___lambda5__webkit_web_extension_page_created (WebKitWebExtension* _sender,
                                               WebKitWebPage* web_page,
                                               gpointer self)
{
#line 15 "/home/test/core/web/activatable.vala"
	__lambda5_ (web_page);
#line 696 "activatable.c"
}


void
webkit_web_extension_initialize_with_user_data (WebKitWebExtension* extension,
                                                GVariant* user_data)
{
	const gchar* _tmp0_;
	MidoriPlugins* _tmp1_;
#line 13 "/home/test/core/web/activatable.vala"
	g_return_if_fail (extension != NULL);
#line 13 "/home/test/core/web/activatable.vala"
	g_return_if_fail (user_data != NULL);
#line 14 "/home/test/core/web/activatable.vala"
	_tmp0_ = g_variant_get_string (user_data, NULL);
#line 14 "/home/test/core/web/activatable.vala"
	_tmp1_ = midori_plugins_get_default (_tmp0_);
#line 14 "/home/test/core/web/activatable.vala"
	_g_object_unref0 (plugins);
#line 14 "/home/test/core/web/activatable.vala"
	plugins = _tmp1_;
#line 15 "/home/test/core/web/activatable.vala"
	g_signal_connect (extension, "page-created", (GCallback) ___lambda5__webkit_web_extension_page_created, NULL);
#line 720 "activatable.c"
}



