/* plugins.c generated by valac 0.40.23, the Vala compiler
 * generated from plugins.vala, do not modify */

/*
 Copyright (C) 2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas.h>
#include <stdlib.h>
#include <string.h>
#include "config.h"


#define MIDORI_TYPE_LOGGABLE (midori_loggable_get_type ())
#define MIDORI_LOGGABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_LOGGABLE, MidoriLoggable))
#define MIDORI_IS_LOGGABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_LOGGABLE))
#define MIDORI_LOGGABLE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MIDORI_TYPE_LOGGABLE, MidoriLoggableIface))

typedef struct _MidoriLoggable MidoriLoggable;
typedef struct _MidoriLoggableIface MidoriLoggableIface;

#define MIDORI_TYPE_PLUGINS (midori_plugins_get_type ())
#define MIDORI_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_PLUGINS, MidoriPlugins))
#define MIDORI_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_PLUGINS, MidoriPluginsClass))
#define MIDORI_IS_PLUGINS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_PLUGINS))
#define MIDORI_IS_PLUGINS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_PLUGINS))
#define MIDORI_PLUGINS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_PLUGINS, MidoriPluginsClass))

typedef struct _MidoriPlugins MidoriPlugins;
typedef struct _MidoriPluginsClass MidoriPluginsClass;
typedef struct _MidoriPluginsPrivate MidoriPluginsPrivate;
enum  {
	MIDORI_PLUGINS_0_PROPERTY,
	MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY,
	MIDORI_PLUGINS_NUM_PROPERTIES
};
static GParamSpec* midori_plugins_properties[MIDORI_PLUGINS_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define MIDORI_TYPE_SETTINGS (midori_settings_get_type ())
#define MIDORI_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_SETTINGS, MidoriSettings))
#define MIDORI_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_SETTINGS, MidoriSettingsClass))
#define MIDORI_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_SETTINGS))
#define MIDORI_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_SETTINGS))
#define MIDORI_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_SETTINGS, MidoriSettingsClass))

typedef struct _MidoriSettings MidoriSettings;
typedef struct _MidoriSettingsClass MidoriSettingsClass;

#define MIDORI_TYPE_CORE_SETTINGS (midori_core_settings_get_type ())
#define MIDORI_CORE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettings))
#define MIDORI_CORE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettingsClass))
#define MIDORI_IS_CORE_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_CORE_SETTINGS))
#define MIDORI_IS_CORE_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_CORE_SETTINGS))
#define MIDORI_CORE_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_CORE_SETTINGS, MidoriCoreSettingsClass))

typedef struct _MidoriCoreSettings MidoriCoreSettings;
typedef struct _MidoriCoreSettingsClass MidoriCoreSettingsClass;
#define __vala_PeasPluginInfo_free0(var) ((var == NULL) ? NULL : (var = (_vala_PeasPluginInfo_free (var), NULL)))

struct _MidoriLoggableIface {
	GTypeInterface parent_iface;
};

struct _MidoriPlugins {
	PeasEngine parent_instance;
	MidoriPluginsPrivate * priv;
};

struct _MidoriPluginsClass {
	PeasEngineClass parent_class;
};

struct _MidoriPluginsPrivate {
	gchar* _builtin_path;
};


static gpointer midori_plugins_parent_class = NULL;
static MidoriPlugins* midori_plugins__default;
static MidoriPlugins* midori_plugins__default = NULL;
static MidoriLoggableIface * midori_plugins_midori_loggable_parent_iface = NULL;

GType midori_loggable_get_type (void) G_GNUC_CONST;
GType midori_plugins_get_type (void) G_GNUC_CONST;
#define MIDORI_PLUGINS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_PLUGINS, MidoriPluginsPrivate))
MidoriPlugins* midori_plugins_get_default (const gchar* builtin_path);
static MidoriPlugins* midori_plugins_new (const gchar* builtin_path);
static MidoriPlugins* midori_plugins_construct (GType object_type,
                                         const gchar* builtin_path);
PeasExtensionSet* midori_plugins_plug (MidoriPlugins* self,
                                       GType t_type,
                                       GBoxedCopyFunc t_dup_func,
                                       GDestroyNotify t_destroy_func,
                                       const gchar* name,
                                       GObject* object);
const gchar* midori_plugins_get_builtin_path (MidoriPlugins* self);
void midori_plugins_set_builtin_path (MidoriPlugins* self,
                                      const gchar* value);
static GObject * midori_plugins_constructor (GType type,
                                      guint n_construct_properties,
                                      GObjectConstructParam * construct_properties);
void midori_loggable_debug (MidoriLoggable* self,
                            const gchar* format,
                            ...);
GType midori_settings_get_type (void) G_GNUC_CONST;
GType midori_core_settings_get_type (void) G_GNUC_CONST;
MidoriCoreSettings* midori_core_settings_get_default (void);
static PeasPluginInfo* _vala_PeasPluginInfo_copy (PeasPluginInfo* self);
gboolean midori_core_settings_get_plugin_enabled (MidoriCoreSettings* self,
                                                  const gchar* plugin);
static void _vala_PeasPluginInfo_free (PeasPluginInfo* self);
static void midori_plugins_finalize (GObject * obj);
static void _vala_midori_plugins_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec);
static void _vala_midori_plugins_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "/home/test/core/core/plugins.vala"
	return self ? g_object_ref (self) : NULL;
#line 141 "plugins.c"
}


MidoriPlugins*
midori_plugins_get_default (const gchar* builtin_path)
{
	MidoriPlugins* result = NULL;
	MidoriPlugins* _tmp0_;
	MidoriPlugins* _tmp2_;
	MidoriPlugins* _tmp3_;
#line 19 "/home/test/core/core/plugins.vala"
	_tmp0_ = midori_plugins__default;
#line 19 "/home/test/core/core/plugins.vala"
	if (_tmp0_ == NULL) {
#line 156 "plugins.c"
		MidoriPlugins* _tmp1_;
#line 20 "/home/test/core/core/plugins.vala"
		_tmp1_ = midori_plugins_new (builtin_path);
#line 20 "/home/test/core/core/plugins.vala"
		_g_object_unref0 (midori_plugins__default);
#line 20 "/home/test/core/core/plugins.vala"
		midori_plugins__default = _tmp1_;
#line 164 "plugins.c"
	}
#line 22 "/home/test/core/core/plugins.vala"
	_tmp2_ = midori_plugins__default;
#line 22 "/home/test/core/core/plugins.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 22 "/home/test/core/core/plugins.vala"
	result = _tmp3_;
#line 22 "/home/test/core/core/plugins.vala"
	return result;
#line 174 "plugins.c"
}


static MidoriPlugins*
midori_plugins_construct (GType object_type,
                          const gchar* builtin_path)
{
	MidoriPlugins * self = NULL;
#line 25 "/home/test/core/core/plugins.vala"
	g_return_val_if_fail (builtin_path != NULL, NULL);
#line 26 "/home/test/core/core/plugins.vala"
	self = (MidoriPlugins*) g_object_new (object_type, "builtin-path", builtin_path, NULL);
#line 25 "/home/test/core/core/plugins.vala"
	return self;
#line 189 "plugins.c"
}


static MidoriPlugins*
midori_plugins_new (const gchar* builtin_path)
{
#line 25 "/home/test/core/core/plugins.vala"
	return midori_plugins_construct (MIDORI_TYPE_PLUGINS, builtin_path);
#line 198 "plugins.c"
}


PeasExtensionSet*
midori_plugins_plug (MidoriPlugins* self,
                     GType t_type,
                     GBoxedCopyFunc t_dup_func,
                     GDestroyNotify t_destroy_func,
                     const gchar* name,
                     GObject* object)
{
	PeasExtensionSet* result = NULL;
	PeasExtensionSet* extensions = NULL;
	PeasExtensionSet* _tmp0_;
	GObject* _tmp1_;
#line 54 "/home/test/core/core/plugins.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 54 "/home/test/core/core/plugins.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 54 "/home/test/core/core/plugins.vala"
	g_return_val_if_fail (object != NULL, NULL);
#line 55 "/home/test/core/core/plugins.vala"
	_tmp0_ = peas_extension_set_new ((PeasEngine*) self, t_type, name, object, NULL, NULL);
#line 55 "/home/test/core/core/plugins.vala"
	extensions = _tmp0_;
#line 56 "/home/test/core/core/plugins.vala"
	_tmp1_ = _g_object_ref0 ((GObject*) extensions);
#line 56 "/home/test/core/core/plugins.vala"
	g_object_set_data_full (object, "midori-plug", _tmp1_, g_object_unref);
#line 57 "/home/test/core/core/plugins.vala"
	result = extensions;
#line 57 "/home/test/core/core/plugins.vala"
	return result;
#line 232 "plugins.c"
}


const gchar*
midori_plugins_get_builtin_path (MidoriPlugins* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 14 "/home/test/core/core/plugins.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 14 "/home/test/core/core/plugins.vala"
	_tmp0_ = self->priv->_builtin_path;
#line 14 "/home/test/core/core/plugins.vala"
	result = _tmp0_;
#line 14 "/home/test/core/core/plugins.vala"
	return result;
#line 249 "plugins.c"
}


void
midori_plugins_set_builtin_path (MidoriPlugins* self,
                                 const gchar* value)
{
#line 14 "/home/test/core/core/plugins.vala"
	g_return_if_fail (self != NULL);
#line 14 "/home/test/core/core/plugins.vala"
	if (g_strcmp0 (value, midori_plugins_get_builtin_path (self)) != 0) {
#line 261 "plugins.c"
		gchar* _tmp0_;
#line 14 "/home/test/core/core/plugins.vala"
		_tmp0_ = g_strdup (value);
#line 14 "/home/test/core/core/plugins.vala"
		_g_free0 (self->priv->_builtin_path);
#line 14 "/home/test/core/core/plugins.vala"
		self->priv->_builtin_path = _tmp0_;
#line 14 "/home/test/core/core/plugins.vala"
		g_object_notify_by_pspec ((GObject *) self, midori_plugins_properties[MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY]);
#line 271 "plugins.c"
	}
}


static PeasPluginInfo*
_vala_PeasPluginInfo_copy (PeasPluginInfo* self)
{
#line 40 "/home/test/core/core/plugins.vala"
	return g_boxed_copy (peas_plugin_info_get_type (), self);
#line 281 "plugins.c"
}


static gpointer
__vala_PeasPluginInfo_copy0 (gpointer self)
{
#line 40 "/home/test/core/core/plugins.vala"
	return self ? _vala_PeasPluginInfo_copy (self) : NULL;
#line 290 "plugins.c"
}


static void
_vala_PeasPluginInfo_free (PeasPluginInfo* self)
{
#line 40 "/home/test/core/core/plugins.vala"
	g_boxed_free (peas_plugin_info_get_type (), self);
#line 299 "plugins.c"
}


static GObject *
midori_plugins_constructor (GType type,
                            guint n_construct_properties,
                            GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MidoriPlugins * self;
	gchar* user_path = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	MidoriCoreSettings* settings = NULL;
	MidoriCoreSettings* _tmp7_;
	GList* _tmp8_;
#line 29 "/home/test/core/core/plugins.vala"
	parent_class = G_OBJECT_CLASS (midori_plugins_parent_class);
#line 29 "/home/test/core/core/plugins.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 29 "/home/test/core/core/plugins.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_PLUGINS, MidoriPlugins);
#line 30 "/home/test/core/core/plugins.vala"
	peas_engine_enable_loader ((PeasEngine*) self, "python");
#line 32 "/home/test/core/core/plugins.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 32 "/home/test/core/core/plugins.vala"
	_tmp1_ = g_build_path (G_DIR_SEPARATOR_S, _tmp0_, PROJECT_NAME, "extensions", NULL);
#line 32 "/home/test/core/core/plugins.vala"
	user_path = _tmp1_;
#line 34 "/home/test/core/core/plugins.vala"
	_tmp2_ = user_path;
#line 34 "/home/test/core/core/plugins.vala"
	midori_loggable_debug ((MidoriLoggable*) self, "Loading plugins from %s", _tmp2_, NULL);
#line 35 "/home/test/core/core/plugins.vala"
	_tmp3_ = user_path;
#line 35 "/home/test/core/core/plugins.vala"
	peas_engine_add_search_path ((PeasEngine*) self, _tmp3_, NULL);
#line 36 "/home/test/core/core/plugins.vala"
	_tmp4_ = self->priv->_builtin_path;
#line 36 "/home/test/core/core/plugins.vala"
	midori_loggable_debug ((MidoriLoggable*) self, "Loading plugins from %s", _tmp4_, NULL);
#line 37 "/home/test/core/core/plugins.vala"
	_tmp5_ = self->priv->_builtin_path;
#line 37 "/home/test/core/core/plugins.vala"
	_tmp6_ = user_path;
#line 37 "/home/test/core/core/plugins.vala"
	peas_engine_add_search_path ((PeasEngine*) self, _tmp5_, _tmp6_);
#line 39 "/home/test/core/core/plugins.vala"
	_tmp7_ = midori_core_settings_get_default ();
#line 39 "/home/test/core/core/plugins.vala"
	settings = _tmp7_;
#line 40 "/home/test/core/core/plugins.vala"
	_tmp8_ = peas_engine_get_plugin_list ((PeasEngine*) self);
#line 360 "plugins.c"
	{
		GList* plugin_collection = NULL;
		GList* plugin_it = NULL;
#line 40 "/home/test/core/core/plugins.vala"
		plugin_collection = _tmp8_;
#line 40 "/home/test/core/core/plugins.vala"
		for (plugin_it = plugin_collection; plugin_it != NULL; plugin_it = plugin_it->next) {
#line 368 "plugins.c"
			PeasPluginInfo* _tmp9_;
			PeasPluginInfo* plugin = NULL;
#line 40 "/home/test/core/core/plugins.vala"
			_tmp9_ = __vala_PeasPluginInfo_copy0 ((PeasPluginInfo*) plugin_it->data);
#line 40 "/home/test/core/core/plugins.vala"
			plugin = _tmp9_;
#line 375 "plugins.c"
			{
				PeasPluginInfo* _tmp10_;
				const gchar* _tmp11_;
				gboolean _tmp12_ = FALSE;
				PeasPluginInfo* _tmp13_;
#line 41 "/home/test/core/core/plugins.vala"
				_tmp10_ = plugin;
#line 41 "/home/test/core/core/plugins.vala"
				_tmp11_ = peas_plugin_info_get_name (_tmp10_);
#line 41 "/home/test/core/core/plugins.vala"
				midori_loggable_debug ((MidoriLoggable*) self, "Found plugin %s", _tmp11_, NULL);
#line 42 "/home/test/core/core/plugins.vala"
				_tmp13_ = plugin;
#line 42 "/home/test/core/core/plugins.vala"
				if (peas_plugin_info_is_builtin (_tmp13_)) {
#line 42 "/home/test/core/core/plugins.vala"
					_tmp12_ = TRUE;
#line 393 "plugins.c"
				} else {
					MidoriCoreSettings* _tmp14_;
					PeasPluginInfo* _tmp15_;
					const gchar* _tmp16_;
					gchar* _tmp17_;
					gchar* _tmp18_;
#line 43 "/home/test/core/core/plugins.vala"
					_tmp14_ = settings;
#line 43 "/home/test/core/core/plugins.vala"
					_tmp15_ = plugin;
#line 43 "/home/test/core/core/plugins.vala"
					_tmp16_ = peas_plugin_info_get_module_name (_tmp15_);
#line 43 "/home/test/core/core/plugins.vala"
					_tmp17_ = g_strdup_printf ("lib%s.so", _tmp16_);
#line 43 "/home/test/core/core/plugins.vala"
					_tmp18_ = _tmp17_;
#line 43 "/home/test/core/core/plugins.vala"
					_tmp12_ = midori_core_settings_get_plugin_enabled (_tmp14_, _tmp18_);
#line 43 "/home/test/core/core/plugins.vala"
					_g_free0 (_tmp18_);
#line 414 "plugins.c"
				}
#line 42 "/home/test/core/core/plugins.vala"
				if (_tmp12_) {
#line 418 "plugins.c"
					PeasPluginInfo* _tmp19_;
#line 44 "/home/test/core/core/plugins.vala"
					_tmp19_ = plugin;
#line 44 "/home/test/core/core/plugins.vala"
					if (!peas_engine_load_plugin ((PeasEngine*) self, _tmp19_)) {
#line 424 "plugins.c"
						PeasPluginInfo* _tmp20_;
						const gchar* _tmp21_;
#line 45 "/home/test/core/core/plugins.vala"
						_tmp20_ = plugin;
#line 45 "/home/test/core/core/plugins.vala"
						_tmp21_ = peas_plugin_info_get_module_name (_tmp20_);
#line 45 "/home/test/core/core/plugins.vala"
						g_critical ("plugins.vala:45: Failed to load plugin %s", _tmp21_);
#line 433 "plugins.c"
					}
				}
#line 40 "/home/test/core/core/plugins.vala"
				__vala_PeasPluginInfo_free0 (plugin);
#line 438 "plugins.c"
			}
		}
	}
#line 29 "/home/test/core/core/plugins.vala"
	_g_object_unref0 (settings);
#line 29 "/home/test/core/core/plugins.vala"
	_g_free0 (user_path);
#line 29 "/home/test/core/core/plugins.vala"
	return obj;
#line 448 "plugins.c"
}


static void
midori_plugins_class_init (MidoriPluginsClass * klass)
{
#line 13 "/home/test/core/core/plugins.vala"
	midori_plugins_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/test/core/core/plugins.vala"
	g_type_class_add_private (klass, sizeof (MidoriPluginsPrivate));
#line 13 "/home/test/core/core/plugins.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_midori_plugins_get_property;
#line 13 "/home/test/core/core/plugins.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_midori_plugins_set_property;
#line 13 "/home/test/core/core/plugins.vala"
	G_OBJECT_CLASS (klass)->constructor = midori_plugins_constructor;
#line 13 "/home/test/core/core/plugins.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_plugins_finalize;
#line 13 "/home/test/core/core/plugins.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY, midori_plugins_properties[MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY] = g_param_spec_string ("builtin-path", "builtin-path", "builtin-path", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
#line 469 "plugins.c"
}


static void
midori_plugins_midori_loggable_interface_init (MidoriLoggableIface * iface)
{
#line 13 "/home/test/core/core/plugins.vala"
	midori_plugins_midori_loggable_parent_iface = g_type_interface_peek_parent (iface);
#line 478 "plugins.c"
}


static void
midori_plugins_instance_init (MidoriPlugins * self)
{
#line 13 "/home/test/core/core/plugins.vala"
	self->priv = MIDORI_PLUGINS_GET_PRIVATE (self);
#line 487 "plugins.c"
}


static void
midori_plugins_finalize (GObject * obj)
{
	MidoriPlugins * self;
#line 13 "/home/test/core/core/plugins.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_PLUGINS, MidoriPlugins);
#line 14 "/home/test/core/core/plugins.vala"
	_g_free0 (self->priv->_builtin_path);
#line 13 "/home/test/core/core/plugins.vala"
	G_OBJECT_CLASS (midori_plugins_parent_class)->finalize (obj);
#line 501 "plugins.c"
}


GType
midori_plugins_get_type (void)
{
	static volatile gsize midori_plugins_type_id__volatile = 0;
	if (g_once_init_enter (&midori_plugins_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MidoriPluginsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_plugins_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriPlugins), 0, (GInstanceInitFunc) midori_plugins_instance_init, NULL };
		static const GInterfaceInfo midori_loggable_info = { (GInterfaceInitFunc) midori_plugins_midori_loggable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType midori_plugins_type_id;
		midori_plugins_type_id = g_type_register_static (peas_engine_get_type (), "MidoriPlugins", &g_define_type_info, 0);
		g_type_add_interface_static (midori_plugins_type_id, MIDORI_TYPE_LOGGABLE, &midori_loggable_info);
		g_once_init_leave (&midori_plugins_type_id__volatile, midori_plugins_type_id);
	}
	return midori_plugins_type_id__volatile;
}


static void
_vala_midori_plugins_get_property (GObject * object,
                                   guint property_id,
                                   GValue * value,
                                   GParamSpec * pspec)
{
	MidoriPlugins * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_PLUGINS, MidoriPlugins);
#line 13 "/home/test/core/core/plugins.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/plugins.vala"
		case MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY:
#line 13 "/home/test/core/core/plugins.vala"
		g_value_set_string (value, midori_plugins_get_builtin_path (self));
#line 13 "/home/test/core/core/plugins.vala"
		break;
#line 537 "plugins.c"
		default:
#line 13 "/home/test/core/core/plugins.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/plugins.vala"
		break;
#line 543 "plugins.c"
	}
}


static void
_vala_midori_plugins_set_property (GObject * object,
                                   guint property_id,
                                   const GValue * value,
                                   GParamSpec * pspec)
{
	MidoriPlugins * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_PLUGINS, MidoriPlugins);
#line 13 "/home/test/core/core/plugins.vala"
	switch (property_id) {
#line 13 "/home/test/core/core/plugins.vala"
		case MIDORI_PLUGINS_BUILTIN_PATH_PROPERTY:
#line 13 "/home/test/core/core/plugins.vala"
		midori_plugins_set_builtin_path (self, g_value_get_string (value));
#line 13 "/home/test/core/core/plugins.vala"
		break;
#line 564 "plugins.c"
		default:
#line 13 "/home/test/core/core/plugins.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/core/plugins.vala"
		break;
#line 570 "plugins.c"
	}
}



