/* colorful-tabs.c generated by valac 0.40.23, the Vala compiler
 * generated from colorful-tabs.vala, do not modify */

/*
 Copyright (C) 2009-2018 Christian Dywan <christian@twotoasts.de>
 Copyright (C) 2010 Samuel Creshal <creshal@arcor.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas.h>
#include "midori-core.h"
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define COLORFUL_TABS_TYPE_TINT (colorful_tabs_tint_get_type ())
#define COLORFUL_TABS_TINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COLORFUL_TABS_TYPE_TINT, ColorfulTabsTint))
#define COLORFUL_TABS_TINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), COLORFUL_TABS_TYPE_TINT, ColorfulTabsTintClass))
#define COLORFUL_TABS_IS_TINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COLORFUL_TABS_TYPE_TINT))
#define COLORFUL_TABS_IS_TINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), COLORFUL_TABS_TYPE_TINT))
#define COLORFUL_TABS_TINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), COLORFUL_TABS_TYPE_TINT, ColorfulTabsTintClass))

typedef struct _ColorfulTabsTint ColorfulTabsTint;
typedef struct _ColorfulTabsTintClass ColorfulTabsTintClass;
typedef struct _ColorfulTabsTintPrivate ColorfulTabsTintPrivate;
enum  {
	COLORFUL_TABS_TINT_0_PROPERTY,
	COLORFUL_TABS_TINT_TAB_PROPERTY,
	COLORFUL_TABS_TINT_NUM_PROPERTIES
};
static GParamSpec* colorful_tabs_tint_properties[COLORFUL_TABS_TINT_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ColorfulTabsTint {
	PeasExtensionBase parent_instance;
	ColorfulTabsTintPrivate * priv;
};

struct _ColorfulTabsTintClass {
	PeasExtensionBaseClass parent_class;
};

struct _ColorfulTabsTintPrivate {
	MidoriTab* _tab;
};


static gpointer colorful_tabs_tint_parent_class = NULL;
static MidoriTabActivatableIface * colorful_tabs_tint_midori_tab_activatable_parent_iface = NULL;
static GType colorful_tabs_tint_type_id = 0;

GType colorful_tabs_tint_register_type (GTypeModule * module);
GType colorful_tabs_tint_get_type (void) G_GNUC_CONST;
#define COLORFUL_TABS_TINT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), COLORFUL_TABS_TYPE_TINT, ColorfulTabsTintPrivate))
static void colorful_tabs_tint_real_activate (MidoriTabActivatable* base);
static void colorful_tabs_tint_apply_tint (ColorfulTabsTint* self);
static void _colorful_tabs_tint_apply_tint_g_object_notify (GObject* _sender,
                                                     GParamSpec* pspec,
                                                     gpointer self);
static void __lambda4_ (ColorfulTabsTint* self);
static void ___lambda4__midori_tab_activatable_deactivate (MidoriTabActivatable* _sender,
                                                    gpointer self);
ColorfulTabsTint* colorful_tabs_tint_new (void);
ColorfulTabsTint* colorful_tabs_tint_construct (GType object_type);
static void colorful_tabs_tint_finalize (GObject * obj);
static void _vala_colorful_tabs_tint_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec);
static void _vala_colorful_tabs_tint_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec);
void peas_register_types (GTypeModule* module);
GType colorful_tabs_tint_register_type (GTypeModule * module);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void
_colorful_tabs_tint_apply_tint_g_object_notify (GObject* _sender,
                                                GParamSpec* pspec,
                                                gpointer self)
{
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	colorful_tabs_tint_apply_tint ((ColorfulTabsTint*) self);
#line 104 "colorful-tabs.c"
}


static void
__lambda4_ (ColorfulTabsTint* self)
{
	MidoriTab* _tmp0_;
	MidoriTab* _tmp1_;
	MidoriTab* _tmp2_;
	guint _tmp3_;
	GQuark _tmp4_;
	MidoriTab* _tmp5_;
	MidoriTab* _tmp6_;
	MidoriTab* _tmp7_;
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp0_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp1_ = _tmp0_;
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp2_ = _tmp1_;
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	g_signal_parse_name ("notify::display-uri", G_TYPE_OBJECT, &_tmp3_, &_tmp4_, TRUE);
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	g_signal_handlers_disconnect_matched ((GObject*) _tmp2_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_DETAIL | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp3_, _tmp4_, NULL, (GCallback) _colorful_tabs_tint_apply_tint_g_object_notify, self);
#line 21 "/home/test/core/extensions/colorful-tabs.vala"
	_g_object_unref0 (_tmp2_);
#line 22 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp5_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 22 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp6_ = _tmp5_;
#line 22 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp7_ = _tmp6_;
#line 22 "/home/test/core/extensions/colorful-tabs.vala"
	midori_tab_set_color (_tmp7_, NULL);
#line 22 "/home/test/core/extensions/colorful-tabs.vala"
	_g_object_unref0 (_tmp7_);
#line 141 "colorful-tabs.c"
}


static void
___lambda4__midori_tab_activatable_deactivate (MidoriTabActivatable* _sender,
                                               gpointer self)
{
#line 20 "/home/test/core/extensions/colorful-tabs.vala"
	__lambda4_ ((ColorfulTabsTint*) self);
#line 151 "colorful-tabs.c"
}


static void
colorful_tabs_tint_real_activate (MidoriTabActivatable* base)
{
	ColorfulTabsTint * self;
	MidoriTab* _tmp0_;
	MidoriTab* _tmp1_;
	MidoriTab* _tmp2_;
#line 17 "/home/test/core/extensions/colorful-tabs.vala"
	self = (ColorfulTabsTint*) base;
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp0_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp1_ = _tmp0_;
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp2_ = _tmp1_;
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	g_signal_connect_object ((GObject*) _tmp2_, "notify::display-uri", (GCallback) _colorful_tabs_tint_apply_tint_g_object_notify, self, 0);
#line 18 "/home/test/core/extensions/colorful-tabs.vala"
	_g_object_unref0 (_tmp2_);
#line 19 "/home/test/core/extensions/colorful-tabs.vala"
	colorful_tabs_tint_apply_tint (self);
#line 20 "/home/test/core/extensions/colorful-tabs.vala"
	g_signal_connect_object ((MidoriTabActivatable*) self, "deactivate", (GCallback) ___lambda4__midori_tab_activatable_deactivate, self, 0);
#line 178 "colorful-tabs.c"
}


static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gboolean result = FALSE;
	gchar* _tmp0_;
#line 1475 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1475 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1476 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 198 "colorful-tabs.c"
}


static const gchar*
string_offset (const gchar* self,
               glong offset)
{
	const gchar* result = NULL;
#line 1219 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1220 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = (const gchar*) (((gchar*) self) + offset);
#line 1220 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 213 "colorful-tabs.c"
}


static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
#line 1392 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1392 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	end = _tmp0_;
#line 1393 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1_ = end;
#line 1393 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1394 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		result = maxlen;
#line 1394 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		return result;
#line 237 "colorful-tabs.c"
	} else {
		gchar* _tmp2_;
#line 1396 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp2_ = end;
#line 1396 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1396 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		return result;
#line 246 "colorful-tabs.c"
	}
}


static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp6_;
	gchar* _tmp7_;
#line 1403 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1405 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1405 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 267 "colorful-tabs.c"
	} else {
#line 1405 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 271 "colorful-tabs.c"
	}
#line 1405 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (_tmp0_) {
#line 1407 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 277 "colorful-tabs.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1409 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1409 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1409 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 287 "colorful-tabs.c"
	}
#line 1412 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 291 "colorful-tabs.c"
		glong _tmp3_;
#line 1413 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp3_ = string_length;
#line 1413 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		offset = _tmp3_ + offset;
#line 1414 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 299 "colorful-tabs.c"
	} else {
		glong _tmp4_;
#line 1416 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp4_ = string_length;
#line 1416 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		g_return_val_if_fail (offset <= _tmp4_, NULL);
#line 306 "colorful-tabs.c"
	}
#line 1418 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 310 "colorful-tabs.c"
		glong _tmp5_;
#line 1419 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		_tmp5_ = string_length;
#line 1419 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
		len = _tmp5_ - offset;
#line 316 "colorful-tabs.c"
	}
#line 1421 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp6_ = string_length;
#line 1421 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= _tmp6_, NULL);
#line 1422 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp7_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1422 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = _tmp7_;
#line 1422 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 328 "colorful-tabs.c"
}


static void
colorful_tabs_tint_apply_tint (ColorfulTabsTint* self)
{
	MidoriTab* _tmp0_;
	MidoriTab* _tmp1_;
	MidoriTab* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	gboolean _tmp5_;
#line 26 "/home/test/core/extensions/colorful-tabs.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp0_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp1_ = _tmp0_;
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp2_ = _tmp1_;
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp3_ = midori_tab_get_display_uri (_tmp2_);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp4_ = _tmp3_;
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp5_ = string_contains (_tmp4_, "://");
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	_g_object_unref0 (_tmp2_);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
	if (_tmp5_) {
#line 359 "colorful-tabs.c"
		GdkColor color = {0};
		gchar* hostname = NULL;
		MidoriTab* _tmp6_;
		MidoriTab* _tmp7_;
		MidoriTab* _tmp8_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		gchar** _tmp13_;
		gchar** _tmp14_;
		gchar** _tmp15_;
		gint _tmp15__length1;
		const gchar* _tmp16_;
		gchar* _tmp17_;
		gchar* _tmp18_;
		gchar* hash = NULL;
		const gchar* _tmp19_;
		gchar* _tmp20_;
		const gchar* _tmp21_;
		gchar* _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		GdkColor _tmp26_ = {0};
		guint16 grey = 0U;
		guint16 adjustment = 0U;
		guint16 blue = 0U;
		guint16 extra = 0U;
		gboolean _tmp27_ = FALSE;
		gboolean _tmp28_ = FALSE;
		GdkColor _tmp29_;
		guint16 _tmp30_;
		guint16 _tmp31_;
		guint16 _tmp44_ = 0U;
		GdkColor _tmp45_;
		guint16 _tmp46_;
		guint16 _tmp47_;
		guint16 _tmp52_ = 0U;
		GdkColor _tmp53_;
		guint16 _tmp54_;
		guint16 _tmp55_;
		guint16 _tmp60_ = 0U;
		GdkColor _tmp61_;
		guint16 _tmp62_;
		guint16 _tmp63_;
		MidoriTab* _tmp68_;
		MidoriTab* _tmp69_;
		MidoriTab* _tmp70_;
		gchar* _tmp71_;
		gchar* _tmp72_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp6_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp7_ = _tmp6_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp8_ = _tmp7_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp9_ = midori_tab_get_display_uri (_tmp8_);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp10_ = _tmp9_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp11_ = g_utf8_strchr (_tmp10_, (gssize) -1, (gunichar) '/');
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp12_ = string_offset (_tmp11_, (glong) 2);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, "/", 0);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp15_ = _tmp14_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp15__length1 = _vala_array_length (_tmp13_);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp16_ = _tmp15_[0];
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp17_ = g_strdup (_tmp16_);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp18_ = _tmp17_;
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		_g_object_unref0 (_tmp8_);
#line 30 "/home/test/core/extensions/colorful-tabs.vala"
		hostname = _tmp18_;
#line 31 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp19_ = hostname;
#line 31 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp20_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, _tmp19_, (gsize) 1);
#line 31 "/home/test/core/extensions/colorful-tabs.vala"
		hash = _tmp20_;
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp21_ = hash;
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp22_ = string_substring (_tmp21_, (glong) 0, (glong) 6);
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp23_ = _tmp22_;
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp24_ = g_strconcat ("#", _tmp23_, NULL);
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp25_ = _tmp24_;
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		gdk_color_parse (_tmp25_, &_tmp26_);
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		color = _tmp26_;
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_g_free0 (_tmp25_);
#line 32 "/home/test/core/extensions/colorful-tabs.vala"
		_g_free0 (_tmp23_);
#line 34 "/home/test/core/extensions/colorful-tabs.vala"
		grey = (guint16) (137 * 255);
#line 35 "/home/test/core/extensions/colorful-tabs.vala"
		adjustment = (guint16) (78 * 255);
#line 36 "/home/test/core/extensions/colorful-tabs.vala"
		blue = (guint16) (39 * 255);
#line 37 "/home/test/core/extensions/colorful-tabs.vala"
		extra = (guint16) (19 * 255);
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp29_ = color;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp30_ = _tmp29_.red;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp31_ = grey;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp30_ < _tmp31_) {
#line 483 "colorful-tabs.c"
			GdkColor _tmp32_;
			guint16 _tmp33_;
			guint16 _tmp34_;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp32_ = color;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp33_ = _tmp32_.green;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp34_ = grey;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp28_ = _tmp33_ < _tmp34_;
#line 495 "colorful-tabs.c"
		} else {
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp28_ = FALSE;
#line 499 "colorful-tabs.c"
		}
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp28_) {
#line 503 "colorful-tabs.c"
			GdkColor _tmp35_;
			guint16 _tmp36_;
			guint16 _tmp37_;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp35_ = color;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp36_ = _tmp35_.blue;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp37_ = grey;
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp27_ = _tmp36_ < _tmp37_;
#line 515 "colorful-tabs.c"
		} else {
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp27_ = FALSE;
#line 519 "colorful-tabs.c"
		}
#line 38 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp27_) {
#line 523 "colorful-tabs.c"
			guint16 _tmp38_;
			guint16 _tmp39_;
			guint16 _tmp40_;
			guint16 _tmp41_;
			guint16 _tmp42_;
			guint16 _tmp43_;
#line 39 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp38_ = color.red;
#line 39 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp39_ = adjustment;
#line 39 "/home/test/core/extensions/colorful-tabs.vala"
			color.red = _tmp38_ + _tmp39_;
#line 40 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp40_ = color.green;
#line 40 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp41_ = adjustment;
#line 40 "/home/test/core/extensions/colorful-tabs.vala"
			color.green = _tmp40_ + _tmp41_;
#line 41 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp42_ = color.blue;
#line 41 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp43_ = adjustment;
#line 41 "/home/test/core/extensions/colorful-tabs.vala"
			color.blue = _tmp42_ + _tmp43_;
#line 548 "colorful-tabs.c"
		}
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp45_ = color;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp46_ = _tmp45_.red;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp47_ = blue;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp46_ < _tmp47_) {
#line 558 "colorful-tabs.c"
			guint16 _tmp48_;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp48_ = extra;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp44_ = _tmp48_;
#line 564 "colorful-tabs.c"
		} else {
			GdkColor _tmp49_;
			guint16 _tmp50_;
			guint16 _tmp51_;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp49_ = color;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp50_ = _tmp49_.red;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp51_ = extra;
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp44_ = _tmp50_ - _tmp51_;
#line 577 "colorful-tabs.c"
		}
#line 43 "/home/test/core/extensions/colorful-tabs.vala"
		color.red = _tmp44_;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp53_ = color;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp54_ = _tmp53_.blue;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp55_ = blue;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp54_ < _tmp55_) {
#line 589 "colorful-tabs.c"
			guint16 _tmp56_;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp56_ = extra;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp52_ = _tmp56_;
#line 595 "colorful-tabs.c"
		} else {
			GdkColor _tmp57_;
			guint16 _tmp58_;
			guint16 _tmp59_;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp57_ = color;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp58_ = _tmp57_.blue;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp59_ = extra;
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp52_ = _tmp58_ - _tmp59_;
#line 608 "colorful-tabs.c"
		}
#line 44 "/home/test/core/extensions/colorful-tabs.vala"
		color.blue = _tmp52_;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp61_ = color;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp62_ = _tmp61_.green;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp63_ = blue;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
		if (_tmp62_ < _tmp63_) {
#line 620 "colorful-tabs.c"
			guint16 _tmp64_;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp64_ = extra;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp60_ = _tmp64_;
#line 626 "colorful-tabs.c"
		} else {
			GdkColor _tmp65_;
			guint16 _tmp66_;
			guint16 _tmp67_;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp65_ = color;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp66_ = _tmp65_.green;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp67_ = extra;
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
			_tmp60_ = _tmp66_ - _tmp67_;
#line 639 "colorful-tabs.c"
		}
#line 45 "/home/test/core/extensions/colorful-tabs.vala"
		color.green = _tmp60_;
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp68_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp69_ = _tmp68_;
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp70_ = _tmp69_;
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp71_ = gdk_color_to_string (&color);
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp72_ = _tmp71_;
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		midori_tab_set_color (_tmp70_, _tmp72_);
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_g_free0 (_tmp72_);
#line 46 "/home/test/core/extensions/colorful-tabs.vala"
		_g_object_unref0 (_tmp70_);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
		_g_free0 (hash);
#line 27 "/home/test/core/extensions/colorful-tabs.vala"
		_g_free0 (hostname);
#line 663 "colorful-tabs.c"
	} else {
		MidoriTab* _tmp73_;
		MidoriTab* _tmp74_;
		MidoriTab* _tmp75_;
#line 48 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp73_ = midori_tab_activatable_get_tab ((MidoriTabActivatable*) self);
#line 48 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp74_ = _tmp73_;
#line 48 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp75_ = _tmp74_;
#line 48 "/home/test/core/extensions/colorful-tabs.vala"
		midori_tab_set_color (_tmp75_, NULL);
#line 48 "/home/test/core/extensions/colorful-tabs.vala"
		_g_object_unref0 (_tmp75_);
#line 678 "colorful-tabs.c"
	}
}


ColorfulTabsTint*
colorful_tabs_tint_construct (GType object_type)
{
	ColorfulTabsTint * self = NULL;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	self = (ColorfulTabsTint*) g_object_new (object_type, NULL);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	return self;
#line 691 "colorful-tabs.c"
}


ColorfulTabsTint*
colorful_tabs_tint_new (void)
{
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	return colorful_tabs_tint_construct (COLORFUL_TABS_TYPE_TINT);
#line 700 "colorful-tabs.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	return self ? g_object_ref (self) : NULL;
#line 709 "colorful-tabs.c"
}


static MidoriTab*
colorful_tabs_tint_real_get_tab (MidoriTabActivatable* base)
{
	MidoriTab* result;
	ColorfulTabsTint* self;
	MidoriTab* _tmp0_;
	MidoriTab* _tmp1_;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	self = (ColorfulTabsTint*) base;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp0_ = self->priv->_tab;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	result = _tmp1_;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	return result;
#line 730 "colorful-tabs.c"
}


static void
colorful_tabs_tint_real_set_tab (MidoriTabActivatable* base,
                                 MidoriTab* value)
{
	ColorfulTabsTint* self;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	self = (ColorfulTabsTint*) base;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	if (colorful_tabs_tint_real_get_tab (base) != value) {
#line 743 "colorful-tabs.c"
		MidoriTab* _tmp0_;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
		_g_object_unref0 (self->priv->_tab);
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
		self->priv->_tab = _tmp0_;
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
		g_object_notify_by_pspec ((GObject *) self, colorful_tabs_tint_properties[COLORFUL_TABS_TINT_TAB_PROPERTY]);
#line 753 "colorful-tabs.c"
	}
}


static void
colorful_tabs_tint_class_init (ColorfulTabsTintClass * klass)
{
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	colorful_tabs_tint_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	g_type_class_add_private (klass, sizeof (ColorfulTabsTintPrivate));
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_colorful_tabs_tint_get_property;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_colorful_tabs_tint_set_property;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	G_OBJECT_CLASS (klass)->finalize = colorful_tabs_tint_finalize;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), COLORFUL_TABS_TINT_TAB_PROPERTY, colorful_tabs_tint_properties[COLORFUL_TABS_TINT_TAB_PROPERTY] = g_param_spec_object ("tab", "tab", "tab", MIDORI_TYPE_TAB, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 773 "colorful-tabs.c"
}


static void
colorful_tabs_tint_midori_tab_activatable_interface_init (MidoriTabActivatableIface * iface)
{
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	colorful_tabs_tint_midori_tab_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	iface->activate = (void (*) (MidoriTabActivatable*)) colorful_tabs_tint_real_activate;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	iface->get_tab = colorful_tabs_tint_real_get_tab;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	iface->set_tab = colorful_tabs_tint_real_set_tab;
#line 788 "colorful-tabs.c"
}


static void
colorful_tabs_tint_instance_init (ColorfulTabsTint * self)
{
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	self->priv = COLORFUL_TABS_TINT_GET_PRIVATE (self);
#line 797 "colorful-tabs.c"
}


static void
colorful_tabs_tint_finalize (GObject * obj)
{
	ColorfulTabsTint * self;
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, COLORFUL_TABS_TYPE_TINT, ColorfulTabsTint);
#line 15 "/home/test/core/extensions/colorful-tabs.vala"
	_g_object_unref0 (self->priv->_tab);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	G_OBJECT_CLASS (colorful_tabs_tint_parent_class)->finalize (obj);
#line 811 "colorful-tabs.c"
}


GType
colorful_tabs_tint_get_type (void)
{
	return colorful_tabs_tint_type_id;
}


GType
colorful_tabs_tint_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (ColorfulTabsTintClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) colorful_tabs_tint_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ColorfulTabsTint), 0, (GInstanceInitFunc) colorful_tabs_tint_instance_init, NULL };
	static const GInterfaceInfo midori_tab_activatable_info = { (GInterfaceInitFunc) colorful_tabs_tint_midori_tab_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	colorful_tabs_tint_type_id = g_type_module_register_type (module, peas_extension_base_get_type (), "ColorfulTabsTint", &g_define_type_info, 0);
	g_type_module_add_interface (module, colorful_tabs_tint_type_id, MIDORI_TYPE_TAB_ACTIVATABLE, &midori_tab_activatable_info);
	return colorful_tabs_tint_type_id;
}


static void
_vala_colorful_tabs_tint_get_property (GObject * object,
                                       guint property_id,
                                       GValue * value,
                                       GParamSpec * pspec)
{
	ColorfulTabsTint * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, COLORFUL_TABS_TYPE_TINT, ColorfulTabsTint);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	switch (property_id) {
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		case COLORFUL_TABS_TINT_TAB_PROPERTY:
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		g_value_take_object (value, midori_tab_activatable_get_tab ((MidoriTabActivatable*) self));
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		break;
#line 849 "colorful-tabs.c"
		default:
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		break;
#line 855 "colorful-tabs.c"
	}
}


static void
_vala_colorful_tabs_tint_set_property (GObject * object,
                                       guint property_id,
                                       const GValue * value,
                                       GParamSpec * pspec)
{
	ColorfulTabsTint * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, COLORFUL_TABS_TYPE_TINT, ColorfulTabsTint);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
	switch (property_id) {
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		case COLORFUL_TABS_TINT_TAB_PROPERTY:
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		midori_tab_activatable_set_tab ((MidoriTabActivatable*) self, g_value_get_object (value));
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		break;
#line 876 "colorful-tabs.c"
		default:
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 14 "/home/test/core/extensions/colorful-tabs.vala"
		break;
#line 882 "colorful-tabs.c"
	}
}


void
peas_register_types (GTypeModule* module)
{
#line 55 "/home/test/core/extensions/colorful-tabs.vala"
	g_return_if_fail (module != NULL);
#line 55 "/home/test/core/extensions/colorful-tabs.vala"
	colorful_tabs_tint_register_type (module);
#line 56 "/home/test/core/extensions/colorful-tabs.vala"
	peas_object_module_register_extension_type (G_TYPE_CHECK_INSTANCE_CAST (module, peas_object_module_get_type (), PeasObjectModule), MIDORI_TYPE_TAB_ACTIVATABLE, COLORFUL_TABS_TYPE_TINT);
#line 896 "colorful-tabs.c"
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint
_vala_array_length (gpointer array)
{
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



