/* new.c generated by valac 0.40.23, the Vala compiler
 * generated from new.vala, do not modify */

/*
 Copyright (C) 2013-2018 Christian Dywan <christian@twotoats.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "midori-core.h"
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <libpeas/peas.h>


#define MIDORI_TYPE_BUTTON (midori_button_get_type ())
#define MIDORI_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_BUTTON, MidoriButton))
#define MIDORI_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_BUTTON, MidoriButtonClass))
#define MIDORI_IS_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_BUTTON))
#define MIDORI_IS_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_BUTTON))
#define MIDORI_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_BUTTON, MidoriButtonClass))

typedef struct _MidoriButton MidoriButton;
typedef struct _MidoriButtonClass MidoriButtonClass;
typedef struct _MidoriButtonPrivate MidoriButtonPrivate;
enum  {
	MIDORI_BUTTON_0_PROPERTY,
	MIDORI_BUTTON_NUM_PROPERTIES
};
static GParamSpec* midori_button_properties[MIDORI_BUTTON_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
enum  {
	MIDORI_BUTTON_OPEN_CONFIG_SIGNAL,
	MIDORI_BUTTON_NUM_SIGNALS
};
static guint midori_button_signals[MIDORI_BUTTON_NUM_SIGNALS] = {0};

#define MIDORI_TYPE_FRONTEND (midori_frontend_get_type ())
#define MIDORI_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MIDORI_TYPE_FRONTEND, MidoriFrontend))
#define MIDORI_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MIDORI_TYPE_FRONTEND, MidoriFrontendClass))
#define MIDORI_IS_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MIDORI_TYPE_FRONTEND))
#define MIDORI_IS_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MIDORI_TYPE_FRONTEND))
#define MIDORI_FRONTEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MIDORI_TYPE_FRONTEND, MidoriFrontendClass))

typedef struct _MidoriFrontend MidoriFrontend;
typedef struct _MidoriFrontendClass MidoriFrontendClass;
typedef struct _MidoriFrontendPrivate MidoriFrontendPrivate;
enum  {
	MIDORI_FRONTEND_0_PROPERTY,
	MIDORI_FRONTEND_BROWSER_PROPERTY,
	MIDORI_FRONTEND_NUM_PROPERTIES
};
static GParamSpec* midori_frontend_properties[MIDORI_FRONTEND_NUM_PROPERTIES];

struct _MidoriButton {
	GtkButton parent_instance;
	MidoriButtonPrivate * priv;
};

struct _MidoriButtonClass {
	GtkButtonClass parent_class;
	void (*open_config) (MidoriButton* self);
};

struct _MidoriButtonPrivate {
	GtkPopover* popover;
	GtkSwitch* switch1;
	GtkSwitch* switch2;
	GtkSwitch* switch3;
	GtkSwitch* switch4;
	gboolean active1;
	gboolean active2;
	gboolean active3;
	gboolean active4;
	gboolean all_active;
	MidoriBrowser* browser;
};

struct _MidoriFrontend {
	GObject parent_instance;
	MidoriFrontendPrivate * priv;
};

struct _MidoriFrontendClass {
	GObjectClass parent_class;
};

struct _MidoriFrontendPrivate {
	MidoriBrowser* _browser;
};


static gpointer midori_button_parent_class = NULL;
static GType midori_button_type_id = 0;
static gpointer midori_frontend_parent_class = NULL;
static MidoriBrowserActivatableIface * midori_frontend_midori_browser_activatable_parent_iface = NULL;
static GType midori_frontend_type_id = 0;

GType midori_button_register_type (GTypeModule * module);
GType midori_button_get_type (void) G_GNUC_CONST;
#define MIDORI_BUTTON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_BUTTON, MidoriButtonPrivate))
MidoriButton* midori_button_new (MidoriBrowser* browser);
MidoriButton* midori_button_construct (GType object_type,
                                       MidoriBrowser* browser);
static void midori_button_config_activated (MidoriButton* self);
static void _midori_button_config_activated_g_simple_action_activate (GSimpleAction* _sender,
                                                               GVariant* parameter,
                                                               gpointer self);
static void midori_button_switcher_activated (MidoriButton* self,
                                       GObject* switcher,
                                       GParamSpec* pspec);
static void midori_button_exec_program_async (MidoriButton* self,
                                       gchar** spawn_args,
                                       int spawn_args_length1);
static gboolean midori_button_spawn_option (MidoriButton* self);
static gboolean midori_button_spawn_warning (MidoriButton* self,
                                      const gchar* str);
static void midori_button_real_open_config (MidoriButton* self);
static GObject * midori_button_constructor (GType type,
                                     guint n_construct_properties,
                                     GObjectConstructParam * construct_properties);
static void _midori_button_switcher_activated_g_object_notify (GObject* _sender,
                                                        GParamSpec* pspec,
                                                        gpointer self);
static void midori_button_finalize (GObject * obj);
GType midori_frontend_register_type (GTypeModule * module);
GType midori_frontend_get_type (void) G_GNUC_CONST;
#define MIDORI_FRONTEND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MIDORI_TYPE_FRONTEND, MidoriFrontendPrivate))
static void midori_frontend_real_activate (MidoriBrowserActivatable* base);
MidoriFrontend* midori_frontend_new (void);
MidoriFrontend* midori_frontend_construct (GType object_type);
static void midori_frontend_finalize (GObject * obj);
static void _vala_midori_frontend_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec);
static void _vala_midori_frontend_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec);
void peas_register_types (GTypeModule* module);
GType midori_button_register_type (GTypeModule * module);
GType midori_frontend_register_type (GTypeModule * module);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer
_g_object_ref0 (gpointer self)
{
#line 48 "/home/test/core/extensions/new.vala"
	return self ? g_object_ref (self) : NULL;
#line 171 "new.c"
}


static void
_midori_button_config_activated_g_simple_action_activate (GSimpleAction* _sender,
                                                          GVariant* parameter,
                                                          gpointer self)
{
#line 51 "/home/test/core/extensions/new.vala"
	midori_button_config_activated ((MidoriButton*) self);
#line 182 "new.c"
}


MidoriButton*
midori_button_construct (GType object_type,
                         MidoriBrowser* browser)
{
	MidoriButton * self = NULL;
	MidoriBrowser* _tmp0_;
	GSimpleAction* action = NULL;
	GSimpleAction* _tmp1_;
#line 47 "/home/test/core/extensions/new.vala"
	g_return_val_if_fail (browser != NULL, NULL);
#line 47 "/home/test/core/extensions/new.vala"
	self = (MidoriButton*) g_object_new (object_type, NULL);
#line 48 "/home/test/core/extensions/new.vala"
	_tmp0_ = _g_object_ref0 (browser);
#line 48 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->browser);
#line 48 "/home/test/core/extensions/new.vala"
	self->priv->browser = _tmp0_;
#line 50 "/home/test/core/extensions/new.vala"
	_tmp1_ = g_simple_action_new ("open-config", NULL);
#line 50 "/home/test/core/extensions/new.vala"
	action = _tmp1_;
#line 51 "/home/test/core/extensions/new.vala"
	g_signal_connect_object (action, "activate", (GCallback) _midori_button_config_activated_g_simple_action_activate, self, 0);
#line 52 "/home/test/core/extensions/new.vala"
	g_action_map_add_action ((GActionMap*) browser, (GAction*) action);
#line 47 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (action);
#line 47 "/home/test/core/extensions/new.vala"
	return self;
#line 216 "new.c"
}


MidoriButton*
midori_button_new (MidoriBrowser* browser)
{
#line 47 "/home/test/core/extensions/new.vala"
	return midori_button_construct (MIDORI_TYPE_BUTTON, browser);
#line 225 "new.c"
}


static void
midori_button_config_activated (MidoriButton* self)
{
#line 55 "/home/test/core/extensions/new.vala"
	g_return_if_fail (self != NULL);
#line 56 "/home/test/core/extensions/new.vala"
	g_signal_emit (self, midori_button_signals[MIDORI_BUTTON_OPEN_CONFIG_SIGNAL], 0);
#line 236 "new.c"
}


static void
midori_button_switcher_activated (MidoriButton* self,
                                  GObject* switcher,
                                  GParamSpec* pspec)
{
#line 59 "/home/test/core/extensions/new.vala"
	g_return_if_fail (self != NULL);
#line 59 "/home/test/core/extensions/new.vala"
	g_return_if_fail (switcher != NULL);
#line 59 "/home/test/core/extensions/new.vala"
	g_return_if_fail (pspec != NULL);
#line 60 "/home/test/core/extensions/new.vala"
	if (gtk_switch_get_active (G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL)) {
#line 253 "new.c"
		gboolean _tmp0_ = FALSE;
		GtkSwitch* _tmp1_;
#line 61 "/home/test/core/extensions/new.vala"
		_tmp1_ = self->priv->switch1;
#line 61 "/home/test/core/extensions/new.vala"
		if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp1_) {
#line 260 "new.c"
			gboolean _tmp2_;
#line 61 "/home/test/core/extensions/new.vala"
			_tmp2_ = self->priv->active1;
#line 61 "/home/test/core/extensions/new.vala"
			_tmp0_ = !_tmp2_;
#line 266 "new.c"
		} else {
#line 61 "/home/test/core/extensions/new.vala"
			_tmp0_ = FALSE;
#line 270 "new.c"
		}
#line 61 "/home/test/core/extensions/new.vala"
		if (_tmp0_) {
#line 274 "new.c"
			gchar* _tmp3_;
			gchar* _tmp4_;
			gchar* _tmp5_;
			gchar** _tmp6_;
			gchar** _tmp7_;
			gint _tmp7__length1;
			gboolean _tmp8_ = FALSE;
			gboolean _tmp9_ = FALSE;
			gboolean _tmp10_;
#line 62 "/home/test/core/extensions/new.vala"
			_tmp3_ = g_strdup ("python3");
#line 62 "/home/test/core/extensions/new.vala"
			_tmp4_ = g_strdup ("-c");
#line 62 "/home/test/core/extensions/new.vala"
			_tmp5_ = g_strdup ("from os import system;system('tshark -i enp0s3 -F pcapng -w out 2>/dev" \
"/null</dev/null &')");
#line 62 "/home/test/core/extensions/new.vala"
			_tmp6_ = g_new0 (gchar*, 3 + 1);
#line 62 "/home/test/core/extensions/new.vala"
			_tmp6_[0] = _tmp3_;
#line 62 "/home/test/core/extensions/new.vala"
			_tmp6_[1] = _tmp4_;
#line 62 "/home/test/core/extensions/new.vala"
			_tmp6_[2] = _tmp5_;
#line 62 "/home/test/core/extensions/new.vala"
			_tmp7_ = _tmp6_;
#line 62 "/home/test/core/extensions/new.vala"
			_tmp7__length1 = 3;
#line 62 "/home/test/core/extensions/new.vala"
			midori_button_exec_program_async (self, _tmp7_, 3);
#line 62 "/home/test/core/extensions/new.vala"
			_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
#line 63 "/home/test/core/extensions/new.vala"
			self->priv->active1 = TRUE;
#line 64 "/home/test/core/extensions/new.vala"
			_tmp10_ = self->priv->active1;
#line 64 "/home/test/core/extensions/new.vala"
			if (_tmp10_) {
#line 312 "new.c"
				gboolean _tmp11_;
#line 64 "/home/test/core/extensions/new.vala"
				_tmp11_ = self->priv->active2;
#line 64 "/home/test/core/extensions/new.vala"
				_tmp9_ = _tmp11_;
#line 318 "new.c"
			} else {
#line 64 "/home/test/core/extensions/new.vala"
				_tmp9_ = FALSE;
#line 322 "new.c"
			}
#line 64 "/home/test/core/extensions/new.vala"
			if (_tmp9_) {
#line 326 "new.c"
				gboolean _tmp12_;
#line 64 "/home/test/core/extensions/new.vala"
				_tmp12_ = self->priv->active3;
#line 64 "/home/test/core/extensions/new.vala"
				_tmp8_ = _tmp12_;
#line 332 "new.c"
			} else {
#line 64 "/home/test/core/extensions/new.vala"
				_tmp8_ = FALSE;
#line 336 "new.c"
			}
#line 64 "/home/test/core/extensions/new.vala"
			if (_tmp8_) {
#line 340 "new.c"
				GtkSwitch* _tmp13_;
#line 65 "/home/test/core/extensions/new.vala"
				self->priv->all_active = TRUE;
#line 66 "/home/test/core/extensions/new.vala"
				_tmp13_ = self->priv->switch4;
#line 66 "/home/test/core/extensions/new.vala"
				gtk_switch_set_active (_tmp13_, TRUE);
#line 348 "new.c"
			}
		} else {
			gboolean _tmp14_ = FALSE;
			GtkSwitch* _tmp15_;
#line 69 "/home/test/core/extensions/new.vala"
			_tmp15_ = self->priv->switch2;
#line 69 "/home/test/core/extensions/new.vala"
			if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp15_) {
#line 357 "new.c"
				gboolean _tmp16_;
#line 69 "/home/test/core/extensions/new.vala"
				_tmp16_ = self->priv->active2;
#line 69 "/home/test/core/extensions/new.vala"
				_tmp14_ = !_tmp16_;
#line 363 "new.c"
			} else {
#line 69 "/home/test/core/extensions/new.vala"
				_tmp14_ = FALSE;
#line 367 "new.c"
			}
#line 69 "/home/test/core/extensions/new.vala"
			if (_tmp14_) {
#line 371 "new.c"
				gboolean _tmp17_ = FALSE;
				gboolean _tmp18_ = FALSE;
				gboolean _tmp19_;
#line 70 "/home/test/core/extensions/new.vala"
				g_print ("Avvio estrazione codice sorgente\n");
#line 71 "/home/test/core/extensions/new.vala"
				self->priv->active2 = TRUE;
#line 72 "/home/test/core/extensions/new.vala"
				_tmp19_ = self->priv->active1;
#line 72 "/home/test/core/extensions/new.vala"
				if (_tmp19_) {
#line 383 "new.c"
					gboolean _tmp20_;
#line 72 "/home/test/core/extensions/new.vala"
					_tmp20_ = self->priv->active2;
#line 72 "/home/test/core/extensions/new.vala"
					_tmp18_ = _tmp20_;
#line 389 "new.c"
				} else {
#line 72 "/home/test/core/extensions/new.vala"
					_tmp18_ = FALSE;
#line 393 "new.c"
				}
#line 72 "/home/test/core/extensions/new.vala"
				if (_tmp18_) {
#line 397 "new.c"
					gboolean _tmp21_;
#line 72 "/home/test/core/extensions/new.vala"
					_tmp21_ = self->priv->active3;
#line 72 "/home/test/core/extensions/new.vala"
					_tmp17_ = _tmp21_;
#line 403 "new.c"
				} else {
#line 72 "/home/test/core/extensions/new.vala"
					_tmp17_ = FALSE;
#line 407 "new.c"
				}
#line 72 "/home/test/core/extensions/new.vala"
				if (_tmp17_) {
#line 411 "new.c"
					GtkSwitch* _tmp22_;
#line 73 "/home/test/core/extensions/new.vala"
					self->priv->all_active = TRUE;
#line 74 "/home/test/core/extensions/new.vala"
					_tmp22_ = self->priv->switch4;
#line 74 "/home/test/core/extensions/new.vala"
					gtk_switch_set_active (_tmp22_, TRUE);
#line 419 "new.c"
				}
			} else {
				gboolean _tmp23_ = FALSE;
				GtkSwitch* _tmp24_;
#line 77 "/home/test/core/extensions/new.vala"
				_tmp24_ = self->priv->switch3;
#line 77 "/home/test/core/extensions/new.vala"
				if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp24_) {
#line 428 "new.c"
					gboolean _tmp25_;
#line 77 "/home/test/core/extensions/new.vala"
					_tmp25_ = self->priv->active3;
#line 77 "/home/test/core/extensions/new.vala"
					_tmp23_ = !_tmp25_;
#line 434 "new.c"
				} else {
#line 77 "/home/test/core/extensions/new.vala"
					_tmp23_ = FALSE;
#line 438 "new.c"
				}
#line 77 "/home/test/core/extensions/new.vala"
				if (_tmp23_) {
#line 442 "new.c"
					gboolean _tmp26_ = FALSE;
					gboolean _tmp27_ = FALSE;
					gboolean _tmp28_;
#line 78 "/home/test/core/extensions/new.vala"
					if (midori_button_spawn_option (self)) {
#line 79 "/home/test/core/extensions/new.vala"
						g_print ("Avvio registrazione con suoni ambientali\n");
#line 450 "new.c"
					} else {
#line 81 "/home/test/core/extensions/new.vala"
						g_print ("Avvio registrazione senza suoni ambientali\n");
#line 454 "new.c"
					}
#line 82 "/home/test/core/extensions/new.vala"
					self->priv->active3 = TRUE;
#line 83 "/home/test/core/extensions/new.vala"
					_tmp28_ = self->priv->active1;
#line 83 "/home/test/core/extensions/new.vala"
					if (_tmp28_) {
#line 462 "new.c"
						gboolean _tmp29_;
#line 83 "/home/test/core/extensions/new.vala"
						_tmp29_ = self->priv->active2;
#line 83 "/home/test/core/extensions/new.vala"
						_tmp27_ = _tmp29_;
#line 468 "new.c"
					} else {
#line 83 "/home/test/core/extensions/new.vala"
						_tmp27_ = FALSE;
#line 472 "new.c"
					}
#line 83 "/home/test/core/extensions/new.vala"
					if (_tmp27_) {
#line 476 "new.c"
						gboolean _tmp30_;
#line 83 "/home/test/core/extensions/new.vala"
						_tmp30_ = self->priv->active3;
#line 83 "/home/test/core/extensions/new.vala"
						_tmp26_ = _tmp30_;
#line 482 "new.c"
					} else {
#line 83 "/home/test/core/extensions/new.vala"
						_tmp26_ = FALSE;
#line 486 "new.c"
					}
#line 83 "/home/test/core/extensions/new.vala"
					if (_tmp26_) {
#line 490 "new.c"
						GtkSwitch* _tmp31_;
#line 84 "/home/test/core/extensions/new.vala"
						self->priv->all_active = TRUE;
#line 85 "/home/test/core/extensions/new.vala"
						_tmp31_ = self->priv->switch4;
#line 85 "/home/test/core/extensions/new.vala"
						gtk_switch_set_active (_tmp31_, TRUE);
#line 498 "new.c"
					}
				} else {
					gboolean _tmp32_ = FALSE;
					GtkSwitch* _tmp33_;
#line 88 "/home/test/core/extensions/new.vala"
					_tmp33_ = self->priv->switch4;
#line 88 "/home/test/core/extensions/new.vala"
					if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp33_) {
#line 507 "new.c"
						gboolean _tmp34_;
#line 88 "/home/test/core/extensions/new.vala"
						_tmp34_ = self->priv->active4;
#line 88 "/home/test/core/extensions/new.vala"
						_tmp32_ = !_tmp34_;
#line 513 "new.c"
					} else {
#line 88 "/home/test/core/extensions/new.vala"
						_tmp32_ = FALSE;
#line 517 "new.c"
					}
#line 88 "/home/test/core/extensions/new.vala"
					if (_tmp32_) {
#line 521 "new.c"
						gboolean _tmp35_ = FALSE;
						gboolean _tmp36_ = FALSE;
						gboolean _tmp37_;
#line 89 "/home/test/core/extensions/new.vala"
						_tmp37_ = self->priv->active1;
#line 89 "/home/test/core/extensions/new.vala"
						if (_tmp37_) {
#line 529 "new.c"
							gboolean _tmp38_;
#line 89 "/home/test/core/extensions/new.vala"
							_tmp38_ = self->priv->active2;
#line 89 "/home/test/core/extensions/new.vala"
							_tmp36_ = _tmp38_;
#line 535 "new.c"
						} else {
#line 89 "/home/test/core/extensions/new.vala"
							_tmp36_ = FALSE;
#line 539 "new.c"
						}
#line 89 "/home/test/core/extensions/new.vala"
						if (_tmp36_) {
#line 543 "new.c"
							gboolean _tmp39_;
#line 89 "/home/test/core/extensions/new.vala"
							_tmp39_ = self->priv->active3;
#line 89 "/home/test/core/extensions/new.vala"
							_tmp35_ = _tmp39_;
#line 549 "new.c"
						} else {
#line 89 "/home/test/core/extensions/new.vala"
							_tmp35_ = FALSE;
#line 553 "new.c"
						}
#line 89 "/home/test/core/extensions/new.vala"
						if (!_tmp35_) {
#line 557 "new.c"
							GtkSwitch* _tmp40_;
							GtkSwitch* _tmp41_;
							GtkSwitch* _tmp42_;
#line 90 "/home/test/core/extensions/new.vala"
							g_print ("Avvio tutti i programmi\n");
#line 91 "/home/test/core/extensions/new.vala"
							_tmp40_ = self->priv->switch1;
#line 91 "/home/test/core/extensions/new.vala"
							gtk_switch_set_active (_tmp40_, TRUE);
#line 92 "/home/test/core/extensions/new.vala"
							_tmp41_ = self->priv->switch2;
#line 92 "/home/test/core/extensions/new.vala"
							gtk_switch_set_active (_tmp41_, TRUE);
#line 93 "/home/test/core/extensions/new.vala"
							_tmp42_ = self->priv->switch3;
#line 93 "/home/test/core/extensions/new.vala"
							gtk_switch_set_active (_tmp42_, TRUE);
#line 575 "new.c"
						}
#line 95 "/home/test/core/extensions/new.vala"
						self->priv->active4 = TRUE;
#line 96 "/home/test/core/extensions/new.vala"
						self->priv->all_active = TRUE;
#line 581 "new.c"
					}
				}
			}
		}
	} else {
		GtkSwitch* _tmp43_;
#line 100 "/home/test/core/extensions/new.vala"
		_tmp43_ = self->priv->switch1;
#line 100 "/home/test/core/extensions/new.vala"
		if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp43_) {
#line 101 "/home/test/core/extensions/new.vala"
			if (midori_button_spawn_warning (self, "la cattura dei pacchetti di rete")) {
#line 594 "new.c"
				gchar* _tmp44_;
				gchar* _tmp45_;
				gchar* _tmp46_;
				gchar** _tmp47_;
				gchar** _tmp48_;
				gint _tmp48__length1;
				gboolean _tmp49_;
#line 102 "/home/test/core/extensions/new.vala"
				_tmp44_ = g_strdup ("python3");
#line 102 "/home/test/core/extensions/new.vala"
				_tmp45_ = g_strdup ("script/kill_program.py");
#line 102 "/home/test/core/extensions/new.vala"
				_tmp46_ = g_strdup ("tshark");
#line 102 "/home/test/core/extensions/new.vala"
				_tmp47_ = g_new0 (gchar*, 3 + 1);
#line 102 "/home/test/core/extensions/new.vala"
				_tmp47_[0] = _tmp44_;
#line 102 "/home/test/core/extensions/new.vala"
				_tmp47_[1] = _tmp45_;
#line 102 "/home/test/core/extensions/new.vala"
				_tmp47_[2] = _tmp46_;
#line 102 "/home/test/core/extensions/new.vala"
				_tmp48_ = _tmp47_;
#line 102 "/home/test/core/extensions/new.vala"
				_tmp48__length1 = 3;
#line 102 "/home/test/core/extensions/new.vala"
				midori_button_exec_program_async (self, _tmp48_, 3);
#line 102 "/home/test/core/extensions/new.vala"
				_tmp48_ = (_vala_array_free (_tmp48_, _tmp48__length1, (GDestroyNotify) g_free), NULL);
#line 103 "/home/test/core/extensions/new.vala"
				self->priv->active1 = FALSE;
#line 104 "/home/test/core/extensions/new.vala"
				_tmp49_ = self->priv->active4;
#line 104 "/home/test/core/extensions/new.vala"
				if (_tmp49_) {
#line 630 "new.c"
					GtkSwitch* _tmp50_;
#line 105 "/home/test/core/extensions/new.vala"
					self->priv->all_active = FALSE;
#line 106 "/home/test/core/extensions/new.vala"
					_tmp50_ = self->priv->switch4;
#line 106 "/home/test/core/extensions/new.vala"
					gtk_switch_set_active (_tmp50_, FALSE);
#line 638 "new.c"
				}
			} else {
#line 110 "/home/test/core/extensions/new.vala"
				gtk_switch_set_active (G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL, TRUE);
#line 643 "new.c"
			}
		} else {
			GtkSwitch* _tmp51_;
#line 112 "/home/test/core/extensions/new.vala"
			_tmp51_ = self->priv->switch2;
#line 112 "/home/test/core/extensions/new.vala"
			if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp51_) {
#line 113 "/home/test/core/extensions/new.vala"
				if (midori_button_spawn_warning (self, "l'estrazione del codice sorgente")) {
#line 653 "new.c"
					gboolean _tmp52_;
#line 114 "/home/test/core/extensions/new.vala"
					g_print ("Termina estrazione codice sorgente\n");
#line 115 "/home/test/core/extensions/new.vala"
					self->priv->active2 = FALSE;
#line 116 "/home/test/core/extensions/new.vala"
					_tmp52_ = self->priv->active4;
#line 116 "/home/test/core/extensions/new.vala"
					if (_tmp52_) {
#line 663 "new.c"
						GtkSwitch* _tmp53_;
#line 117 "/home/test/core/extensions/new.vala"
						self->priv->all_active = FALSE;
#line 118 "/home/test/core/extensions/new.vala"
						_tmp53_ = self->priv->switch4;
#line 118 "/home/test/core/extensions/new.vala"
						gtk_switch_set_active (_tmp53_, FALSE);
#line 671 "new.c"
					}
				} else {
#line 122 "/home/test/core/extensions/new.vala"
					gtk_switch_set_active (G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL, TRUE);
#line 676 "new.c"
				}
			} else {
				GtkSwitch* _tmp54_;
#line 123 "/home/test/core/extensions/new.vala"
				_tmp54_ = self->priv->switch3;
#line 123 "/home/test/core/extensions/new.vala"
				if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp54_) {
#line 124 "/home/test/core/extensions/new.vala"
					if (midori_button_spawn_warning (self, "la registrazione")) {
#line 686 "new.c"
						gboolean _tmp55_;
#line 125 "/home/test/core/extensions/new.vala"
						g_print ("Termina registrazione\n");
#line 126 "/home/test/core/extensions/new.vala"
						self->priv->active3 = FALSE;
#line 127 "/home/test/core/extensions/new.vala"
						_tmp55_ = self->priv->active4;
#line 127 "/home/test/core/extensions/new.vala"
						if (_tmp55_) {
#line 696 "new.c"
							GtkSwitch* _tmp56_;
#line 128 "/home/test/core/extensions/new.vala"
							self->priv->all_active = FALSE;
#line 129 "/home/test/core/extensions/new.vala"
							_tmp56_ = self->priv->switch4;
#line 129 "/home/test/core/extensions/new.vala"
							gtk_switch_set_active (_tmp56_, FALSE);
#line 704 "new.c"
						}
					} else {
#line 133 "/home/test/core/extensions/new.vala"
						gtk_switch_set_active (G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL, TRUE);
#line 709 "new.c"
					}
				} else {
					GtkSwitch* _tmp57_;
#line 134 "/home/test/core/extensions/new.vala"
					_tmp57_ = self->priv->switch4;
#line 134 "/home/test/core/extensions/new.vala"
					if ((G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL) == _tmp57_) {
#line 717 "new.c"
						gboolean _tmp58_;
#line 135 "/home/test/core/extensions/new.vala"
						_tmp58_ = self->priv->all_active;
#line 135 "/home/test/core/extensions/new.vala"
						if (_tmp58_) {
#line 136 "/home/test/core/extensions/new.vala"
							if (midori_button_spawn_warning (self, "l'esecuzione di tutti i programmi")) {
#line 725 "new.c"
								GtkSwitch* _tmp59_;
								GtkSwitch* _tmp60_;
								GtkSwitch* _tmp61_;
#line 137 "/home/test/core/extensions/new.vala"
								g_print ("Termino tutti i programmi\n");
#line 138 "/home/test/core/extensions/new.vala"
								_tmp59_ = self->priv->switch1;
#line 138 "/home/test/core/extensions/new.vala"
								gtk_switch_set_active (_tmp59_, FALSE);
#line 139 "/home/test/core/extensions/new.vala"
								_tmp60_ = self->priv->switch2;
#line 139 "/home/test/core/extensions/new.vala"
								gtk_switch_set_active (_tmp60_, FALSE);
#line 140 "/home/test/core/extensions/new.vala"
								_tmp61_ = self->priv->switch3;
#line 140 "/home/test/core/extensions/new.vala"
								gtk_switch_set_active (_tmp61_, FALSE);
#line 141 "/home/test/core/extensions/new.vala"
								self->priv->active4 = FALSE;
#line 745 "new.c"
							} else {
#line 144 "/home/test/core/extensions/new.vala"
								gtk_switch_set_active (G_TYPE_CHECK_INSTANCE_TYPE (switcher, gtk_switch_get_type ()) ? ((GtkSwitch*) switcher) : NULL, TRUE);
#line 749 "new.c"
							}
						} else {
#line 146 "/home/test/core/extensions/new.vala"
							self->priv->active4 = FALSE;
#line 754 "new.c"
						}
					}
				}
			}
		}
	}
}


static gboolean
midori_button_spawn_warning (MidoriButton* self,
                             const gchar* str)
{
	gboolean result = FALSE;
	gchar* message = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GtkMessageDialog* dialog = NULL;
	MidoriBrowser* _tmp4_;
	const gchar* _tmp5_;
	GtkMessageDialog* _tmp6_;
	GtkMessageDialog* _tmp7_;
	gint response = 0;
	GtkMessageDialog* _tmp8_;
	gboolean ret = FALSE;
	gint _tmp9_;
	GtkMessageDialog* _tmp10_;
#line 149 "/home/test/core/extensions/new.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 149 "/home/test/core/extensions/new.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 150 "/home/test/core/extensions/new.vala"
	_tmp0_ = g_strconcat ("Sicuro di voler bloccare ", str, NULL);
#line 150 "/home/test/core/extensions/new.vala"
	_tmp1_ = _tmp0_;
#line 150 "/home/test/core/extensions/new.vala"
	_tmp2_ = g_strconcat (_tmp1_, " ?", NULL);
#line 150 "/home/test/core/extensions/new.vala"
	_tmp3_ = _tmp2_;
#line 150 "/home/test/core/extensions/new.vala"
	_g_free0 (_tmp1_);
#line 150 "/home/test/core/extensions/new.vala"
	message = _tmp3_;
#line 151 "/home/test/core/extensions/new.vala"
	_tmp4_ = self->priv->browser;
#line 151 "/home/test/core/extensions/new.vala"
	_tmp5_ = message;
#line 151 "/home/test/core/extensions/new.vala"
	_tmp6_ = (GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) _tmp4_, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_YES_NO, "%s", _tmp5_);
#line 151 "/home/test/core/extensions/new.vala"
	g_object_ref_sink (_tmp6_);
#line 151 "/home/test/core/extensions/new.vala"
	dialog = _tmp6_;
#line 152 "/home/test/core/extensions/new.vala"
	_tmp7_ = dialog;
#line 152 "/home/test/core/extensions/new.vala"
	gtk_window_set_title ((GtkWindow*) _tmp7_, "ATTENZIONE");
#line 153 "/home/test/core/extensions/new.vala"
	_tmp8_ = dialog;
#line 153 "/home/test/core/extensions/new.vala"
	response = gtk_dialog_run ((GtkDialog*) _tmp8_);
#line 154 "/home/test/core/extensions/new.vala"
	ret = FALSE;
#line 156 "/home/test/core/extensions/new.vala"
	_tmp9_ = response;
#line 156 "/home/test/core/extensions/new.vala"
	switch (_tmp9_) {
#line 156 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_YES:
#line 826 "new.c"
		{
#line 158 "/home/test/core/extensions/new.vala"
			ret = TRUE;
#line 159 "/home/test/core/extensions/new.vala"
			break;
#line 832 "new.c"
		}
#line 156 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_NO:
#line 836 "new.c"
		{
#line 161 "/home/test/core/extensions/new.vala"
			break;
#line 840 "new.c"
		}
#line 156 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_DELETE_EVENT:
#line 844 "new.c"
		{
#line 163 "/home/test/core/extensions/new.vala"
			g_print ("dialog closed or cancelled\n");
#line 164 "/home/test/core/extensions/new.vala"
			break;
#line 850 "new.c"
		}
		default:
#line 156 "/home/test/core/extensions/new.vala"
		break;
#line 855 "new.c"
	}
#line 167 "/home/test/core/extensions/new.vala"
	_tmp10_ = dialog;
#line 167 "/home/test/core/extensions/new.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp10_);
#line 168 "/home/test/core/extensions/new.vala"
	result = ret;
#line 168 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (dialog);
#line 168 "/home/test/core/extensions/new.vala"
	_g_free0 (message);
#line 168 "/home/test/core/extensions/new.vala"
	return result;
#line 869 "new.c"
}


static gboolean
midori_button_spawn_option (MidoriButton* self)
{
	gboolean result = FALSE;
	gchar* message = NULL;
	gchar* _tmp0_;
	GtkMessageDialog* dialog = NULL;
	MidoriBrowser* _tmp1_;
	const gchar* _tmp2_;
	GtkMessageDialog* _tmp3_;
	GtkMessageDialog* _tmp4_;
	gint response = 0;
	GtkMessageDialog* _tmp5_;
	gboolean ret = FALSE;
	gint _tmp6_;
	GtkMessageDialog* _tmp7_;
#line 171 "/home/test/core/extensions/new.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 172 "/home/test/core/extensions/new.vala"
	_tmp0_ = g_strdup ("Vuoi abilitare la registrazione dell'audio proveniente dal microfono ?");
#line 172 "/home/test/core/extensions/new.vala"
	message = _tmp0_;
#line 173 "/home/test/core/extensions/new.vala"
	_tmp1_ = self->priv->browser;
#line 173 "/home/test/core/extensions/new.vala"
	_tmp2_ = message;
#line 173 "/home/test/core/extensions/new.vala"
	_tmp3_ = (GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) _tmp1_, GTK_DIALOG_MODAL, GTK_MESSAGE_QUESTION, GTK_BUTTONS_YES_NO, "%s", _tmp2_);
#line 173 "/home/test/core/extensions/new.vala"
	g_object_ref_sink (_tmp3_);
#line 173 "/home/test/core/extensions/new.vala"
	dialog = _tmp3_;
#line 174 "/home/test/core/extensions/new.vala"
	_tmp4_ = dialog;
#line 174 "/home/test/core/extensions/new.vala"
	gtk_window_set_title ((GtkWindow*) _tmp4_, "ATTENZIONE");
#line 175 "/home/test/core/extensions/new.vala"
	_tmp5_ = dialog;
#line 175 "/home/test/core/extensions/new.vala"
	response = gtk_dialog_run ((GtkDialog*) _tmp5_);
#line 176 "/home/test/core/extensions/new.vala"
	ret = FALSE;
#line 178 "/home/test/core/extensions/new.vala"
	_tmp6_ = response;
#line 178 "/home/test/core/extensions/new.vala"
	switch (_tmp6_) {
#line 178 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_YES:
#line 921 "new.c"
		{
#line 180 "/home/test/core/extensions/new.vala"
			ret = TRUE;
#line 181 "/home/test/core/extensions/new.vala"
			break;
#line 927 "new.c"
		}
#line 178 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_NO:
#line 931 "new.c"
		{
#line 183 "/home/test/core/extensions/new.vala"
			break;
#line 935 "new.c"
		}
#line 178 "/home/test/core/extensions/new.vala"
		case GTK_RESPONSE_DELETE_EVENT:
#line 939 "new.c"
		{
#line 185 "/home/test/core/extensions/new.vala"
			g_print ("dialog closed or cancelled\n");
#line 186 "/home/test/core/extensions/new.vala"
			break;
#line 945 "new.c"
		}
		default:
#line 178 "/home/test/core/extensions/new.vala"
		break;
#line 950 "new.c"
	}
#line 189 "/home/test/core/extensions/new.vala"
	_tmp7_ = dialog;
#line 189 "/home/test/core/extensions/new.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp7_);
#line 190 "/home/test/core/extensions/new.vala"
	result = ret;
#line 190 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (dialog);
#line 190 "/home/test/core/extensions/new.vala"
	_g_free0 (message);
#line 190 "/home/test/core/extensions/new.vala"
	return result;
#line 964 "new.c"
}


static void
midori_button_exec_program_async (MidoriButton* self,
                                  gchar** spawn_args,
                                  int spawn_args_length1)
{
	GError* _inner_error0_ = NULL;
#line 193 "/home/test/core/extensions/new.vala"
	g_return_if_fail (self != NULL);
#line 976 "new.c"
	{
		gchar** spawn_env = NULL;
		gchar** _tmp0_;
		gchar** _tmp1_;
		gint spawn_env_length1;
		gint _spawn_env_size_;
		GPid child_pid = 0;
		gint standard_input = 0;
		gint standard_output = 0;
		gint standard_error = 0;
		GPid _tmp2_ = 0;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 195 "/home/test/core/extensions/new.vala"
		_tmp1_ = _tmp0_ = g_get_environ ();
#line 195 "/home/test/core/extensions/new.vala"
		spawn_env = _tmp1_;
#line 195 "/home/test/core/extensions/new.vala"
		spawn_env_length1 = _vala_array_length (_tmp0_);
#line 195 "/home/test/core/extensions/new.vala"
		_spawn_env_size_ = spawn_env_length1;
#line 202 "/home/test/core/extensions/new.vala"
		g_spawn_async_with_pipes ("./", spawn_args, spawn_env, G_SPAWN_SEARCH_PATH | G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp2_, &_tmp3_, &_tmp4_, &_tmp5_, &_inner_error0_);
#line 202 "/home/test/core/extensions/new.vala"
		child_pid = _tmp2_;
#line 202 "/home/test/core/extensions/new.vala"
		standard_input = _tmp3_;
#line 202 "/home/test/core/extensions/new.vala"
		standard_output = _tmp4_;
#line 202 "/home/test/core/extensions/new.vala"
		standard_error = _tmp5_;
#line 202 "/home/test/core/extensions/new.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 202 "/home/test/core/extensions/new.vala"
			spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
#line 202 "/home/test/core/extensions/new.vala"
			if (_inner_error0_->domain == G_SPAWN_ERROR) {
#line 1015 "new.c"
				goto __catch0_g_spawn_error;
			}
#line 202 "/home/test/core/extensions/new.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 202 "/home/test/core/extensions/new.vala"
			g_clear_error (&_inner_error0_);
#line 202 "/home/test/core/extensions/new.vala"
			return;
#line 1024 "new.c"
		}
#line 194 "/home/test/core/extensions/new.vala"
		spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
#line 1028 "new.c"
	}
	goto __finally0;
	__catch0_g_spawn_error:
	{
		GError* e = NULL;
		GError* _tmp6_;
		const gchar* _tmp7_;
#line 194 "/home/test/core/extensions/new.vala"
		e = _inner_error0_;
#line 194 "/home/test/core/extensions/new.vala"
		_inner_error0_ = NULL;
#line 212 "/home/test/core/extensions/new.vala"
		_tmp6_ = e;
#line 212 "/home/test/core/extensions/new.vala"
		_tmp7_ = _tmp6_->message;
#line 212 "/home/test/core/extensions/new.vala"
		g_print ("Error: %s\n", _tmp7_);
#line 194 "/home/test/core/extensions/new.vala"
		_g_error_free0 (e);
#line 1048 "new.c"
	}
	__finally0:
#line 194 "/home/test/core/extensions/new.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 194 "/home/test/core/extensions/new.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 194 "/home/test/core/extensions/new.vala"
		g_clear_error (&_inner_error0_);
#line 194 "/home/test/core/extensions/new.vala"
		return;
#line 1059 "new.c"
	}
}


static void
midori_button_real_open_config (MidoriButton* self)
{
	GtkPopover* _tmp0_;
#line 44 "/home/test/core/extensions/new.vala"
	_tmp0_ = self->priv->popover;
#line 44 "/home/test/core/extensions/new.vala"
	gtk_widget_show ((GtkWidget*) _tmp0_);
#line 1072 "new.c"
}


static void
_midori_button_switcher_activated_g_object_notify (GObject* _sender,
                                                   GParamSpec* pspec,
                                                   gpointer self)
{
#line 37 "/home/test/core/extensions/new.vala"
	midori_button_switcher_activated ((MidoriButton*) self, _sender, pspec);
#line 1083 "new.c"
}


static GObject *
midori_button_constructor (GType type,
                           guint n_construct_properties,
                           GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MidoriButton * self;
	GtkPopover* _tmp0_;
	GtkSwitch* _tmp1_;
	GtkSwitch* _tmp2_;
	GtkSwitch* _tmp3_;
	GtkSwitch* _tmp4_;
#line 35 "/home/test/core/extensions/new.vala"
	parent_class = G_OBJECT_CLASS (midori_button_parent_class);
#line 35 "/home/test/core/extensions/new.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 35 "/home/test/core/extensions/new.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_BUTTON, MidoriButton);
#line 36 "/home/test/core/extensions/new.vala"
	_tmp0_ = self->priv->popover;
#line 36 "/home/test/core/extensions/new.vala"
	gtk_popover_set_relative_to (_tmp0_, (GtkWidget*) self);
#line 37 "/home/test/core/extensions/new.vala"
	_tmp1_ = self->priv->switch1;
#line 37 "/home/test/core/extensions/new.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify::active", (GCallback) _midori_button_switcher_activated_g_object_notify, self, 0);
#line 38 "/home/test/core/extensions/new.vala"
	_tmp2_ = self->priv->switch2;
#line 38 "/home/test/core/extensions/new.vala"
	g_signal_connect_object ((GObject*) _tmp2_, "notify::active", (GCallback) _midori_button_switcher_activated_g_object_notify, self, 0);
#line 39 "/home/test/core/extensions/new.vala"
	_tmp3_ = self->priv->switch3;
#line 39 "/home/test/core/extensions/new.vala"
	g_signal_connect_object ((GObject*) _tmp3_, "notify::active", (GCallback) _midori_button_switcher_activated_g_object_notify, self, 0);
#line 40 "/home/test/core/extensions/new.vala"
	_tmp4_ = self->priv->switch4;
#line 40 "/home/test/core/extensions/new.vala"
	g_signal_connect_object ((GObject*) _tmp4_, "notify::active", (GCallback) _midori_button_switcher_activated_g_object_notify, self, 0);
#line 35 "/home/test/core/extensions/new.vala"
	return obj;
#line 1128 "new.c"
}


static void
midori_button_class_init (MidoriButtonClass * klass)
{
	gint MidoriButton_private_offset;
#line 15 "/home/test/core/extensions/new.vala"
	midori_button_parent_class = g_type_class_peek_parent (klass);
#line 15 "/home/test/core/extensions/new.vala"
	g_type_class_add_private (klass, sizeof (MidoriButtonPrivate));
#line 15 "/home/test/core/extensions/new.vala"
	((MidoriButtonClass *) klass)->open_config = midori_button_real_open_config;
#line 15 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (klass)->constructor = midori_button_constructor;
#line 15 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_button_finalize;
#line 15 "/home/test/core/extensions/new.vala"
	MidoriButton_private_offset = g_type_class_get_instance_private_offset (klass);
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/ui/new-button.ui");
#line 15 "/home/test/core/extensions/new.vala"
	midori_button_signals[MIDORI_BUTTON_OPEN_CONFIG_SIGNAL] = g_signal_new ("open-config", MIDORI_TYPE_BUTTON, G_SIGNAL_RUN_LAST, G_STRUCT_OFFSET (MidoriButtonClass, open_config), NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "popover", FALSE, MidoriButton_private_offset + G_STRUCT_OFFSET (MidoriButtonPrivate, popover));
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switch1", FALSE, MidoriButton_private_offset + G_STRUCT_OFFSET (MidoriButtonPrivate, switch1));
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switch2", FALSE, MidoriButton_private_offset + G_STRUCT_OFFSET (MidoriButtonPrivate, switch2));
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switch3", FALSE, MidoriButton_private_offset + G_STRUCT_OFFSET (MidoriButtonPrivate, switch3));
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switch4", FALSE, MidoriButton_private_offset + G_STRUCT_OFFSET (MidoriButtonPrivate, switch4));
#line 1162 "new.c"
}


static void
midori_button_instance_init (MidoriButton * self)
{
#line 15 "/home/test/core/extensions/new.vala"
	self->priv = MIDORI_BUTTON_GET_PRIVATE (self);
#line 27 "/home/test/core/extensions/new.vala"
	self->priv->active1 = FALSE;
#line 28 "/home/test/core/extensions/new.vala"
	self->priv->active2 = FALSE;
#line 29 "/home/test/core/extensions/new.vala"
	self->priv->active3 = FALSE;
#line 30 "/home/test/core/extensions/new.vala"
	self->priv->active4 = FALSE;
#line 31 "/home/test/core/extensions/new.vala"
	self->priv->all_active = FALSE;
#line 15 "/home/test/core/extensions/new.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1183 "new.c"
}


static void
midori_button_finalize (GObject * obj)
{
	MidoriButton * self;
#line 15 "/home/test/core/extensions/new.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_BUTTON, MidoriButton);
#line 17 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->popover);
#line 19 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->switch1);
#line 21 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->switch2);
#line 23 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->switch3);
#line 25 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->switch4);
#line 33 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->browser);
#line 15 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (midori_button_parent_class)->finalize (obj);
#line 1207 "new.c"
}


GType
midori_button_get_type (void)
{
	return midori_button_type_id;
}


GType
midori_button_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (MidoriButtonClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_button_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriButton), 0, (GInstanceInitFunc) midori_button_instance_init, NULL };
	midori_button_type_id = g_type_module_register_type (module, gtk_button_get_type (), "MidoriButton", &g_define_type_info, 0);
	return midori_button_type_id;
}


static void
midori_frontend_real_activate (MidoriBrowserActivatable* base)
{
	MidoriFrontend * self;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
	MidoriBrowser* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp5_;
	MidoriBrowser* _tmp6_;
	MidoriBrowser* _tmp7_;
	MidoriBrowser* _tmp8_;
	MidoriBrowser* _tmp9_;
	MidoriBrowser* _tmp10_;
	MidoriBrowser* _tmp11_;
	MidoriButton* _tmp12_;
	MidoriButton* _tmp13_;
#line 221 "/home/test/core/extensions/new.vala"
	self = (MidoriFrontend*) base;
#line 223 "/home/test/core/extensions/new.vala"
	_tmp0_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 223 "/home/test/core/extensions/new.vala"
	_tmp1_ = _tmp0_;
#line 223 "/home/test/core/extensions/new.vala"
	_tmp2_ = _tmp1_;
#line 223 "/home/test/core/extensions/new.vala"
	_tmp3_ = midori_browser_get_is_locked (_tmp2_);
#line 223 "/home/test/core/extensions/new.vala"
	_tmp4_ = _tmp3_;
#line 223 "/home/test/core/extensions/new.vala"
	_tmp5_ = _tmp4_;
#line 223 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (_tmp2_);
#line 223 "/home/test/core/extensions/new.vala"
	if (_tmp5_) {
#line 224 "/home/test/core/extensions/new.vala"
		return;
#line 1265 "new.c"
	}
#line 227 "/home/test/core/extensions/new.vala"
	_tmp6_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 227 "/home/test/core/extensions/new.vala"
	_tmp7_ = _tmp6_;
#line 227 "/home/test/core/extensions/new.vala"
	_tmp8_ = _tmp7_;
#line 227 "/home/test/core/extensions/new.vala"
	_tmp9_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 227 "/home/test/core/extensions/new.vala"
	_tmp10_ = _tmp9_;
#line 227 "/home/test/core/extensions/new.vala"
	_tmp11_ = _tmp10_;
#line 227 "/home/test/core/extensions/new.vala"
	_tmp12_ = midori_button_new (_tmp11_);
#line 227 "/home/test/core/extensions/new.vala"
	g_object_ref_sink (_tmp12_);
#line 227 "/home/test/core/extensions/new.vala"
	_tmp13_ = _tmp12_;
#line 227 "/home/test/core/extensions/new.vala"
	midori_browser_add_button (_tmp8_, (GtkButton*) _tmp13_);
#line 227 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (_tmp13_);
#line 227 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (_tmp11_);
#line 227 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (_tmp8_);
#line 1293 "new.c"
}


MidoriFrontend*
midori_frontend_construct (GType object_type)
{
	MidoriFrontend * self = NULL;
#line 218 "/home/test/core/extensions/new.vala"
	self = (MidoriFrontend*) g_object_new (object_type, NULL);
#line 218 "/home/test/core/extensions/new.vala"
	return self;
#line 1305 "new.c"
}


MidoriFrontend*
midori_frontend_new (void)
{
#line 218 "/home/test/core/extensions/new.vala"
	return midori_frontend_construct (MIDORI_TYPE_FRONTEND);
#line 1314 "new.c"
}


static MidoriBrowser*
midori_frontend_real_get_browser (MidoriBrowserActivatable* base)
{
	MidoriBrowser* result;
	MidoriFrontend* self;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
#line 219 "/home/test/core/extensions/new.vala"
	self = (MidoriFrontend*) base;
#line 219 "/home/test/core/extensions/new.vala"
	_tmp0_ = self->priv->_browser;
#line 219 "/home/test/core/extensions/new.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 219 "/home/test/core/extensions/new.vala"
	result = _tmp1_;
#line 219 "/home/test/core/extensions/new.vala"
	return result;
#line 1335 "new.c"
}


static void
midori_frontend_real_set_browser (MidoriBrowserActivatable* base,
                                  MidoriBrowser* value)
{
	MidoriFrontend* self;
#line 219 "/home/test/core/extensions/new.vala"
	self = (MidoriFrontend*) base;
#line 219 "/home/test/core/extensions/new.vala"
	if (midori_frontend_real_get_browser (base) != value) {
#line 1348 "new.c"
		MidoriBrowser* _tmp0_;
#line 219 "/home/test/core/extensions/new.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 219 "/home/test/core/extensions/new.vala"
		_g_object_unref0 (self->priv->_browser);
#line 219 "/home/test/core/extensions/new.vala"
		self->priv->_browser = _tmp0_;
#line 219 "/home/test/core/extensions/new.vala"
		g_object_notify_by_pspec ((GObject *) self, midori_frontend_properties[MIDORI_FRONTEND_BROWSER_PROPERTY]);
#line 1358 "new.c"
	}
}


static void
midori_frontend_class_init (MidoriFrontendClass * klass)
{
#line 218 "/home/test/core/extensions/new.vala"
	midori_frontend_parent_class = g_type_class_peek_parent (klass);
#line 218 "/home/test/core/extensions/new.vala"
	g_type_class_add_private (klass, sizeof (MidoriFrontendPrivate));
#line 218 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_midori_frontend_get_property;
#line 218 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_midori_frontend_set_property;
#line 218 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (klass)->finalize = midori_frontend_finalize;
#line 218 "/home/test/core/extensions/new.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), MIDORI_FRONTEND_BROWSER_PROPERTY, midori_frontend_properties[MIDORI_FRONTEND_BROWSER_PROPERTY] = g_param_spec_object ("browser", "browser", "browser", MIDORI_TYPE_BROWSER, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1378 "new.c"
}


static void
midori_frontend_midori_browser_activatable_interface_init (MidoriBrowserActivatableIface * iface)
{
#line 218 "/home/test/core/extensions/new.vala"
	midori_frontend_midori_browser_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 218 "/home/test/core/extensions/new.vala"
	iface->activate = (void (*) (MidoriBrowserActivatable*)) midori_frontend_real_activate;
#line 218 "/home/test/core/extensions/new.vala"
	iface->get_browser = midori_frontend_real_get_browser;
#line 218 "/home/test/core/extensions/new.vala"
	iface->set_browser = midori_frontend_real_set_browser;
#line 1393 "new.c"
}


static void
midori_frontend_instance_init (MidoriFrontend * self)
{
#line 218 "/home/test/core/extensions/new.vala"
	self->priv = MIDORI_FRONTEND_GET_PRIVATE (self);
#line 1402 "new.c"
}


static void
midori_frontend_finalize (GObject * obj)
{
	MidoriFrontend * self;
#line 218 "/home/test/core/extensions/new.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MIDORI_TYPE_FRONTEND, MidoriFrontend);
#line 219 "/home/test/core/extensions/new.vala"
	_g_object_unref0 (self->priv->_browser);
#line 218 "/home/test/core/extensions/new.vala"
	G_OBJECT_CLASS (midori_frontend_parent_class)->finalize (obj);
#line 1416 "new.c"
}


GType
midori_frontend_get_type (void)
{
	return midori_frontend_type_id;
}


GType
midori_frontend_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (MidoriFrontendClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) midori_frontend_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MidoriFrontend), 0, (GInstanceInitFunc) midori_frontend_instance_init, NULL };
	static const GInterfaceInfo midori_browser_activatable_info = { (GInterfaceInitFunc) midori_frontend_midori_browser_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	midori_frontend_type_id = g_type_module_register_type (module, G_TYPE_OBJECT, "MidoriFrontend", &g_define_type_info, 0);
	g_type_module_add_interface (module, midori_frontend_type_id, MIDORI_TYPE_BROWSER_ACTIVATABLE, &midori_browser_activatable_info);
	return midori_frontend_type_id;
}


static void
_vala_midori_frontend_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec)
{
	MidoriFrontend * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_FRONTEND, MidoriFrontend);
#line 218 "/home/test/core/extensions/new.vala"
	switch (property_id) {
#line 218 "/home/test/core/extensions/new.vala"
		case MIDORI_FRONTEND_BROWSER_PROPERTY:
#line 218 "/home/test/core/extensions/new.vala"
		g_value_take_object (value, midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self));
#line 218 "/home/test/core/extensions/new.vala"
		break;
#line 1454 "new.c"
		default:
#line 218 "/home/test/core/extensions/new.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 218 "/home/test/core/extensions/new.vala"
		break;
#line 1460 "new.c"
	}
}


static void
_vala_midori_frontend_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec)
{
	MidoriFrontend * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MIDORI_TYPE_FRONTEND, MidoriFrontend);
#line 218 "/home/test/core/extensions/new.vala"
	switch (property_id) {
#line 218 "/home/test/core/extensions/new.vala"
		case MIDORI_FRONTEND_BROWSER_PROPERTY:
#line 218 "/home/test/core/extensions/new.vala"
		midori_browser_activatable_set_browser ((MidoriBrowserActivatable*) self, g_value_get_object (value));
#line 218 "/home/test/core/extensions/new.vala"
		break;
#line 1481 "new.c"
		default:
#line 218 "/home/test/core/extensions/new.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 218 "/home/test/core/extensions/new.vala"
		break;
#line 1487 "new.c"
	}
}


void
peas_register_types (GTypeModule* module)
{
#line 233 "/home/test/core/extensions/new.vala"
	g_return_if_fail (module != NULL);
#line 233 "/home/test/core/extensions/new.vala"
	midori_button_register_type (module);
#line 233 "/home/test/core/extensions/new.vala"
	midori_frontend_register_type (module);
#line 234 "/home/test/core/extensions/new.vala"
	peas_object_module_register_extension_type (G_TYPE_CHECK_INSTANCE_CAST (module, peas_object_module_get_type (), PeasObjectModule), MIDORI_TYPE_BROWSER_ACTIVATABLE, MIDORI_TYPE_FRONTEND);
#line 1503 "new.c"
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint
_vala_array_length (gpointer array)
{
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



