/* statusbar-features.c generated by valac 0.40.23, the Vala compiler
 * generated from statusbar-features.vala, do not modify */

/*
 Copyright (C) 2008-2018 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include "midori-core.h"
#include <gtk/gtk.h>
#include "webkit2/webkit2.h"
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <libpeas/peas.h>


#define STATUSBAR_FEATURES_TYPE_FRONTEND (statusbar_features_frontend_get_type ())
#define STATUSBAR_FEATURES_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontend))
#define STATUSBAR_FEATURES_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontendClass))
#define STATUSBAR_FEATURES_IS_FRONTEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), STATUSBAR_FEATURES_TYPE_FRONTEND))
#define STATUSBAR_FEATURES_IS_FRONTEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), STATUSBAR_FEATURES_TYPE_FRONTEND))
#define STATUSBAR_FEATURES_FRONTEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontendClass))

typedef struct _StatusbarFeaturesFrontend StatusbarFeaturesFrontend;
typedef struct _StatusbarFeaturesFrontendClass StatusbarFeaturesFrontendClass;
typedef struct _StatusbarFeaturesFrontendPrivate StatusbarFeaturesFrontendPrivate;
enum  {
	STATUSBAR_FEATURES_FRONTEND_0_PROPERTY,
	STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY,
	STATUSBAR_FEATURES_FRONTEND_NUM_PROPERTIES
};
static GParamSpec* statusbar_features_frontend_properties[STATUSBAR_FEATURES_FRONTEND_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block2Data Block2Data;

struct _StatusbarFeaturesFrontend {
	GObject parent_instance;
	StatusbarFeaturesFrontendPrivate * priv;
};

struct _StatusbarFeaturesFrontendClass {
	GObjectClass parent_class;
};

struct _StatusbarFeaturesFrontendPrivate {
	MidoriBrowser* _browser;
};

struct _Block1Data {
	int _ref_count_;
	StatusbarFeaturesFrontend* self;
	GtkComboBoxText* zoom;
	GtkEntry* entry;
};

struct _Block2Data {
	int _ref_count_;
	StatusbarFeaturesFrontend* self;
	GtkToggleButton* button;
};


static gpointer statusbar_features_frontend_parent_class = NULL;
static MidoriBrowserActivatableIface * statusbar_features_frontend_midori_browser_activatable_parent_iface = NULL;
static GType statusbar_features_frontend_type_id = 0;

GType statusbar_features_frontend_register_type (GTypeModule * module);
GType statusbar_features_frontend_get_type (void) G_GNUC_CONST;
#define STATUSBAR_FEATURES_FRONTEND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontendPrivate))
void statusbar_features_frontend_add_zoom (StatusbarFeaturesFrontend* self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_);
static void ___lambda4__gtk_combo_box_changed (GtkComboBox* _sender,
                                        gpointer self);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__gtk_entry_activate (GtkEntry* _sender,
                                     gpointer self);
static void __lambda6_ (Block1Data* _data1_);
static void ___lambda6__midori_browser_activatable_deactivate (MidoriBrowserActivatable* _sender,
                                                        gpointer self);
static void statusbar_features_frontend_add_toggle (StatusbarFeaturesFrontend* self,
                                             const gchar* item,
                                             const gchar* icon_name,
                                             const gchar* tooltip);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda7_ (Block2Data* _data2_);
static void ___lambda7__midori_browser_activatable_deactivate (MidoriBrowserActivatable* _sender,
                                                        gpointer self);
static void statusbar_features_frontend_real_activate (MidoriBrowserActivatable* base);
StatusbarFeaturesFrontend* statusbar_features_frontend_new (void);
StatusbarFeaturesFrontend* statusbar_features_frontend_construct (GType object_type);
static void statusbar_features_frontend_finalize (GObject * obj);
static void _vala_statusbar_features_frontend_get_property (GObject * object,
                                                     guint property_id,
                                                     GValue * value,
                                                     GParamSpec * pspec);
static void _vala_statusbar_features_frontend_set_property (GObject * object,
                                                     guint property_id,
                                                     const GValue * value,
                                                     GParamSpec * pspec);
void peas_register_types (GTypeModule* module);
GType statusbar_features_frontend_register_type (GTypeModule * module);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	return _data1_;
#line 136 "statusbar-features.c"
}


static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 147 "statusbar-features.c"
		StatusbarFeaturesFrontend* self;
#line 16 "/home/test/core/extensions/statusbar-features.vala"
		self = _data1_->self;
#line 16 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_data1_->entry);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_data1_->zoom);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (self);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
		g_slice_free (Block1Data, _data1_);
#line 159 "statusbar-features.c"
	}
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 18 "/home/test/core/extensions/statusbar-features.vala"
	return self ? g_object_ref (self) : NULL;
#line 169 "statusbar-features.c"
}


static gchar*
double_to_string (gdouble self)
{
	gchar* result = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp3_ = g_strdup (_tmp2_);
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp4_ = _tmp3_;
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	_tmp1_ = (g_free (_tmp1_), NULL);
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = _tmp4_;
#line 938 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 201 "statusbar-features.c"
}


static void
__lambda4_ (Block1Data* _data1_)
{
	StatusbarFeaturesFrontend* self;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp48_;
	gboolean _tmp49_;
#line 28 "/home/test/core/extensions/statusbar-features.vala"
	self = _data1_->self;
#line 29 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 29 "/home/test/core/extensions/statusbar-features.vala"
	_tmp1_ = _tmp0_;
#line 29 "/home/test/core/extensions/statusbar-features.vala"
	_tmp2_ = g_strcmp0 (_tmp1_, "50%") == 0;
#line 29 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (_tmp1_);
#line 29 "/home/test/core/extensions/statusbar-features.vala"
	if (_tmp2_) {
#line 226 "statusbar-features.c"
		MidoriBrowser* _tmp3_;
		MidoriBrowser* _tmp4_;
		MidoriBrowser* _tmp5_;
		MidoriTab* _tmp6_;
		MidoriTab* _tmp7_;
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_tmp3_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_tmp4_ = _tmp3_;
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_tmp5_ = _tmp4_;
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_tmp6_ = midori_browser_get_tab (_tmp5_);
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_tmp7_ = _tmp6_;
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp7_, 0.5);
#line 30 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_tmp5_);
#line 246 "statusbar-features.c"
	} else {
		gchar* _tmp8_;
		gchar* _tmp9_;
		gboolean _tmp10_;
#line 31 "/home/test/core/extensions/statusbar-features.vala"
		_tmp8_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 31 "/home/test/core/extensions/statusbar-features.vala"
		_tmp9_ = _tmp8_;
#line 31 "/home/test/core/extensions/statusbar-features.vala"
		_tmp10_ = g_strcmp0 (_tmp9_, "80%") == 0;
#line 31 "/home/test/core/extensions/statusbar-features.vala"
		_g_free0 (_tmp9_);
#line 31 "/home/test/core/extensions/statusbar-features.vala"
		if (_tmp10_) {
#line 261 "statusbar-features.c"
			MidoriBrowser* _tmp11_;
			MidoriBrowser* _tmp12_;
			MidoriBrowser* _tmp13_;
			MidoriTab* _tmp14_;
			MidoriTab* _tmp15_;
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_tmp11_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_tmp12_ = _tmp11_;
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_tmp13_ = _tmp12_;
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_tmp14_ = midori_browser_get_tab (_tmp13_);
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_tmp15_ = _tmp14_;
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp15_, 0.8);
#line 32 "/home/test/core/extensions/statusbar-features.vala"
			_g_object_unref0 (_tmp13_);
#line 281 "statusbar-features.c"
		} else {
			gchar* _tmp16_;
			gchar* _tmp17_;
			gboolean _tmp18_;
#line 33 "/home/test/core/extensions/statusbar-features.vala"
			_tmp16_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 33 "/home/test/core/extensions/statusbar-features.vala"
			_tmp17_ = _tmp16_;
#line 33 "/home/test/core/extensions/statusbar-features.vala"
			_tmp18_ = g_strcmp0 (_tmp17_, "100%") == 0;
#line 33 "/home/test/core/extensions/statusbar-features.vala"
			_g_free0 (_tmp17_);
#line 33 "/home/test/core/extensions/statusbar-features.vala"
			if (_tmp18_) {
#line 296 "statusbar-features.c"
				MidoriBrowser* _tmp19_;
				MidoriBrowser* _tmp20_;
				MidoriBrowser* _tmp21_;
				MidoriTab* _tmp22_;
				MidoriTab* _tmp23_;
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_tmp19_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_tmp20_ = _tmp19_;
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_tmp21_ = _tmp20_;
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_tmp22_ = midori_browser_get_tab (_tmp21_);
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_tmp23_ = _tmp22_;
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp23_, 1.0);
#line 34 "/home/test/core/extensions/statusbar-features.vala"
				_g_object_unref0 (_tmp21_);
#line 316 "statusbar-features.c"
			} else {
				gchar* _tmp24_;
				gchar* _tmp25_;
				gboolean _tmp26_;
#line 35 "/home/test/core/extensions/statusbar-features.vala"
				_tmp24_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 35 "/home/test/core/extensions/statusbar-features.vala"
				_tmp25_ = _tmp24_;
#line 35 "/home/test/core/extensions/statusbar-features.vala"
				_tmp26_ = g_strcmp0 (_tmp25_, "120%") == 0;
#line 35 "/home/test/core/extensions/statusbar-features.vala"
				_g_free0 (_tmp25_);
#line 35 "/home/test/core/extensions/statusbar-features.vala"
				if (_tmp26_) {
#line 331 "statusbar-features.c"
					MidoriBrowser* _tmp27_;
					MidoriBrowser* _tmp28_;
					MidoriBrowser* _tmp29_;
					MidoriTab* _tmp30_;
					MidoriTab* _tmp31_;
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_tmp27_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_tmp28_ = _tmp27_;
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_tmp29_ = _tmp28_;
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_tmp30_ = midori_browser_get_tab (_tmp29_);
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_tmp31_ = _tmp30_;
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp31_, 1.2);
#line 36 "/home/test/core/extensions/statusbar-features.vala"
					_g_object_unref0 (_tmp29_);
#line 351 "statusbar-features.c"
				} else {
					gchar* _tmp32_;
					gchar* _tmp33_;
					gboolean _tmp34_;
#line 37 "/home/test/core/extensions/statusbar-features.vala"
					_tmp32_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 37 "/home/test/core/extensions/statusbar-features.vala"
					_tmp33_ = _tmp32_;
#line 37 "/home/test/core/extensions/statusbar-features.vala"
					_tmp34_ = g_strcmp0 (_tmp33_, "150%") == 0;
#line 37 "/home/test/core/extensions/statusbar-features.vala"
					_g_free0 (_tmp33_);
#line 37 "/home/test/core/extensions/statusbar-features.vala"
					if (_tmp34_) {
#line 366 "statusbar-features.c"
						MidoriBrowser* _tmp35_;
						MidoriBrowser* _tmp36_;
						MidoriBrowser* _tmp37_;
						MidoriTab* _tmp38_;
						MidoriTab* _tmp39_;
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_tmp35_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_tmp36_ = _tmp35_;
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_tmp37_ = _tmp36_;
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_tmp38_ = midori_browser_get_tab (_tmp37_);
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_tmp39_ = _tmp38_;
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp39_, 1.5);
#line 38 "/home/test/core/extensions/statusbar-features.vala"
						_g_object_unref0 (_tmp37_);
#line 386 "statusbar-features.c"
					} else {
						gchar* _tmp40_;
						gchar* _tmp41_;
						gboolean _tmp42_;
#line 39 "/home/test/core/extensions/statusbar-features.vala"
						_tmp40_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 39 "/home/test/core/extensions/statusbar-features.vala"
						_tmp41_ = _tmp40_;
#line 39 "/home/test/core/extensions/statusbar-features.vala"
						_tmp42_ = g_strcmp0 (_tmp41_, "200%") == 0;
#line 39 "/home/test/core/extensions/statusbar-features.vala"
						_g_free0 (_tmp41_);
#line 39 "/home/test/core/extensions/statusbar-features.vala"
						if (_tmp42_) {
#line 401 "statusbar-features.c"
							MidoriBrowser* _tmp43_;
							MidoriBrowser* _tmp44_;
							MidoriBrowser* _tmp45_;
							MidoriTab* _tmp46_;
							MidoriTab* _tmp47_;
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_tmp43_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_tmp44_ = _tmp43_;
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_tmp45_ = _tmp44_;
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_tmp46_ = midori_browser_get_tab (_tmp45_);
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_tmp47_ = _tmp46_;
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp47_, 2.0);
#line 40 "/home/test/core/extensions/statusbar-features.vala"
							_g_object_unref0 (_tmp45_);
#line 421 "statusbar-features.c"
						}
					}
				}
			}
		}
	}
#line 42 "/home/test/core/extensions/statusbar-features.vala"
	g_object_get ((GtkWidget*) _data1_->entry, "has-focus", &_tmp48_, NULL);
#line 42 "/home/test/core/extensions/statusbar-features.vala"
	_tmp49_ = _tmp48_;
#line 42 "/home/test/core/extensions/statusbar-features.vala"
	if (_tmp49_ == FALSE) {
#line 434 "statusbar-features.c"
		MidoriBrowser* _tmp50_;
		MidoriBrowser* _tmp51_;
		MidoriBrowser* _tmp52_;
		MidoriTab* _tmp53_;
		MidoriTab* _tmp54_;
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_tmp50_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_tmp51_ = _tmp50_;
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_tmp52_ = _tmp51_;
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_tmp53_ = midori_browser_get_tab (_tmp52_);
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_tmp54_ = _tmp53_;
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		gtk_widget_grab_focus ((GtkWidget*) _tmp54_);
#line 43 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_tmp52_);
#line 454 "statusbar-features.c"
	}
}


static void
___lambda4__gtk_combo_box_changed (GtkComboBox* _sender,
                                   gpointer self)
{
#line 28 "/home/test/core/extensions/statusbar-features.vala"
	__lambda4_ (self);
#line 465 "statusbar-features.c"
}


static gdouble
double_parse (const gchar* str)
{
	gdouble result = 0.0;
#line 944 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	g_return_val_if_fail (str != NULL, 0.0);
#line 945 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	result = g_ascii_strtod (str, NULL);
#line 945 "/usr/share/vala-0.40/vapi/glib-2.0.vapi"
	return result;
#line 479 "statusbar-features.c"
}


static void
__lambda5_ (Block1Data* _data1_)
{
	StatusbarFeaturesFrontend* self;
	const gchar* _tmp0_;
	MidoriBrowser* _tmp8_;
	MidoriBrowser* _tmp9_;
	MidoriBrowser* _tmp10_;
	MidoriTab* _tmp11_;
	MidoriTab* _tmp12_;
	gdouble _tmp13_;
	gdouble _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	MidoriBrowser* _tmp19_;
	MidoriBrowser* _tmp20_;
	MidoriBrowser* _tmp21_;
	MidoriTab* _tmp22_;
	MidoriTab* _tmp23_;
#line 47 "/home/test/core/extensions/statusbar-features.vala"
	self = _data1_->self;
#line 48 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = gtk_entry_get_text (_data1_->entry);
#line 48 "/home/test/core/extensions/statusbar-features.vala"
	if (double_parse (_tmp0_) >= ((gdouble) 1)) {
#line 510 "statusbar-features.c"
		MidoriBrowser* _tmp1_;
		MidoriBrowser* _tmp2_;
		MidoriBrowser* _tmp3_;
		MidoriTab* _tmp4_;
		MidoriTab* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp1_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp2_ = _tmp1_;
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp3_ = _tmp2_;
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp4_ = midori_browser_get_tab (_tmp3_);
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp5_ = _tmp4_;
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp6_ = gtk_combo_box_text_get_active_text (_data1_->zoom);
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_tmp7_ = _tmp6_;
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		webkit_web_view_set_zoom_level ((WebKitWebView*) _tmp5_, double_parse (_tmp7_) / 100);
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_g_free0 (_tmp7_);
#line 49 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_tmp3_);
#line 538 "statusbar-features.c"
	}
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp8_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp9_ = _tmp8_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp10_ = _tmp9_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp11_ = midori_browser_get_tab (_tmp10_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp12_ = _tmp11_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp13_ = webkit_web_view_get_zoom_level ((WebKitWebView*) _tmp12_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp14_ = _tmp13_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp15_ = double_to_string (100 * _tmp14_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp16_ = _tmp15_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp17_ = g_strconcat (_tmp16_, "%", NULL);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_tmp18_ = _tmp17_;
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	gtk_entry_set_text (_data1_->entry, _tmp18_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (_tmp18_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (_tmp16_);
#line 51 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (_tmp10_);
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_tmp19_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_tmp20_ = _tmp19_;
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_tmp21_ = _tmp20_;
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_tmp22_ = midori_browser_get_tab (_tmp21_);
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_tmp23_ = _tmp22_;
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_grab_focus ((GtkWidget*) _tmp23_);
#line 52 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (_tmp21_);
#line 584 "statusbar-features.c"
}


static void
___lambda5__gtk_entry_activate (GtkEntry* _sender,
                                gpointer self)
{
#line 47 "/home/test/core/extensions/statusbar-features.vala"
	__lambda5_ (self);
#line 594 "statusbar-features.c"
}


static void
__lambda6_ (Block1Data* _data1_)
{
	StatusbarFeaturesFrontend* self;
#line 55 "/home/test/core/extensions/statusbar-features.vala"
	self = _data1_->self;
#line 56 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_destroy ((GtkWidget*) _data1_->zoom);
#line 606 "statusbar-features.c"
}


static void
___lambda6__midori_browser_activatable_deactivate (MidoriBrowserActivatable* _sender,
                                                   gpointer self)
{
#line 55 "/home/test/core/extensions/statusbar-features.vala"
	__lambda6_ (self);
#line 616 "statusbar-features.c"
}


void
statusbar_features_frontend_add_zoom (StatusbarFeaturesFrontend* self)
{
	Block1Data* _data1_;
	GtkComboBoxText* _tmp0_;
	GtkWidget* _tmp1_;
	GtkEntry* _tmp2_;
	MidoriBrowser* _tmp3_;
	MidoriBrowser* _tmp4_;
	MidoriBrowser* _tmp5_;
	MidoriTab* _tmp6_;
	MidoriTab* _tmp7_;
	gdouble _tmp8_;
	gdouble _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	MidoriBrowser* _tmp14_;
	MidoriBrowser* _tmp15_;
	MidoriBrowser* _tmp16_;
	MidoriStatusbar* _tmp17_;
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	g_return_if_fail (self != NULL);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	_data1_->_ref_count_ = 1;
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	_data1_->self = g_object_ref (self);
#line 17 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = (GtkComboBoxText*) gtk_combo_box_text_new_with_entry ();
#line 17 "/home/test/core/extensions/statusbar-features.vala"
	g_object_ref_sink (_tmp0_);
#line 17 "/home/test/core/extensions/statusbar-features.vala"
	_data1_->zoom = _tmp0_;
#line 18 "/home/test/core/extensions/statusbar-features.vala"
	_tmp1_ = gtk_bin_get_child ((GtkBin*) _data1_->zoom);
#line 18 "/home/test/core/extensions/statusbar-features.vala"
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp1_) : NULL);
#line 18 "/home/test/core/extensions/statusbar-features.vala"
	_data1_->entry = _tmp2_;
#line 19 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "50%");
#line 20 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "80%");
#line 21 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "100%");
#line 22 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "120%");
#line 23 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "150%");
#line 24 "/home/test/core/extensions/statusbar-features.vala"
	gtk_combo_box_text_append_text (_data1_->zoom, "200%");
#line 25 "/home/test/core/extensions/statusbar-features.vala"
	gtk_entry_set_width_chars (_data1_->entry, 6);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp3_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp4_ = _tmp3_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp5_ = _tmp4_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp6_ = midori_browser_get_tab (_tmp5_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp7_ = _tmp6_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp8_ = webkit_web_view_get_zoom_level ((WebKitWebView*) _tmp7_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp9_ = _tmp8_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp10_ = double_to_string (100 * _tmp9_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp11_ = _tmp10_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp12_ = g_strconcat (_tmp11_, "%", NULL);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_tmp13_ = _tmp12_;
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	gtk_entry_set_text (_data1_->entry, _tmp13_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (_tmp13_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (_tmp11_);
#line 26 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (_tmp5_);
#line 27 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_show ((GtkWidget*) _data1_->zoom);
#line 28 "/home/test/core/extensions/statusbar-features.vala"
	g_signal_connect_data ((GtkComboBox*) _data1_->zoom, "changed", (GCallback) ___lambda4__gtk_combo_box_changed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 47 "/home/test/core/extensions/statusbar-features.vala"
	g_signal_connect_data (_data1_->entry, "activate", (GCallback) ___lambda5__gtk_entry_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 55 "/home/test/core/extensions/statusbar-features.vala"
	g_signal_connect_data ((MidoriBrowserActivatable*) self, "deactivate", (GCallback) ___lambda6__midori_browser_activatable_deactivate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	_tmp14_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	_tmp15_ = _tmp14_;
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	_tmp16_ = _tmp15_;
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	_tmp17_ = _tmp16_->statusbar;
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	gtk_container_add ((GtkContainer*) _tmp17_, (GtkWidget*) _data1_->zoom);
#line 58 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (_tmp16_);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	block1_data_unref (_data1_);
#line 16 "/home/test/core/extensions/statusbar-features.vala"
	_data1_ = NULL;
#line 730 "statusbar-features.c"
}


static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	return _data2_;
#line 741 "statusbar-features.c"
}


static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 752 "statusbar-features.c"
		StatusbarFeaturesFrontend* self;
#line 60 "/home/test/core/extensions/statusbar-features.vala"
		self = _data2_->self;
#line 60 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_data2_->button);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (self);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
		g_slice_free (Block2Data, _data2_);
#line 762 "statusbar-features.c"
	}
}


static void
__lambda7_ (Block2Data* _data2_)
{
	StatusbarFeaturesFrontend* self;
	GtkToggleButton* _tmp0_;
#line 75 "/home/test/core/extensions/statusbar-features.vala"
	self = _data2_->self;
#line 76 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = _data2_->button;
#line 76 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
#line 778 "statusbar-features.c"
}


static void
___lambda7__midori_browser_activatable_deactivate (MidoriBrowserActivatable* _sender,
                                                   gpointer self)
{
#line 75 "/home/test/core/extensions/statusbar-features.vala"
	__lambda7_ (self);
#line 788 "statusbar-features.c"
}


static void
statusbar_features_frontend_add_toggle (StatusbarFeaturesFrontend* self,
                                        const gchar* item,
                                        const gchar* icon_name,
                                        const gchar* tooltip)
{
	Block2Data* _data2_;
	GtkToggleButton* _tmp0_;
	GtkToggleButton* _tmp5_;
	MidoriCoreSettings* settings = NULL;
	MidoriCoreSettings* _tmp6_;
	MidoriCoreSettings* _tmp7_;
	GObjectClass* _tmp8_;
	GParamSpec* _tmp9_;
	GtkToggleButton* _tmp13_;
	MidoriBrowser* _tmp14_;
	MidoriBrowser* _tmp15_;
	MidoriBrowser* _tmp16_;
	MidoriStatusbar* _tmp17_;
	GtkToggleButton* _tmp18_;
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	g_return_if_fail (self != NULL);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	g_return_if_fail (item != NULL);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	_data2_->_ref_count_ = 1;
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	_data2_->self = g_object_ref (self);
#line 61 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = (GtkToggleButton*) gtk_toggle_button_new ();
#line 61 "/home/test/core/extensions/statusbar-features.vala"
	g_object_ref_sink (_tmp0_);
#line 61 "/home/test/core/extensions/statusbar-features.vala"
	_data2_->button = _tmp0_;
#line 62 "/home/test/core/extensions/statusbar-features.vala"
	if (icon_name != NULL) {
#line 830 "statusbar-features.c"
		GtkToggleButton* _tmp1_;
		GtkImage* _tmp2_;
		GtkImage* _tmp3_;
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		_tmp1_ = _data2_->button;
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name (icon_name, (GtkIconSize) GTK_ICON_SIZE_BUTTON);
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		g_object_ref_sink (_tmp2_);
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		_tmp3_ = _tmp2_;
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		gtk_container_add ((GtkContainer*) _tmp1_, (GtkWidget*) _tmp3_);
#line 63 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (_tmp3_);
#line 846 "statusbar-features.c"
	} else {
		GtkToggleButton* _tmp4_;
#line 65 "/home/test/core/extensions/statusbar-features.vala"
		_tmp4_ = _data2_->button;
#line 65 "/home/test/core/extensions/statusbar-features.vala"
		gtk_button_set_label ((GtkButton*) _tmp4_, item);
#line 853 "statusbar-features.c"
	}
#line 67 "/home/test/core/extensions/statusbar-features.vala"
	_tmp5_ = _data2_->button;
#line 67 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp5_, tooltip);
#line 68 "/home/test/core/extensions/statusbar-features.vala"
	_tmp6_ = midori_core_settings_get_default ();
#line 68 "/home/test/core/extensions/statusbar-features.vala"
	settings = _tmp6_;
#line 69 "/home/test/core/extensions/statusbar-features.vala"
	_tmp7_ = settings;
#line 69 "/home/test/core/extensions/statusbar-features.vala"
	_tmp8_ = G_OBJECT_GET_CLASS ((GObject*) _tmp7_);
#line 69 "/home/test/core/extensions/statusbar-features.vala"
	_tmp9_ = g_object_class_find_property (_tmp8_, item);
#line 69 "/home/test/core/extensions/statusbar-features.vala"
	if (_tmp9_ != NULL) {
#line 871 "statusbar-features.c"
		MidoriCoreSettings* _tmp10_;
		GtkToggleButton* _tmp11_;
#line 70 "/home/test/core/extensions/statusbar-features.vala"
		_tmp10_ = settings;
#line 70 "/home/test/core/extensions/statusbar-features.vala"
		_tmp11_ = _data2_->button;
#line 70 "/home/test/core/extensions/statusbar-features.vala"
		g_object_bind_property_with_closures ((GObject*) _tmp10_, item, (GObject*) _tmp11_, "active", G_BINDING_SYNC_CREATE | G_BINDING_BIDIRECTIONAL, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
#line 880 "statusbar-features.c"
	} else {
		GtkToggleButton* _tmp12_;
#line 72 "/home/test/core/extensions/statusbar-features.vala"
		_tmp12_ = _data2_->button;
#line 72 "/home/test/core/extensions/statusbar-features.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp12_, FALSE);
#line 887 "statusbar-features.c"
	}
#line 74 "/home/test/core/extensions/statusbar-features.vala"
	_tmp13_ = _data2_->button;
#line 74 "/home/test/core/extensions/statusbar-features.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp13_);
#line 75 "/home/test/core/extensions/statusbar-features.vala"
	g_signal_connect_data ((MidoriBrowserActivatable*) self, "deactivate", (GCallback) ___lambda7__midori_browser_activatable_deactivate, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_tmp14_ = midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self);
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_tmp15_ = _tmp14_;
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_tmp16_ = _tmp15_;
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_tmp17_ = _tmp16_->statusbar;
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_tmp18_ = _data2_->button;
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	gtk_container_add ((GtkContainer*) _tmp17_, (GtkWidget*) _tmp18_);
#line 78 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (_tmp16_);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (settings);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	block2_data_unref (_data2_);
#line 60 "/home/test/core/extensions/statusbar-features.vala"
	_data2_ = NULL;
#line 915 "statusbar-features.c"
}


static void
statusbar_features_frontend_real_activate (MidoriBrowserActivatable* base)
{
	StatusbarFeaturesFrontend * self;
	gchar* items = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar** _tmp2_;
	gchar** _tmp3_;
#line 81 "/home/test/core/extensions/statusbar-features.vala"
	self = (StatusbarFeaturesFrontend*) base;
#line 82 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = g_strdup ("auto-load-images;enable-javascript;enable-plugins");
#line 82 "/home/test/core/extensions/statusbar-features.vala"
	items = _tmp0_;
#line 83 "/home/test/core/extensions/statusbar-features.vala"
	_tmp1_ = items;
#line 83 "/home/test/core/extensions/statusbar-features.vala"
	_tmp3_ = _tmp2_ = g_strsplit (_tmp1_, ";", 0);
#line 938 "statusbar-features.c"
	{
		gchar** item_collection = NULL;
		gint item_collection_length1 = 0;
		gint _item_collection_size_ = 0;
		gint item_it = 0;
#line 83 "/home/test/core/extensions/statusbar-features.vala"
		item_collection = _tmp3_;
#line 83 "/home/test/core/extensions/statusbar-features.vala"
		item_collection_length1 = _vala_array_length (_tmp2_);
#line 83 "/home/test/core/extensions/statusbar-features.vala"
		for (item_it = 0; item_it < item_collection_length1; item_it = item_it + 1) {
#line 950 "statusbar-features.c"
			gchar* _tmp4_;
			gchar* item = NULL;
#line 83 "/home/test/core/extensions/statusbar-features.vala"
			_tmp4_ = g_strdup (item_collection[item_it]);
#line 83 "/home/test/core/extensions/statusbar-features.vala"
			item = _tmp4_;
#line 957 "statusbar-features.c"
			{
				const gchar* _tmp5_;
#line 84 "/home/test/core/extensions/statusbar-features.vala"
				_tmp5_ = item;
#line 84 "/home/test/core/extensions/statusbar-features.vala"
				if (g_strcmp0 (_tmp5_, "enable-javascript") == 0) {
#line 964 "statusbar-features.c"
					const gchar* _tmp6_;
#line 85 "/home/test/core/extensions/statusbar-features.vala"
					_tmp6_ = item;
#line 85 "/home/test/core/extensions/statusbar-features.vala"
					statusbar_features_frontend_add_toggle (self, _tmp6_, "text-x-script", _ ("Enable scripts"));
#line 970 "statusbar-features.c"
				} else {
					const gchar* _tmp7_;
#line 86 "/home/test/core/extensions/statusbar-features.vala"
					_tmp7_ = item;
#line 86 "/home/test/core/extensions/statusbar-features.vala"
					if (g_strcmp0 (_tmp7_, "auto-load-images") == 0) {
#line 977 "statusbar-features.c"
						const gchar* _tmp8_;
#line 87 "/home/test/core/extensions/statusbar-features.vala"
						_tmp8_ = item;
#line 87 "/home/test/core/extensions/statusbar-features.vala"
						statusbar_features_frontend_add_toggle (self, _tmp8_, "image-x-generic", _ ("Load images automatically"));
#line 983 "statusbar-features.c"
					} else {
						const gchar* _tmp9_;
#line 88 "/home/test/core/extensions/statusbar-features.vala"
						_tmp9_ = item;
#line 88 "/home/test/core/extensions/statusbar-features.vala"
						if (g_strcmp0 (_tmp9_, "enable-plugins") == 0) {
#line 990 "statusbar-features.c"
							const gchar* _tmp10_;
#line 89 "/home/test/core/extensions/statusbar-features.vala"
							_tmp10_ = item;
#line 89 "/home/test/core/extensions/statusbar-features.vala"
							statusbar_features_frontend_add_toggle (self, _tmp10_, "libpeas-plugin", _ ("Enable Netscape plugins"));
#line 996 "statusbar-features.c"
						} else {
							const gchar* _tmp11_;
#line 91 "/home/test/core/extensions/statusbar-features.vala"
							_tmp11_ = item;
#line 91 "/home/test/core/extensions/statusbar-features.vala"
							statusbar_features_frontend_add_toggle (self, _tmp11_, NULL, NULL);
#line 1003 "statusbar-features.c"
						}
					}
				}
#line 83 "/home/test/core/extensions/statusbar-features.vala"
				_g_free0 (item);
#line 1009 "statusbar-features.c"
			}
		}
#line 83 "/home/test/core/extensions/statusbar-features.vala"
		item_collection = (_vala_array_free (item_collection, item_collection_length1, (GDestroyNotify) g_free), NULL);
#line 1014 "statusbar-features.c"
	}
#line 94 "/home/test/core/extensions/statusbar-features.vala"
	statusbar_features_frontend_add_zoom (self);
#line 81 "/home/test/core/extensions/statusbar-features.vala"
	_g_free0 (items);
#line 1020 "statusbar-features.c"
}


StatusbarFeaturesFrontend*
statusbar_features_frontend_construct (GType object_type)
{
	StatusbarFeaturesFrontend * self = NULL;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	self = (StatusbarFeaturesFrontend*) g_object_new (object_type, NULL);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	return self;
#line 1032 "statusbar-features.c"
}


StatusbarFeaturesFrontend*
statusbar_features_frontend_new (void)
{
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	return statusbar_features_frontend_construct (STATUSBAR_FEATURES_TYPE_FRONTEND);
#line 1041 "statusbar-features.c"
}


static MidoriBrowser*
statusbar_features_frontend_real_get_browser (MidoriBrowserActivatable* base)
{
	MidoriBrowser* result;
	StatusbarFeaturesFrontend* self;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	self = (StatusbarFeaturesFrontend*) base;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	_tmp0_ = self->priv->_browser;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	result = _tmp1_;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	return result;
#line 1062 "statusbar-features.c"
}


static void
statusbar_features_frontend_real_set_browser (MidoriBrowserActivatable* base,
                                              MidoriBrowser* value)
{
	StatusbarFeaturesFrontend* self;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	self = (StatusbarFeaturesFrontend*) base;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	if (statusbar_features_frontend_real_get_browser (base) != value) {
#line 1075 "statusbar-features.c"
		MidoriBrowser* _tmp0_;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 14 "/home/test/core/extensions/statusbar-features.vala"
		_g_object_unref0 (self->priv->_browser);
#line 14 "/home/test/core/extensions/statusbar-features.vala"
		self->priv->_browser = _tmp0_;
#line 14 "/home/test/core/extensions/statusbar-features.vala"
		g_object_notify_by_pspec ((GObject *) self, statusbar_features_frontend_properties[STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY]);
#line 1085 "statusbar-features.c"
	}
}


static void
statusbar_features_frontend_class_init (StatusbarFeaturesFrontendClass * klass)
{
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	statusbar_features_frontend_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	g_type_class_add_private (klass, sizeof (StatusbarFeaturesFrontendPrivate));
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_statusbar_features_frontend_get_property;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_statusbar_features_frontend_set_property;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	G_OBJECT_CLASS (klass)->finalize = statusbar_features_frontend_finalize;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY, statusbar_features_frontend_properties[STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY] = g_param_spec_object ("browser", "browser", "browser", MIDORI_TYPE_BROWSER, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1105 "statusbar-features.c"
}


static void
statusbar_features_frontend_midori_browser_activatable_interface_init (MidoriBrowserActivatableIface * iface)
{
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	statusbar_features_frontend_midori_browser_activatable_parent_iface = g_type_interface_peek_parent (iface);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	iface->activate = (void (*) (MidoriBrowserActivatable*)) statusbar_features_frontend_real_activate;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	iface->get_browser = statusbar_features_frontend_real_get_browser;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	iface->set_browser = statusbar_features_frontend_real_set_browser;
#line 1120 "statusbar-features.c"
}


static void
statusbar_features_frontend_instance_init (StatusbarFeaturesFrontend * self)
{
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	self->priv = STATUSBAR_FEATURES_FRONTEND_GET_PRIVATE (self);
#line 1129 "statusbar-features.c"
}


static void
statusbar_features_frontend_finalize (GObject * obj)
{
	StatusbarFeaturesFrontend * self;
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontend);
#line 14 "/home/test/core/extensions/statusbar-features.vala"
	_g_object_unref0 (self->priv->_browser);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	G_OBJECT_CLASS (statusbar_features_frontend_parent_class)->finalize (obj);
#line 1143 "statusbar-features.c"
}


GType
statusbar_features_frontend_get_type (void)
{
	return statusbar_features_frontend_type_id;
}


GType
statusbar_features_frontend_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (StatusbarFeaturesFrontendClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) statusbar_features_frontend_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StatusbarFeaturesFrontend), 0, (GInstanceInitFunc) statusbar_features_frontend_instance_init, NULL };
	static const GInterfaceInfo midori_browser_activatable_info = { (GInterfaceInitFunc) statusbar_features_frontend_midori_browser_activatable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	statusbar_features_frontend_type_id = g_type_module_register_type (module, G_TYPE_OBJECT, "StatusbarFeaturesFrontend", &g_define_type_info, 0);
	g_type_module_add_interface (module, statusbar_features_frontend_type_id, MIDORI_TYPE_BROWSER_ACTIVATABLE, &midori_browser_activatable_info);
	return statusbar_features_frontend_type_id;
}


static void
_vala_statusbar_features_frontend_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec)
{
	StatusbarFeaturesFrontend * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontend);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	switch (property_id) {
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		case STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY:
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		g_value_take_object (value, midori_browser_activatable_get_browser ((MidoriBrowserActivatable*) self));
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		break;
#line 1181 "statusbar-features.c"
		default:
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		break;
#line 1187 "statusbar-features.c"
	}
}


static void
_vala_statusbar_features_frontend_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec)
{
	StatusbarFeaturesFrontend * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, STATUSBAR_FEATURES_TYPE_FRONTEND, StatusbarFeaturesFrontend);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
	switch (property_id) {
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		case STATUSBAR_FEATURES_FRONTEND_BROWSER_PROPERTY:
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		midori_browser_activatable_set_browser ((MidoriBrowserActivatable*) self, g_value_get_object (value));
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		break;
#line 1208 "statusbar-features.c"
		default:
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 13 "/home/test/core/extensions/statusbar-features.vala"
		break;
#line 1214 "statusbar-features.c"
	}
}


void
peas_register_types (GTypeModule* module)
{
#line 100 "/home/test/core/extensions/statusbar-features.vala"
	g_return_if_fail (module != NULL);
#line 100 "/home/test/core/extensions/statusbar-features.vala"
	statusbar_features_frontend_register_type (module);
#line 101 "/home/test/core/extensions/statusbar-features.vala"
	peas_object_module_register_extension_type (G_TYPE_CHECK_INSTANCE_CAST (module, peas_object_module_get_type (), PeasObjectModule), MIDORI_TYPE_BROWSER_ACTIVATABLE, STATUSBAR_FEATURES_TYPE_FRONTEND);
#line 1228 "statusbar-features.c"
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint
_vala_array_length (gpointer array)
{
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



